- include/common/ast/instruction.h
- include/common/errcode.h
- include/common/errinfo.h
- include/common/types.h
- include/interpreter/interpreter.h
- include/runtime/stackmgr.h
- include/validator/formchecker.h
- include/validator/validator.h
- lib/aot/compiler.cpp
- lib/ast/instruction.cpp
- lib/ast/module.cpp
- lib/interpreter/engine/control.cpp
- lib/interpreter/engine/engine.cpp
- lib/interpreter/instantiate/data.cpp
- lib/interpreter/instantiate/elem.cpp
- lib/interpreter/instantiate/global.cpp
- lib/interpreter/instantiate/import.cpp
- lib/interpreter/instantiate/module.cpp
- lib/support/log.cpp
- lib/validator/formchecker.cpp
- lib/validator/validator.cpp
- test/core/CMakeLists.txt
- test/core/coreTest.cpp
1. Define `blocktype` in control instructions.
2. Update loading in control instructions.
3. Update validator algorithm.
4. Implement multi-value returns in related instructions.
5. Implement multi-value returns in AOT.
6. Turn on `assert_invalid` in core tests.
7. Apply error logging in validator.
> WASM 1.1 control instructions implementation

- include/common/ast/module.h
- include/common/ast/type.h
- include/interpreter/interpreter.h
- include/runtime/instance/function.h
- include/runtime/instance/memory.h
- lib/aot/compiler.cpp
- lib/ast/module.cpp
- lib/interpreter/engine/engine.cpp
- lib/interpreter/instantiate/module.cpp
- lib/interpreter/interpreter.cpp
- lib/loader/loader.cpp
- tools/ssvm-aot/CMakeLists.txt
- tools/ssvm-aot/ssvmc.cpp
* Use mmap for memory allocation
* Remove Ctor
* Add dummy check for DivideByZero check
* Add check for floating point truncation
* Mangling names for outstanding import/export names
* Register signal handler before entering compiled function to handle
errors in compiled function
* Move exra `ctx` argument for all compiled function to static variable
`This`
* Set global variable in compiled module to extern constant for
optimization, and change back after optimization done
* Validate module before compiling
> [AOT] Use mprotect for memory boundary checking

- lib/aot/compiler.cpp
* Wasm require misalignment load/store working as normal. Forcing all
load/store to unalignment for now.
> [AOT] Force unalignment load/store

- include/common/configure.h
- include/runtime/instance/function.h
- include/runtime/instance/memory.h
- include/runtime/instance/type.h
- include/runtime/storemgr.h
- lib/interpreter/helper.cpp
- lib/interpreter/instantiate/data.cpp
- lib/interpreter/instantiate/elem.cpp
- lib/interpreter/instantiate/function.cpp
- lib/interpreter/instantiate/global.cpp
- lib/interpreter/instantiate/memory.cpp
- lib/interpreter/instantiate/module.cpp
- lib/interpreter/instantiate/table.cpp
- lib/interpreter/interpreter.cpp
- test/CMakeLists.txt
- test/memlimit/CMakeLists.txt
- test/memlimit/MemLimitTest.cpp
- tools/ssvm/ssvmr.cpp
1. Refactor function instance for saving spaces.
2. Use template in store manager to saving move operations.
3. Add memory page count limitations in configuration and tool.
> Memory page limitations

- include/common/configure.h
- include/common/log.h
- include/interpreter/interpreter.h
- include/loader/loader.h
- include/runtime/instance/memory.h
- include/runtime/instance/table.h
- include/validator/validator.h
- include/vm/vm.h
- lib/common/log.cpp
- lib/interpreter/interpreter.cpp
- lib/vm/vm.cpp
1. Add the SSVM::AST::Module input of load wasm functions in VM and Loader.
2. Add Debug and Error logging level setting functions.
3. Add the function overloading and quantifiers in memory and table instances.
4. Copy the configuration class for the independent module in VM partitions.
5. Always register as an anonymous module when instantiation.
> Refactor for SSVM C API.

- doc/externref.md
- include/ast/base.h
- include/ast/instruction.h
- include/ast/type.h
- include/common/configure.h
- include/common/statistics.h
- include/common/value.h
- include/interpreter/interpreter.h
- include/loader/loader.h
- include/runtime/instance/global.h
- include/runtime/instance/memory.h
- include/runtime/storemgr.h
- include/validator/validator.h
- include/vm/vm.h
- lib/interpreter/engine/control.cpp
- lib/interpreter/instantiate/import.cpp
- lib/interpreter/interpreter.cpp
- lib/vm/vm.cpp
- test/aot/AOTcoreTest.cpp
- test/externref/ExternrefTest.cpp
- test/interpreter/InterpreterTest.cpp
- test/spec/hostfunc.h
- test/spec/spectest.cpp
- test/spec/spectest.h
- tools/ssvm/ssvmr.cpp
1. Refactor SpecTest class for combining duplicated codes.
2. Apply function parameter type checking when calling wasm functions.
3. Update tools, doc, and tests.
> Value type checking when calling wasm functions

- cmake/FindFilesystem.cmake
- include/ast/instruction.h
- include/common/value.h
- include/experimental/expected.hpp
- include/runtime/stackmgr.h
- include/validator/formchecker.h
- lib/aot/CMakeLists.txt
- lib/aot/compiler.cpp
- lib/api/wasmedge.cpp
- lib/ast/CMakeLists.txt
- lib/host/wasmedge_process/CMakeLists.txt
- lib/interpreter/CMakeLists.txt
- lib/loader/CMakeLists.txt
- lib/system/mmap.cpp
- lib/validator/CMakeLists.txt
- test/aot/AOTCacheTest.cpp
- test/aot/AOTcoreTest.cpp
- test/expected/constructors.cpp
- test/expected/emplace.cpp
- test/externref/ExternrefTest.cpp
- test/host/wasi/wasi.cpp
- test/po/po.cpp
- tools/wasmedge/wasmedger.cpp
* Adjust library dependency
* Check for newer compilers in std::filesystem
* Add missing include files, fix typo
* Avoid helper function to prevent zero and pointer ambiguity
* Use u8path for path creation
* Run clang-format-11
* Remove extra semicolons
* Add unlisted enum entries in switch statements
* Use stof on float, stol on uint32_t
> Minor fixes

- thirdparty/wasi/api.hpp
- utils/wasi-cpp-header/Cargo.toml
- utils/wasi-cpp-header/change-tag-type.patch
- utils/wasi-cpp-header/generate.sh
- utils/wasi-cpp-header/remove-resource.patch
- utils/wasi-cpp-header/src/cpp_header.rs
- utils/wasi-cpp-header/src/lib.rs
- utils/wasi-cpp-header/src/main.rs
* Currently witx library didn't support `resource` tag, manually removed
from witx file.
* Currently witx library hides the typename of union tags, manually
added to header.
> [WASI] Update witx library, generate header again

- README-zh-TW.md
- README-zh.md
- README.md
- doc/install.md
- doc/run.md
We need a central place in doc to list all different ways to install WasmEdge. Each use case tutorials also need to detail their own installation steps.
> Add a install doc

- lib/api/wasmedge.cpp
> [API] Fix usused variables error when AOT build is disabled

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/rust.yml
> [CI] Don't need to check the ninja-build again. It's built-in deps in our docker images

- include/host/wasi/environ.h
- include/host/wasi/inode.h
- include/host/wasi/vinode.h
- include/host/wasi/wasifunc.h
- lib/host/wasi/inode-linux.cpp
- lib/host/wasi/inode-macos.cpp
- lib/host/wasi/inode-win.cpp
- lib/host/wasi/vinode.cpp
- lib/host/wasi/wasifunc.cpp
1. Fix the signature error with the lost read size output.
2. Add the `Ret_` prefix for parameter names with receiving outputs.
> [WASI] Fix the signature error of `path_read_link`.

- include/common/int128.h
Fix arm 32bit compile fail issue when C API is already disable
> Disabe `WASMEDGE_BUILD_AOT_RUNTIME` `WASMEDGE_BUILD_SHARED_LIB` `DWASMEDGE_BUILD_STATIC_LIB`
```bash
cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_TESTS=ON -DWASMEDGE_BUILD_AOT_RUNTIME=OFF -DWASMEDGE_BUILD_SHARED_LIB=OFF -DWASMEDGE_BUILD_STATIC_LIB=OFF .
cmake --build build
```
> [Misc] Include missing headers

- include/api/wasmedge.h.in
- include/common/int128.h
- lib/api/wasmedge.cpp
- test/api/APIStepsCoreTest.cpp
- test/api/APIUnitTest.cpp
- test/api/APIVMCoreTest.cpp
- test/api/helper.cpp
- test/api/helper.h
1. Add struct int128_t / uint128_t in c api layer 
2. Add some help functions covert between  struct and class ( about int128_t / uint128_t)
3. Verify compile result done both 32bit and non 32bit env
**Test environment**
- docker image:
wasmedge/wasmedge:ubuntu2004_armv7l
- Install tool-chain manually: 
```bash
apt update && apt install -y python3 xz-utils libssl-dev rpm build-essential gcc g++ llvm-12-dev liblld-12-dev ninja-build git curl wget m4 gcc-multilib g++-multilib cmake libboost-all-dev
```
- Build commands:
```bash
cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_TESTS=ON -DWASMEDGE_BUILD_AOT_RUNTIME=OFF .
cmake --build build
```
> [Misc] Enable c api in 32-bit environment

- README.md
- docs/ecosystem.md
- docs/integrations.md
- docs/use_cases.md
As we move docs and language binding SDKs, there are broken links in our system. We are fixing them as we encounter them.
> [Docs] Fix documentation links

- docs/use_cases-zh.md
Since the Second State Functions and Netlify Functions are the product names like AWS Lambda, they shouldn't be translated.
I also improve the hyperlinks of the TOC.
> [docs]Update use_cases-zh.md

- lib/executor/instantiate/elem.cpp
- Add assertion for nullptr before dereferencing
- File: https://github.com/WasmEdge/WasmEdge/blob/master/lib/executor/instantiate/elem.cpp
- Fixes #526 
- Fixes #530 
- Fixes #531
Signed-off-by: Avinal Kumar <avinal.xlvii@gmail.com>
> [Code Quality] Fix null dereference issues in elem.cpp

- lib/executor/instantiate/data.cpp
- Add assertion for nullptr before dereferencing
- File: https://github.com/WasmEdge/WasmEdge/blob/master/lib/executor/instantiate/data.cpp
- Fixes #525 
- Fixes #529
Signed-off-by: Avinal Kumar <avinal.xlvii@gmail.com>
> [Code Quality] Fix null dereference warnings

- utils/install.sh
Sorry that lost of the linking of `libpng.so`.
We should add the `libpng.so` -> `libpng16.so`, or the `-lpng` will error.
> [Utils] Add lost symbolic link: libpng.so -> libpng16.so.16.37.0

- include/ast/instruction.h
- include/runtime/instance/function.h
On MacOS, there's a situation that after instantiation, the expression vector of function instance A is connected after the expression vector of function instance B in memory.
Therefore when iterating the instructions in interpreter mode through the program counter, the expression `PC != PCEnd` of the while loop may cause unexpected end because the `A.expr.end()` is right equal to `B.expr.begin()`.
closes #453
closes #454
> Resolve the edge case for the nearby expressions in memory

- README.md
We have migrated from LGTM to CodeQL now. The LGTM app is suspended from this Github repo.
Closes #575 
> [Docs] Remove LGTM badges

- docs/externref.md
- include/executor/executor.h
- include/vm/vm.h
- lib/api/wasmedge.cpp
- lib/executor/executor.cpp
- lib/vm/vm.cpp
- test/aot/AOTcoreTest.cpp
- test/api/APIAOTCoreTest.cpp
- test/api/APIStepsCoreTest.cpp
- test/api/APIUnitTest.cpp
- test/api/APIVMCoreTest.cpp
- test/api/helper.cpp
- test/api/helper.h
- test/executor/ExecutorTest.cpp
- test/externref/ExternrefTest.cpp
- test/spec/spectest.cpp
- test/spec/spectest.h
- tools/wasmedge/wasmedger.cpp
The SIMD opcode spec test failed.
Mentioned at #558 
The last commit can help to check the value comparison, and can be deleted after fixing.
> Return the results with types for execution.

- .github/workflows/inventory.yml
Because there is no warning flow in GitHub CI, the prefix `Warning of` of the name of CI flow is used, such that developer can easily to know this CI flow is allowed to fail.
Fix #626
> [CI] Add inventory warning

- docs/go_api.md
Added go_api.md file.
References:
1. https://github.com/second-state/WasmEdge-go/blob/master/docs/go_api.md
2. https://www.secondstate.io/articles/extend-golang-app-with-webassembly-rust/
3. https://github.com/second-state/WasmEdge-go-examples
4. https://github.com/second-state/WasmEdge-go
5. https://github.com/second-state/WasmEdge-go-examples/tree/master/go_WasmAOT
> [Docs] Added go_api.md

- include/host/wasi/environ.h
- include/host/wasi/inode.h
- include/host/wasi/vinode.h
- include/host/wasi/wasifunc.h
- lib/host/wasi/inode-linux.cpp
- lib/host/wasi/inode-macos.cpp
- lib/host/wasi/vinode.cpp
- lib/host/wasi/wasifunc.cpp
As mentioned in #662, the sockAccept method does not require port parameter since it's not used from ServerSocketAddr. This pr is for removing the port parameter from the implementation and header file.
> Remove Port from sockAccept implementation for INode

- .github/workflows/rust-crate-release.yml
- bindings/rust/Cargo.toml
- flake.nix
Currently, we keep working on `wasmedge-sys` crate, and `wasmedge-sdk` will more focus on how to fit the usage of application layer.  Besides, it will redesign and provide later, so `wasmedge-sdk` is temporally removed.
Signed-off-by: Antonio Yang <yanganto@gmail.com>
> [Rust] Temp rm wasmedge-sdk

- bindings/rust/wasmedge-sys/src/executor.rs
- bindings/rust/wasmedge-sys/src/instance/function.rs
- bindings/rust/wasmedge-sys/src/store.rs
- bindings/rust/wasmedge-sys/src/types.rs
The following C-APIs are involved in this PR:
- Executor
- Fix #703 
- Fix #704 
- Function
- Fix #727 
- FunctionType
- Fix #731 
- Fix #729 
- WasmEdge_FunctionTypeGetReturnsLength
- WasmEdge_FunctionTypeGetReturns
> [Rust] Implement new APIs for Executor and FuncType

- .github/workflows/mdbook.yml
Github Actions will build and push the MDBOOK site to the www repo, which is then published as GitHub pages.
> [CI] Build and publish MDBOOK automatically

- .github/workflows/mdbook.yml
Auto triggers only occur when there is a push event in the docs/book folder
> [CI] Limit the MDBOOK action to merged book file updates

- include/po/argument_parser.h
The output text of the current help command is too compact, making it difficult for the user to read. Hopefully, the formatting can be spruced up and ASNI color codes used.
This commit have change some code in `include/po/argument_parser.h`, here's the preview:
> [Misc] Beautify help information

- bindings/rust/wasmedge-sys/src/lib.rs
- bindings/rust/wasmedge-sys/src/types.rs
This PR is to add the necessary description for the Enum types defined in the types module.
> [Rust] Added doc comments for enums defined in types.

- docs/install.md
- utils/install.sh
- utils/uninstall.sh
* [SAtacker] First checks if curl is installed else checks for wget
* [hydai] If wget has progress-bar option goes with it else it does not
* Suggestions from https://github.com/WasmEdge/WasmEdge/issues/966
and https://github.com/WasmEdge/WasmEdge/pull/958
Co-authored-by: hydai <hydai@secondstate.io>
> [Utils] Install Script: Changed first default and wget options

- bindings/rust/wasmedge-sys/src/executor.rs
- bindings/rust/wasmedge-sys/src/import_obj.rs
- bindings/rust/wasmedge-sys/src/store.rs
- bindings/rust/wasmedge-sys/src/types.rs
- bindings/rust/wasmedge-sys/src/vm.rs
In this PR, the `WasmEdgeString` struct is introduced as a wrapper of `WasmEdge_String`. In addition, to support the new design, refactored some parts of the `store`, `vm`, `import_obj`, and `executor` modules.
The following C-APIs are involved:
- `WasmEdge_StringCreateByBuffer`
- `WasmEdge_StringIsEqual`
> [Rust] Introduce the WasmEdgeString struct 

- bindings/rust/wasmedge-sys/examples/hostfunc.rs
- bindings/rust/wasmedge-sys/examples/hostfunc2.rs
- bindings/rust/wasmedge-sys/src/config.rs
- bindings/rust/wasmedge-sys/src/error.rs
- bindings/rust/wasmedge-sys/src/executor.rs
- bindings/rust/wasmedge-sys/src/instance/function.rs
- bindings/rust/wasmedge-sys/src/lib.rs
- bindings/rust/wasmedge-sys/src/store.rs
This PR is to refactor the function module and add a unit test for FuncType. The C APIs involved are
- Fix #695 
- Support `WasmEdge_ConfigureCompilerIsInterruptible`
- Support `WasmEdge_ConfigureCompilerSetInterruptible`
> [Rust] Refactored the function module

- .gitignore
- docs/book/en/src/SUMMARY.md
Signed-off-by: KernelErr <45716019+KernelErr@users.noreply.github.com>
> [Docs] Update .gitignore and fix python doc

- docs/book/en/src/embed/c/ref.md
Capitalized anchor name doesn't work.
> [Docs] Fix link anchor name in WasmEdge Book.

- utils/uninstall.sh
Fixes #1056 
* When grep gives empty results it leads to `sed` removing complete file.
* Added simple check to prevent this
> [Utils] Uninstall Script: Fix #1056

- docs/book/zh/src/os/android.md
- lib/host/wasi/CMakeLists.txt
- lib/host/wasi/inode-linux.cpp
- utils/android/standalone/build_for_android.sh
* Add Android Binoic libc support, minimun Android API Level 23.
* Add build script for Android NDK.
* Add Android build tutorial.
Signed-off-by: HangedFish <bravohangedman@outlook.com>
----
It is a basic Android platform support that can be used to verify that WasmEdge works on the Android platform.
There is still a lot of work to be done to bring WasmEdge to Android application development.
> [Android] Add basic Anroid support

- lib/host/wasi/inode-linux.cpp
There is a problem with the implementation of this check. As the first
element of sa_data array is sin_port and the first number of low ports
is zero, the function would not copy the sa_data even though the data is
valid in this circumstances.
Signed-off-by: KernelErr <me@lirui.tech>
> [WASI-Socket] Remove empty sa_data check

- bindings/rust/wasmedge-sys/Cargo.toml
- bindings/rust/wasmedge-sys/src/error.rs
- bindings/rust/wasmedge-sys/src/instance/instance.rs
- bindings/rust/wasmedge-sys/src/instance/mod.rs
- bindings/rust/wasmedge-sys/src/instance/module.rs
- bindings/rust/wasmedge-sys/src/lib.rs
- bindings/rust/wasmedge-sys/src/loader.rs
- bindings/rust/wasmedge-sys/src/module.rs
- bindings/rust/wasmedge-sys/src/store.rs
In this PR, the new `ModuleInstance` and the relevant C-APIs are supported in `wasmedge-sys`. Along with this PR, the version of `wasmedge-sys` comes to `0.4.1`.
> [Rust] Supported ModuleInstance and the relevant C-APIs

- include/executor/executor.h
- include/runtime/instance/function.h
- include/runtime/instance/module.h
- include/runtime/stackmgr.h
- include/runtime/storemgr.h
- lib/api/wasmedge.cpp
- lib/executor/engine/controlInstr.cpp
- lib/executor/engine/engine.cpp
- lib/executor/engine/proxy.cpp
- lib/executor/engine/variableInstr.cpp
- lib/executor/executor.cpp
- lib/executor/helper.cpp
- lib/executor/instantiate/data.cpp
- lib/executor/instantiate/elem.cpp
- lib/executor/instantiate/function.cpp
- lib/executor/instantiate/global.cpp
- lib/executor/instantiate/import.cpp
- lib/executor/instantiate/memory.cpp
- lib/executor/instantiate/module.cpp
- lib/executor/instantiate/table.cpp
- lib/vm/vm.cpp
- test/aot/AOTcoreTest.cpp
- test/executor/ExecutorTest.cpp
1. The instance real pointer (allocated as unique pointers) will not changed until destroyed. Therefore it's safe to use pointer to instances.
2. Record the pointers of instances in module instances rather than addresses in store manager.
3. Use the module instance pointer in stack manager.
4. Use the unsafe getter of instances in calling frames to avoid the thread-safe bottleneck.
After applying this PR, about the 35% execution time reduced when running the `miniruby` example in #1016 .
> Pointer-based mechanism in store and module instance

- .github/workflows/wasmedge-sys-docs.yml
In this PR, a new CI workflow is implemented for publishing the rustdoc of  the `wasmedge-sys` crate to github pages.
To enable the Github Pages feature, it is required to specify the `Source` as shown in the red rectangle below:
- [actions-gh-pages](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-deploy-to-external-repository-external_repository)
- [rust-analyzer rustdoc.yaml](https://github.com/rust-analyzer/rust-analyzer/blob/master/.github/workflows/rustdoc.yaml)
- [Prepare your Rust API docs for Github Pages](https://dev.to/deciduously/prepare-your-rust-api-docs-for-github-pages-2n5i)
> [CI] Added workflow for publishing rustdoc.

- .github/workflows/rust-types-crate-release.yml
- .github/workflows/rust-types-docs.yml
- bindings/rust/Cargo.toml
- bindings/rust/wasmedge-types/Cargo.toml
- bindings/rust/wasmedge-types/README.md
- bindings/rust/wasmedge-types/src/lib.rs
In this PR, the `wasmedge-types` crate is created. This crate contains the data structures used in the future versions of both `wasmedge-sys` and `wasmedge-rs` crates.
* This PR should be tagged as `rust-types/0.1.0`.
> [Rust] wasmedge-types v0.1.0

- include/executor/executor.h
- lib/executor/engine/engine.cpp
This PR is able to solve `Stat` incorrect values which will call atomic_bool::load to check
(code position: [ lib/executor/engine/engine.cpp:1619L ](https://github.com/WasmEdge/WasmEdge/blob/master/lib/executor/engine/engine.cpp#L1618-L1621)).
* In Executor constructor: Set `Stat`  value `nullptr` if  default , and set `Stat` value `S` if collect statistics information. (the Value `S` refer to the [VM constructor](https://github.com/WasmEdge/WasmEdge/blob/master/lib/vm/vm.cpp#L16-L24) 
* Modify `PC->getOpCode()` into `if (Stat)` block since  it will only be called in this case.
Fixes #1381 
Signed-off-by: eat4toast <shihaohang@outlook.com>
> [bug] fix Stat incorrect initialize value

- bindings/rust/wasmedge-types/Cargo.toml
- bindings/rust/wasmedge-types/src/lib.rs
In this PR, `wat2wasm` is introduced in `wasmedge-types`. The version of `wasmedge-types` comes to `v0.1.1`.
> [Rust] Defined wat2wasm in wasmedge-types.

- bindings/rust/wasmedge-types/Cargo.toml
- bindings/rust/wasmedge-types/src/error.rs
- bindings/rust/wasmedge-types/src/lib.rs
In this PR, a new `error` module is implemented in the `wasmedge-types` crate. The version of `wasmedge-types` comes to `v0.1.2`.
> [Rust] Added the error module in wasmedge-types crate.

- lib/executor/executor.cpp
> [Executor] Remove the unnecessary std::move.

- test/api/APIUnitTest.cpp
> [Test] Fix the using of deleted configure in the API unit tests.

- docs/book/en/src/SUMMARY.md
> [Docs] Fix the book linking of old API references.

- lib/host/wasi_nn/wasinnfunc.cpp
fix the bug : `WasiNNInitExecCtx` shouldn't push the `GraphId` to `GraphContextBackends` but the backend flag for this `GraphId`
> [WASI] fix(wasinnfunc): add backend flag for context

- test/api/APIAOTCoreTest.cpp
- tools/wasmedge/wasmedgec.cpp
> [Tools] Fix the extension name for shared library format in AOT compiler

- bindings/rust/wasmedge-sys/Cargo.toml
- bindings/rust/wasmedge-sys/examples/func_call_across_different_modes.rs
- bindings/rust/wasmedge-sys/src/instance/module.rs
- bindings/rust/wasmedge-sys/src/lib.rs
- bindings/rust/wasmedge-sys/src/store.rs
- bindings/rust/wasmedge-sys/src/vm.rs
In this PR, the `AsInstance` trait is introduced into `wasmedge-sys` crate and implemented for WasiModule and WasmEdgeProcessModule.
> [Rust] Introduce AsInstance trait in wasmedge-sys crate

- .github/workflows/rust-wasmedge-sdk-release.yml
In this PR, the `nightly` channel of Rust substitutes for the `stable` in `rust-wasmedge-sdk-release` workflow.
Signed-off-by: Xin Liu <sam@secondstate.io>
> [Rust] Used nightly channel of Rust

- utils/install.sh
Previously `. "./wasmedge/env"` will be written to my .zshrc if `-p ./wasmedge` is specific.
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
> [Utils] Installer Script: Prevent writing relative path to login shell profile

- .github/workflows/bindings-rust.yml
The workflow tests rust bindings on windows -
1. In the standalone mode
2. By specifying the WASMEDGE_BUILD_DIR variable
Resolves issue: #1504
> [CI] Add workflow to test rust bindings on Windows

- utils/android/app/lib/build.gradle
Signed-off-by: yixingjia@gmail.com
Previous PR move the example out of the tools folder which will cause
the app cannot load the wasm file.
> Point to the right directoy for wasm examples

- docs/book/en/src/extend/plugin.md
To help readers understand the Plug-in docs, I added a ToC for it.
> Add ToC of plug-in docs

- lib/api/CMakeLists.txt
Fix #1548
`ar` from Xcode toolchain doesn't have option `--output`.
> [Misc] Enable WasmEdge C API static library on macOS

- .github/workflows/release.yml
- Update files according to https://bugzilla.redhat.com/show_bug.cgi?id=2035222
- Add `wasmedge.spec` to release assets
- Add comment above `ExclusiveArch` in spec file
- Rename SRPM and spec files to all lower cases
- Remove `wasmedge-lib` package
- Test release workflow in my own fork: https://github.com/dm4/WasmEdge/runs/6916370789?check_suite_focus=true
> [CI] Add Fedora RPM spec file to release assets

- rpm/wasmedge.spec.in
- Accroding to https://bugzilla.redhat.com/show_bug.cgi?id=2035222#c24 , we should:
> [RPM] Update RPM spec file

- bindings/rust/wasmedge-sdk/examples/hello_world.rs
- bindings/rust/wasmedge-sdk/src/externals/memory.rs
- docs/book/en/src/SUMMARY.md
- docs/book/en/src/embed/rust.md
- docs/book/en/src/embed/rust/memory_manipulation.md
- docs/book/en/src/embed/rust/say_hello.md
- docs/book/en/src/embed/rust/table_and_funcref.md
- docs/book/en/src/extend/plugin/externref.md
- docs/book/en/src/extend/plugin/loadable.md
In this PR, new examples for demonstrating `wasmedge-sdk` are added; in addition, the sections about the `standalone` build mode are removed.
> [Rust] Updated WasmEdge Book with new examples.

- lib/aot/compiler.cpp
Reference: https://reviews.llvm.org/D97799
> [Compiler] lld on macho requires -arch and -platform_version to always be specified

- docs/CONTRIBUTING.md
- utils/docker/Dockerfile.ubuntu2004_x86_64
Following with outdated contribute page will get this error:
```
-- Linker detection: GNU ld
CMake Error at lib/aot/CMakeLists.txt:9 (find_package):
Could not find a package configuration file provided by "LLD" with any of
the following names:
LLDConfig.cmake
lld-config.cmake
Add the installation prefix of "LLD" to CMAKE_PREFIX_PATH or set "LLD_DIR"
to a directory containing one of the above files.  If "LLD" provides a
separate development package or SDK, be sure it has been installed.
-- Configuring incomplete, errors occurred!
See also "/home/cat/WasmEdge/build/CMakeFiles/CMakeOutput.log".
See also "/home/cat/WasmEdge/build/CMakeFiles/CMakeError.log".
```
llvm-12 is required.
Or a better option is to link the build section to [https://wasmedge.org/book/en/extend/build.html](https://wasme …
> [Docs] Fix outdated contributing page

- lib/aot/compiler.cpp
Hi WasmEdge team
We're building WasmEdge statically inside another existing build system and this system is using `-Werror=uninitialized`.  As a result we're getting an error at the two lines fixed by this commit. We could hot patch in the build engine but better to PR this. Thanks! 😇
> Fix uninitialized variable warning

- bindings/rust/wasmedge-sdk/examples/hostfunc_call_chain.rs
- bindings/rust/wasmedge-sdk/src/externals/function.rs
- bindings/rust/wasmedge-sdk/src/import.rs
- bindings/rust/wasmedge-sdk/src/lib.rs
- bindings/rust/wasmedge-sdk/src/vm.rs
- bindings/rust/wasmedge-sys/examples/call_hostfunc_chain.rs
- bindings/rust/wasmedge-sys/examples/threads.rs
- bindings/rust/wasmedge-sys/src/instance/function.rs
- bindings/rust/wasmedge-sys/src/lib.rs
- bindings/rust/wasmedge-sys/src/vm.rs
In this PR, a new global host function storing mechanism is introduced for the single-thread use cases, such as hostfunc call chaining. `wasmedge-sys` and `wasmedge-sdk` get involved in this PR.
> [Rust] Introduced new host function storing design for the single-thread scenario

- include/common/errinfo.h
- include/po/argument_parser.h
Caught by Debian's lintian.
Signed-off-by: Faidon Liambotis <paravoid@debian.org>
> spelling: infomation -> information

- lib/driver/tool.cpp
> [Tools] Add the lost WASI-NN host function registration in tools.

- utils/install.sh
In POSIX, path `xx/lib:` means two pathes, one is `xx/lib`, another is
`.` (an empty path after ':' means `.`).
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
> [Utils] Don't add current directory to path if the $XX_PATH is empty

- .github/workflows/release.yml
> [CI] Fix the wasi-crypto upload path in release CI.

- .github/workflows/rust-wasmedge-sdk-docs.yml
- .github/workflows/rust-wasmedge-sdk-release.yml
- .github/workflows/rust-wasmedge-sys-docs.yml
- .github/workflows/rust-wasmedge-sys-release.yml
- .github/workflows/rust-wasmedge-types-docs.yml
In this PR, `rust-wasmedge-sys-release` and `rust-wasmedge-sdk-release` workflows are refactored for publishing. In addition, `rust-wasmedge-types-docs`, `rust-wasmedge-sys-docs`, and `rust-wasmedge-sdk-docs` are also refactored.
> [Rust][CI] Refactored workflows related to Rust bindings for publishing crates.

- docs/book/en/src/kubernetes/cri/containerd.md
- docs/book/en/src/kubernetes/demo/server.md
- docs/book/en/src/kubernetes/demo/wasi.md
- docs/book/en/src/kubernetes/kubernetes/kind.md
- docs/book/en/src/kubernetes/kubernetes/kubeedge.md
- docs/book/en/src/kubernetes/kubernetes/kubernetes-containerd.md
- docs/book/en/src/kubernetes/kubernetes/kubernetes-crio.md
- docs/book/en/src/kubernetes/kubernetes/openyurt.md
- docs/book/en/src/kubernetes/kubernetes/superedge.md
- docs/book/zh/src/kubernetes/cri/containerd.md
- docs/book/zh/src/kubernetes/demo/server.md
- docs/book/zh/src/kubernetes/demo/wasi.md
- docs/book/zh/src/kubernetes/kubernetes/kind.md
- docs/book/zh/src/kubernetes/kubernetes/kubeedge.md
- docs/book/zh/src/kubernetes/kubernetes/kubernetes-containerd.md
- docs/book/zh/src/kubernetes/kubernetes/kubernetes-crio.md
- docs/book/zh/src/kubernetes/kubernetes/openyurt.md
As mentioned by #1692 and #1338,
in case only wasm apps are used the module.wasm.image/variant: compat-smart annotation should behave exactly like the module.wasm.image/variant: compat annotation. It should only make a difference when standard OCI containers and wasm apps are in the same pod.
So we can update all examples to compat-smart.
> [Docs] use the annotation "module.wasm.image/variant: compat-smart" instead of "module.wasm.image/variant: compat"

- bindings/rust/wasmedge-sys/examples/hostfunc.rs
- bindings/rust/wasmedge-sys/examples/hostfunc2.rs
Fix errors in `hostfunc.rs` and `hostfunc2.rs`.
> [Rust]: Fix errors in examples.

- bindings/rust/wasmedge-sdk/src/externals/memory.rs
- bindings/rust/wasmedge-sys/src/instance/memory.rs
This PR is to refactor `Memory::write` method in `wasmedge-sdk` and `Memory::set_data` method in `wasmedge-sys`.
- Fixed #1728
> [Rust] Refactored Memory::write method in `wasmedge-sdk`

- .github/workflows/mdbook.yml
Fixes #1723
The modified workflow works as described below:
- PRs: first check the markdown format, lint or start building mdbook
- Pulls: skip the format check (to prevent it breaks releasing the latest version of mdbook)
The only uncertain thing is, build-mdbook will be triggered even if the changed files are `docs/**` && `!docs/book/**`, should I separate the format check into a new workflow? any good suggestion?
> [CI] Check markdown format for pr (all rules in markdownlint)

- include/api/wasmedge/wasmedge.h
- lib/api/wasmedge.cpp
- test/api/APIAOTCoreTest.cpp
- test/api/APIUnitTest.cpp
- test/api/hostfunc_c.c
* Compile a wasm byte array into the native binary.
* Get the native handler from a given WASI mapped fd or handler.
> Expose two helper functions in C API

- README-zh-TW.md
"语言" is a Simplified Chinese term. I changed it to the corresponding Traditional Chinese term.
Signed-off-by: Chih-Hsuan Yen <yan12125@gmail.com>
> README-zh-TW: get rid of Simplified Chinese

- lib/aot/compiler.cpp
> [AOT] Fix the lld warning of sdk_version on LLVM 14.

- .CurrentChangelog.md
- Changelog.md
- include/api/wasmedge/wasmedge.h
- lib/api/wasmedge.cpp
- test/api/APIUnitTest.cpp
> [CAPI] Use 'FromBuffer' instead of 'FromArray'

- plugins/wasi_crypto/CMakeLists.txt
- plugins/wasi_crypto/asymmetric_common/ecdsa.h
- plugins/wasi_crypto/signatures/rsa.cpp
- plugins/wasi_crypto/signatures/rsa.h
- plugins/wasi_crypto/symmetric/kdf.cpp
- plugins/wasi_crypto/symmetric/kdf.h
- plugins/wasi_crypto/utils/evp_wrapper.h
* Use `OPENSSL_API_COMPAT` macro for old api interface
> [Plugin] Support openssl3 on wasi-crypto plugin

- include/host/wasi/environ.h
- lib/host/wasi/inode-linux.cpp
- lib/host/wasi/inode-macos.cpp
- lib/host/wasi/inode-win.cpp
- test/host/socket/wasi_socket.cpp
Fix #1372
* Breaking change: remove `kSaDataLen`, use `kMaxSaDataLen` instead.
Signed-off-by: LFsWang <tnst92002@gmail.com>
> [Socket] Adjust kSaDataLen on IPv6 case

- examples/capi/host_functions/parse_json/Makefile
- examples/capi/host_functions/parse_json/README.md
- examples/capi/host_functions/parse_json/host_function.c
Port the "parse_json" example to the 0.10 and 0.11 API. This entails porting WasmEdge_ImportObject* to WasmEdge_ModuleInstance*, as well as WasmEdge_MemoryInstanceContext -> WasmEdge_CallingFrameContext.
While at it, add a Makefile and adjust the README.
Signed-off-by: Faidon Liambotis <paravoid@debian.org>
> Port the "parse_json" example to the newer API

- include/loader/loader.h
- lib/loader/ast/instruction.cpp
- lib/loader/ast/module.cpp
- lib/loader/ast/section.cpp
- lib/loader/ast/segment.cpp
- lib/loader/ast/type.cpp
- lib/loader/shared_library.cpp
1. This will cause universal WASM fail.
2. The error code of load fail case may be incorrect if the syntax error occurs before reach the file end.
> [Loader] Revert commit 19895708eb867e3f193f69e3b5420a6586d2a6e3

- .github/workflows/rust-wasmedge-macro-release.yml
- .github/workflows/rust-wasmedge-types-docs.yml
- .github/workflows/rust-wasmedge-types-release.yml
- bindings/rust/wasmedge-macro/Cargo.toml
In this PR, `wasmedge-types v0.3.0` is ready to release. The tag for this release is `rust-types/0.3.0`.
> [Rust] wasmedge-types v0.3.0

- utils/install.sh
The reason is we need different WasmEdge with system environment os-arch version when docker cross compile image
> [Installer] add new options that user could specify os and arch for installer

- utils/install.sh
This commit fixes the following error:
```
main: line 437: [: missing `]'
```
Signed-off-by: Hiroaki Nakamura <hnakamur@gmail.com>
> [Utils] Installer: Fix missing ] error

- .github/workflows/build-extensions.yml
> [CI] Fix LLVM linking on MacOS 12 when building extensions.

- .github/workflows/inventory.yml
- bindings/rust/wasmedge-sys/src/instance/memory.rs
- bindings/rust/wasmedge-sys/src/utils.rs
- include/api/wasmedge/wasmedge.h
- include/common/log.h
- lib/api/wasmedge.cpp
- lib/common/log.cpp
- test/api/APIUnitTest.cpp
avoid some error log confuse users when migrate wasmedge into other production
> I think the error (ex. interrupt) msg should be able hide thus avoid scare user (?
Signed-off-by: vincent <vincent@secondstate.io>
> [Misc] Add off log system api

- include/common/roundeven.h
#1909 
> A strict rule is: Never ever write to an input operand. ...
> By http://www.ethernut.de/en/documents/arm-inline-asm.html
So I take [llvm's code](https://github.com/llvm/llvm-project/blob/main/libc/src/__support/FPUtil/aarch64/nearest_integer.h) as an example to change it. I can pass the test failed by "simd_f64x2_rounding" on M1 chip after this commit.
I'm also wondering whether we should add __volatile__ to prevent from compiler optimization.
> Fix the test failed on M1

- bindings/rust/wasmedge-sdk/src/lib.rs
- bindings/rust/wasmedge-sdk/src/log.rs
- bindings/rust/wasmedge-sys/src/utils.rs
In this PR, a new `LogManager` is introduced into `wasmedge-sdk` crate.
> [Rust] Implement LogManager

- bindings/rust/wasmedge-sdk/examples/hostfunc_call_chain.rs
- bindings/rust/wasmedge-sdk/src/externals/function.rs
- bindings/rust/wasmedge-sdk/src/import.rs
- bindings/rust/wasmedge-sys/examples/call_hostfunc_chain.rs
- bindings/rust/wasmedge-sys/src/instance/function.rs
- bindings/rust/wasmedge-sys/src/lib.rs
In this PR, the following deprecated APIs are removed from Rust bindings:
- `wasmedge_sdk::Func::wrap_single_thread`
- `wasmedge_sdk::ImportBuilder::with_func_single_thread`
- `wasmedge_sys::Function::create_single_thread`
In addition, those test cases affected by the changes are also updated.
> [Rust] Remove the deprecated APIs

- .github/workflows/release.yml
- utils/docker/Dockerfile.release
Fix #1987. 
- Install netbase for `/etc/services` file.
- Preserve network related libs.
- Steps to verify (use http-client.wasm from #1987. for testing):
```
git clone https://github.com/WasmEdge/WasmEdge.git -b fix-1987
cd WasmEdge/
curl -Lo utils/docker/WasmEdge-0.11.1-Linux.tar.gz https://github.com/WasmEdge/WasmEdge/releases/download/0.11.1/WasmEdge-0.11.1-manylinux2014_x86_64.tar.gz
docker-slim build \
--dockerfile Dockerfile.release \
--dockerfile-context utils/docker \
--tag wasmedge/fix-1987 \
--http-probe-off \
--include-bin /usr/lib/x86_64-linux-gnu/libnss_compat.so.2 \
--include-bin /usr/lib/x86_64-linux-gnu/libnss_dns.so.2 \
--include-bin /usr/lib/x86_64-linux-gnu/libnss_files.so.2 \
--include-bin /usr/lib/x86_64-linux-gnu/libresolv.so.2 \
--include-path /etc/services \ …
```
> [CI] Add network libs into slim images

- .github/workflows/rust-wasmedge-sdk-release.yml
- .github/workflows/rust-wasmedge-sys-release.yml
In this PR, we replaced `llvm-12` with `llvm-14` in the release workflows for `wasmedge-sys` and `wasmedge-sdk`.
Using `llvm-12` causes the same issue as #1821.
> [CI] Refactor the release workflows for Rust SDK

- .github/workflows/bindings-rust.yml
- bindings/rust/wasmedge-macro/src/lib.rs
- bindings/rust/wasmedge-sdk/Cargo.toml
- bindings/rust/wasmedge-sdk/examples/hello_world.rs
- bindings/rust/wasmedge-sdk/examples/run_func_in_aot_mode.rs
- bindings/rust/wasmedge-sdk/src/compiler.rs
- bindings/rust/wasmedge-sys/Cargo.toml
- bindings/rust/wasmedge-sys/src/compiler.rs
In this PR, a critical bug in the `create` method of `wasmedge_sys::Compiler` is fixed. The version of `wasmedge-sys` bumps to `0.11.1`.
> [Rust] Fix a bug in wasmedge_sys::Compiler

- bindings/rust/wasmedge-sdk/examples/async_hello_world.rs
- bindings/rust/wasmedge-sdk/src/module.rs
- bindings/rust/wasmedge-sdk/src/vm.rs
- bindings/rust/wasmedge-sys/examples/async_run_registered_func.rs
- bindings/rust/wasmedge-sys/examples/fibonacci.rs
- bindings/rust/wasmedge-sys/examples/store_get_named_module.rs
- bindings/rust/wasmedge-sys/src/vm.rs
In this PR, some new APIs are introduced into `Vm` and `Module` of `wasmedge-sdk` to support `wat` files. In addition, improve the implementation of some APIs in `Vm` to support `AOT` files.
> [Rust] Support wat files

- lib/validator/validator.cpp
- test/spec/hostfunc.h
This PR passed the newest spec tests on the branch `wasm-dev` in [WasmEdge unittest repo](https://github.com/second-state/WasmEdge-unittest/tree/wasm-dev), except the `threads` proposal.
Therefore, the `wasm-dev-0.11.0` tag should be used currently until the `threads` proposal implementation being fixed.
> [Validator] Fix the error code when element segment mismatch.

- bindings/java/wasmedge-jni/lib/ValueType.c
- bindings/rust/wasmedge-sdk/src/types.rs
- bindings/rust/wasmedge-sys/src/types.rs
- bindings/rust/wasmedge-types/src/lib.rs
- include/ast/instruction.h
- include/common/enum.inc
- include/common/types.h
- include/loader/loader.h
- lib/aot/compiler.cpp
- lib/api/wasmedge.cpp
- lib/common/errinfo.cpp
- lib/loader/ast/instruction.cpp
- lib/loader/ast/segment.cpp
- lib/loader/ast/type.cpp
- lib/loader/filemgr.cpp
- lib/loader/loader.cpp
- lib/validator/formchecker.cpp
- test/errinfo/errinfoTest.cpp
This PR fixes #2029.
It is based on #2030, and currently include the change in #2030. Should be after #2030.
> feat: remove none type from val type

- .github/workflows/bindings-rust.yml
- .github/workflows/rust-standalone.yml
- .github/workflows/rust-wasmedge-macro-release.yml
- .github/workflows/rust-wasmedge-sdk-release.yml
- .github/workflows/rust-wasmedge-sys-release.yml
- .github/workflows/rust-wasmedge-types-release.yml
- bindings/rust/wasmedge-sdk/Cargo.toml
- bindings/rust/wasmedge-sdk/src/executor.rs
- bindings/rust/wasmedge-sys/Cargo.toml
- bindings/rust/wasmedge-sys/build.rs
In this PR, the `standalone` feature is introduced into WasmEdge Rust SDK.
In addition, the changes in PR #2076 are cancelled. The explanations are listed [here](https://github.com/WasmEdge/WasmEdge/issues/2075#issuecomment-1319695523) and [here](https://github.com/WasmEdge/WasmEdge/issues/2075#issuecomment-1319931003).
> [Rust] Add standalone feature

- bindings/rust/wasmedge-sdk/Cargo.toml
- bindings/rust/wasmedge-sdk/examples/async_hello_world.rs
- bindings/rust/wasmedge-sdk/examples/async_run_func.rs
- bindings/rust/wasmedge-sdk/src/externals/function.rs
- bindings/rust/wasmedge-sdk/src/import.rs
- bindings/rust/wasmedge-sdk/src/vm.rs
- bindings/rust/wasmedge-sys/Cargo.toml
- bindings/rust/wasmedge-sys/examples/async_host_func.rs
- bindings/rust/wasmedge-sys/examples/async_host_func_indirect.rs
- bindings/rust/wasmedge-sys/examples/async_run_func.rs
- bindings/rust/wasmedge-sys/examples/async_run_registered_func.rs
- bindings/rust/wasmedge-sys/examples/async_run_wasm_from_bytes.rs
- bindings/rust/wasmedge-sys/examples/async_run_wasm_from_file.rs
- bindings/rust/wasmedge-sys/src/instance/function.rs
- bindings/rust/wasmedge-sys/src/lib.rs
- bindings/rust/wasmedge-sys/src/vm.rs
The `async` features are added in `wasmedge-sdk` and `wasmedge-sys` crates, respectively.
> [Rust] Add async feature

- lib/host/wasi/inode-macos.cpp
Signed-off-by: Tricster <mediosrity@gmail.com>
Solve #2104 
This pr adds two missing functions on macos, `sockGetLocalAddr` and `sockGetPeerAddr`.
The implementations are from the linux version.
> [WASI] Add missing network functions on macos.

- .github/workflows/rust-wasmedge-sdk-release.yml
- .github/workflows/rust-wasmedge-sys-release.yml
In this PR, the `cargo-smart-release` tool is replaced with the standard `cargo publish`. The changes are made in`rust-wasmedge-sys-release` and `rust-wasmedge-sdk-release`.
> [CI] Update the workflows for Rust SDK release

- bindings/rust/wasmedge-sys/src/utils.rs
- bindings/rust/wasmedge-types/src/error.rs
The changes made to the error definition are rolled back for releasing `wasmedge-sys`.
> [Rust] rollback the changes on the error definition

- .github/workflows/rust-standalone.yml
In this PR, the original `build_ubuntu` job in `rust-standalone` workflow is split into two separate jobs: one for `ubuntu-20.04` with `llvm-12` installed, one for `ubuntu-22.04` with `llvm-14` installed.
> [CI] Refactor rust-standalone workflow

- .github/workflows/bindings-rust.yml
- .github/workflows/rust-standalone.yml
- .github/workflows/rust-wasmedge-macro-release.yml
- .github/workflows/rust-wasmedge-sdk-release.yml
- .github/workflows/rust-wasmedge-sys-release.yml
- .github/workflows/rust-wasmedge-types-release.yml
In this PR, refactor the Rust SDK related workflows to use `dtolnay/rust-toolchain@stable`.
> [CI] Refactor rust workflows

- .github/workflows/bindings-rust.yml
- .github/workflows/rust-standalone.yml
- bindings/rust/wasmedge-sdk/Cargo.toml
- bindings/rust/wasmedge-sdk/examples/create_host_func_in_host_func.rs
- bindings/rust/wasmedge-sdk/examples/executor_register_active_module.rs
- bindings/rust/wasmedge-sdk/examples/executor_register_named_module.rs
- bindings/rust/wasmedge-sdk/examples/hello_world.rs
- bindings/rust/wasmedge-sdk/examples/memory.rs
- bindings/rust/wasmedge-sdk/examples/multi_value.rs
- bindings/rust/wasmedge-sdk/examples/table.rs
- bindings/rust/wasmedge-sdk/examples/table_and_funcref.rs
- bindings/rust/wasmedge-sdk/src/externals/function.rs
In this PR, the following changes are introduced:
- Refactored the signature of `call` methods of `Func` and `FuncRef` structs, respectively
- Updated the `rust-standalone` workflow
- Updated the `bindings-rust` workflow to support Rust `1.64`, `1.65`, and `1.66`
> [Rust] Refactor call method

- utils/install.py
> [Utils] python installer: use {0} instead of %s

- plugins/wasi_crypto/symmetric/kdf.cpp
> fix: `symmetric_state_squeeze` for arbitrary-long output

- utils/install.py
- utils/installer_changes.sh
- Fix CI not failing due to installer link specified of master branch
- Ref - https://github.com/WasmEdge/WasmEdge/issues/2217
> [Utils] Installer and CI: Fix installer appending incorrect filename

- docs/book/en/src/features/platforms.md
Corrects a typo on the [supported platforms page](https://wasmedge.org/book/en/features/platforms.html) .
That's all
> docs(platforms): correct typo: respberry -> raspberry

- bindings/rust/wasmedge-sdk/src/externals/function.rs
- bindings/rust/wasmedge-sdk/src/externals/global.rs
- bindings/rust/wasmedge-sdk/src/externals/memory.rs
- bindings/rust/wasmedge-sdk/src/externals/table.rs
- bindings/rust/wasmedge-sys/src/frame.rs
- bindings/rust/wasmedge-sys/src/instance/function.rs
- bindings/rust/wasmedge-sys/src/instance/global.rs
- bindings/rust/wasmedge-sys/src/instance/memory.rs
- bindings/rust/wasmedge-sys/src/instance/module.rs
- bindings/rust/wasmedge-sys/src/instance/table.rs
In this PR, the `Clone` trait is implemented for `Func`, `Memory`, `Global` and `Table` external instances.
> [Rust] Implement Clone trait for external instances

- include/host/wasi/environ.h
- include/host/wasi/inode.h
- include/host/wasi/vinode.h
- lib/host/wasi/inode-linux.cpp
- lib/host/wasi/inode-macos.cpp
- lib/host/wasi/inode-win.cpp
- lib/host/wasi/wasifunc.cpp
https://github.com/WasmEdge/WasmEdge/pull/1599 seems to have introduced a typo in the name of this function.
Signed-off-by: Achille Roussel <achille.roussel@gmail.com>
> fix typo: sockGetLoaclAddr => sockGetLocalAddr

- test/CMakeLists.txt
- test/spec/spectest.cpp
- Add compiler option to ignore out-of-line static constexpr data member declarations
- Initialise un-initialised variables
Resolves: #2224
> [Windows] Fix building tests on Windows

- lib/host/wasi/wasifunc.cpp
> [Socket] fix SockGetPeerAddr buffer size

- utils/install.py
Export WASMEDGE_LIB_DIR to installation-path/lib if unset
- Ref-https://github.com/WasmEdge/WasmEdge/issues/2303
> [Utils] Installer: Export WASMEDGE_LIB_DIR

- .github/workflows/bindings-rust.yml
In this PR, `Rust-1.65` is removed from this workflow as this version of Rust does not support `sym in asm` as a stable feature. This issue blocks PR #2306.
> [CI] update bindings-rust workflow

- bindings/rust/wasmedge-sdk/README.md
- bindings/rust/wasmedge-sdk/examples/async_hello_world.rs
- bindings/rust/wasmedge-sdk/examples/async_run_func.rs
- bindings/rust/wasmedge-sdk/examples/create_host_func_in_host_func.rs
- bindings/rust/wasmedge-sdk/examples/hello_world.rs
- bindings/rust/wasmedge-sdk/examples/host_func_with_custom_error.rs
- bindings/rust/wasmedge-sdk/examples/hostfunc_call_chain.rs
- bindings/rust/wasmedge-sdk/examples/run_func_in_aot_mode.rs
- bindings/rust/wasmedge-sdk/examples/vm.rs
- bindings/rust/wasmedge-sdk/examples/wasi_print_env.rs
- bindings/rust/wasmedge-sdk/src/compiler.rs
- bindings/rust/wasmedge-sdk/src/config.rs
- bindings/rust/wasmedge-sdk/src/import.rs
- bindings/rust/wasmedge-sdk/src/lib.rs
- bindings/rust/wasmedge-sdk/src/vm.rs
- bindings/rust/wasmedge-sys/Cargo.toml
In this PR `VmBuilder` is introduced in `wasmedge-sdk` and used to create `Vm` instances with different settings. In addition, PR #2306 failed DCO, therefore, the `wasmtime-fiber` dependency in `Cargo.toml` of `wasmedge-sys` bumps to `6.0.0` in this PR.
> [Rust] Implement VmBuilder

- docs/book/en/src/contribute/build_from_src/macos.md
According to https://docs.brew.sh/Installation, `/usr/local` for macOS Intel, `/opt/homebrew` for Apple Silicon, so use `brew --prefix` to unify them.
> [Docs] update LLVM_DIR for macOS

- .github/workflows/ignore_words
This pull request fixes the linting issue appeared in `docs/book/en/src/write_wasm/js/ssr.md:293`, where codespell regards the truncated HTML `cript>` as a spelling error.
> [CI] Add `cript` to ignore_words to pass the CI

- bindings/rust/wasmedge-sdk/src/executor.rs
- bindings/rust/wasmedge-sdk/src/import.rs
- bindings/rust/wasmedge-sdk/src/store.rs
- bindings/rust/wasmedge-sdk/src/vm.rs
- bindings/rust/wasmedge-sdk/src/wasi.rs
- bindings/rust/wasmedge-sys/src/executor.rs
- bindings/rust/wasmedge-sys/src/frame.rs
- bindings/rust/wasmedge-sys/src/store.rs
In this PR, the `Clone` trait is derived for `Vm`, `Store`, and `Executor` in `wasmedge-sdk`.
> [Rust] Derive Clone trait for Vm

- docs/book/en/src/SUMMARY.md
- docs/book/en/src/write_wasm/c/quickstart.md
This pull request added "quickstart page" or "getting started page" for compiling c program to wasm and then running it on wasmedge runtime.
> [docs] Adding quickstart page for wasm in c

- .github/workflows/bindings-rust.yml
- .github/workflows/rust-static-lib.yml
- bindings/rust/wasmedge-sys/src/instance/function.rs
- bindings/rust/wasmedge-sys/src/lib.rs
In this PR, the host function design is improved to support removing host functions from the lazy static `HOST_FUNCS`.
> [Rust] Optimize host function

- .github/workflows/test-python-install-script.yml
- utils/install.py
GitHub Issue Reference: https://github.com/WasmEdge/WasmEdge/issues/2397
From WasmEdge 0.11.1, we have the Ubuntu release.
For the WasmEdge-tensorflow and WasmEdge-image, they have updated the ubuntu releases.
This commit installs the same DIST of the extensions and WasmEdge, such as the plugins (the policy described in the comment of #2196).
For the WasmEdge-tensorflow-tools, we do not apply this because the tools are the stand-alone executables.
The extension with Ubuntu releases can be test: 0.11.1, 0.11.2, and 0.12.0-alpha.2
> [Utils] Install Script: Support Ubuntu packages for versions above 0.11.1

- plugins/wasmedge_httpsreq/httpsreqfunc.cpp
This PR addresses the issue described in openssl/openssl#7147 that led to SSL connection errors when the hostname verification check was lacked.
The issue was identified and fixed in the WasmEdge HTTPS request client plugin by adding support for TLS extension with a hostname for remote hostname verification. This improvement enhances the security of communication in the client connection and avoids any potential SSL connection errors.
There is a repository contains test case: https://github.com/jetjinser/https-test
I tested this functionality internally and verified that it resolves the issue reported in OpenSSL. Please review and consider merging this pull request.
Thank you.
> [Plugin] Add hostname verification in HTTPS request plugin to fix SSL connection errors

- .CurrentChangelog.md
- Changelog.md
- include/host/wasi/environ.h
- include/host/wasi/inode.h
- include/host/wasi/vinode.h
- include/host/wasi/wasifunc.h
- lib/executor/instantiate/import.cpp
- lib/host/wasi/inode-linux.cpp
- lib/host/wasi/inode-macos.cpp
- lib/host/wasi/inode-win.cpp
- lib/host/wasi/vinode.cpp
- lib/host/wasi/wasifunc.cpp
- lib/host/wasi/wasimodule.cpp
- test/host/socket/wasi_socket.cpp
- test/host/wasi/wasi.cpp
To make our previous WASI socket functions can be compatible with the WASI spec one and the new WasmEdge WASI socket functions, we use a whitelist mechanism to filter those functions that have the same name but with different function signatures. However, this may increase the maintenance cost, so we are going to deprecate it in a future version.
Please notice that this is a workaround, and this behavior is not allowed by the Wasm spec. This is a final PR before the 0.12 release. So we should make sure that CI is grean and everything is compatible when enabling this feature.
> [WASI Socket][Don't merge until the discussion is finalized] Provide multiple WASI socket API implementation

- .CurrentChangelog.md
- Changelog.md
- docs/book/en/src/sdk/c/ref.md
- docs/book/en/src/sdk/go/ref.md
Hi @q82419 
Once you merge this PR, please add a tag for the 0.12 release.
> [Docs] Remove alpha.2 postfix and unreleased tag

- docs/book/en/src/sdk/c/hostfunction.md
This was broken because it passed in the data in the function pointer parameter and passed in `NULL` for the data parameter.
> Fix HostFunction with data example

- lib/host/wasi/environ.cpp
The user code in c:
```c
#include <stdio.h>
#include <assert.h>
int main() {
const char *fname = "./1.c";
FILE *read = fopen(fname, "r");
assert(read != NULL);
fclose(read);
printf("Read pass\n");
FILE *write = fopen(fname, "w");
assert(write != NULL);
fclose(write);
printf("Write pass\n");
return 0;
}
```
Compile to wasm and run with WasmEdge (0.12.0 release):
```console
$ /opt/wasi-sdk/bin/clang ./1.c    
$ WasmEdge-0.12.0-Linux/bin/wasmedge --dir .:. ./a.out
Read pass
Assertion failed: write != NULL (./1.c: main: 13)
[2023-05-01 20:32:33.227] [error] execution failed: unreachable, Code: 0x89
[2023-05-01 20:32:33.227] [error]     In instruction: unreachable (0x00) , Bytecode offset: 0x00000555
[2023-05-01 20:32:33.227] [error]     When executing function name: "_start"
```
I saw the …
> [BUG] fix rights of pre-open fd cannot write and fix readonly flag parse.

- include/validator/formchecker.h
- lib/validator/formchecker.cpp
In https://github.com/WasmEdge/WasmEdge/pull/2097, we turn `VType` in validator into `Optional<ValType>`, and use `None` as the original `VType::Unknown`, which was used as unreachable type. After further examine the code the validator, most usage of `VType` make no difference to using `ValType`. In this PR, we further reduce the usage of `VType`. Currently, the `VType` is only stored in the `ValStack` of `FormChecker`. All other usages have been turned into `ValType`.
This PR is after https://github.com/WasmEdge/WasmEdge/pull/2099.
> refactor: reduce the use of VType in validator

- .github/workflows/bindings-rust.yml
- .github/workflows/rust-standalone.yml
- .github/workflows/rust-static-lib.yml
- .rustfmt.toml
- bindings/rust/wasmedge-sys/Cargo.toml
- bindings/rust/wasmedge-sys/src/async.rs
- bindings/rust/wasmedge-sys/src/plugin.rs
In this PR, the following major changes are involved:
- Replaced `wasmtime-fiber` with `fiber-for-wasmedge`.
- Updated `bindings-rust` workflow to use `rust-1.68/1.69`.
- Updated `rust-static-lib` workflow to use `rust-1.68/1.69`.
- Updated `rust-standalone` workflow to use `rust-1.68/1.69`
> [Rust] Introduce `fiber-for-wasmedge`

- thirdparty/wasi/api.hpp
Workaround: Temporarily reducing the size of the address family to avoid the ABI compatible issue with the old wasmedge wasi socket function.
We will use another wrapper to support larger socket address types to make it ABI-compatible.
Fixes #2440 
cc @LFsWang
> [WASI Socket] Workaround: reduce the address family size for the old API

- .github/workflows/rust-wasmedge-sys-release.yml
In this PR, an issue in the `wasmedge-sys` release workflow has been fixed.
> [CI] Update wasmedge-sys release workflow

- .github/workflows/test-install-script.yml
- utils/install.py
- utils/installer_changes.sh
- The TensorFlow extensions on macOS only support x86_64. So the error message should be only working on x86_64 macOS platforms.
- Fix https://github.com/WasmEdge/WasmEdge/issues/2477
> [Utils] Installer: Fix error message

- include/host/wasi/environ.h
- include/host/wasi/inode.h
- include/host/wasi/vinode.h
- include/host/wasi/wasifunc.h
- lib/host/wasi/environ.cpp
- lib/host/wasi/inode-linux.cpp
- lib/host/wasi/inode-macos.cpp
- lib/host/wasi/inode-win.cpp
- lib/host/wasi/wasifunc.cpp
- lib/host/wasi/wasimodule.cpp
- test/host/wasi/wasi.cpp
* Remove duplicate code on poll_oneoff with edge-trigger config
* Refactor Poller interface for reusing same object
* Use a pool for reusing Poller
* Lazy removing events on reused Poller
* Reuse timerfd
* Add `PollerContext` for holding `Timer` pool in `Environ`
* Support absolute time flags for `poll_oneoff` in MacOS
* Turn on Edge-trigger test in MacOS
* Extract `sleep_for` in test
> Refactor Poller interface for reusing same object

- docs/book/en/book.toml
- docs/book/en/src/SUMMARY.md
- docs/book/en/src/contribute/build_from_src.md
- docs/book/en/src/contribute/build_from_src/riscv64.md
- docs/book/en/src/quick_start/install.md
- docs/book/en/src/quick_start/run_cli.md
- docs/book/en/src/quick_start/run_in_aot_mode.md
- docs/book/en/src/quick_start/use_docker.md
- docs/book/en/src/sdk/go/tensorflow.md
- docs/book/en/src/use_cases/frameworks/app/yomo.md
- docs/book/en/src/write_wasm/c/simd.md
- docs/book/en/src/write_wasm/go.md
- docs/book/en/src/write_wasm/js/quickstart.md
- docs/book/en/src/write_wasm/python.md
- docs/book/en/src/write_wasm/rust.md
- docs/book/en/src/write_wasm/rust/tensorflow.md
- docs/book/en/src/write_wasm/rust/wasinn.md
1. Since we reserve `wasmedgec` tool at this time, I did not remove `wasmedgec` in the installation documents. Besides, I added notes to remind user that `wasmedgec` is equal to `wasmedge compile` and we decide to deprecate `wasmedgec` in the future.
2. Since `wasmedgec` is equal to `wasmedge compile`, I replace `wasmedgec` to `wasmedge compile` in user guides and examples.
> [Docs] Update documents for unified tool

- include/runtime/instance/memory.h
- lib/api/wasmedge.cpp
- lib/host/wasi/wasifunc.cpp
- plugins/wasi_crypto/asymmetric_common/func.cpp
- plugins/wasi_crypto/common/func.cpp
- plugins/wasi_crypto/kx/func.cpp
- plugins/wasi_crypto/signatures/func.cpp
- plugins/wasi_crypto/symmetric/func.cpp
- plugins/wasi_crypto/utils/hostfunction.h
- plugins/wasi_nn/wasinnfunc.cpp
- plugins/wasm_bpf/func-bpf-buffer-poll.cpp
- plugins/wasm_bpf/func-bpf-buffer-poll.h
- plugins/wasm_bpf/func-bpf-map-operate.cpp
- plugins/wasm_bpf/func-load-bpf-object.cpp
- plugins/wasm_bpf/util.cpp
- plugins/wasmedge_process/processfunc.cpp
- test/host/socket/wasi_socket.cpp
- test/host/wasi/wasi.cpp
- test/plugins/wasi_nn/wasi_nn.cpp
* Add `getSpan` `getStringView` method in `MemoryInstance`
* Remove `getPointer` with length argument.
* Change all relative calls to `getPointer` to `getSpan` or `getStringView`
* Change WASI `path_symlink` error reporting behaviors on invalid string pointers
> [WASI] Use StaticVector to speedup CI in debug version

- docs/book/en/src/contribute/build_from_src/plugin_wasmedge_process.md
This is a small fix of Wasmedge-Process document.
1. Turn `WasmEdge-HttpsReq` => `Wasmedge-Process`.
2. Correct the grammar mistakes by using Grammarly.
> Fix Wasmedge-Process documents grammar/instruction

- lib/host/wasi/vinode.cpp
This PR grants socket FDs the right to `fd_read` and `fd_write`.
Previously you could only call `sock_recv` and `sock_send`.
This matches POSIX where you can `read(2)` and `write(2)` on a socket FD, as well as `recv(2)` and `send(2)`.
For context, [Golang](https://go.dev) will soon be able to natively build WASM/WASI applications via `GOOS=wasip1 GOARCH=wasm go build -o module.wasm ...`. See https://tip.golang.org/doc/go1.21#wasip1. Internally, Go uses `fd_read` and `fd_write` regardless of whether it's a file or socket. For compatibility, WasmEdge needs these additional rights for socket FDs.
This fixes #659 (see [this comment](https://github.com/WasmEdge/WasmEdge/issues/659#issuecomment-974877813)).
> Grant socket FDs the ability to fd_read and fd_write

- .github/workflows/IWYU_scan.yml
- .github/workflows/bindings-java.yml
- .github/workflows/build-extensions.yml
- .github/workflows/build_for_openwrt.yml
- .github/workflows/build_for_riscv.yml
- .github/workflows/release.yml
- .github/workflows/reusable-build-on-fedora.yml
- .github/workflows/reusable-build-on-macos.yml
- .github/workflows/static-code-analysis.yml
- .github/workflows/wasi-testsuite.yml
- CMakeLists.txt
- docs/book/en/src/sdk/node.md
- docs/book/zh-TW/src/extend/build.md
- docs/book/zh/src/embed/node.md
- docs/book/zh/src/extend/build.md
- docs/book/zh/src/extend/build_on_mac.md
- flake.nix
- fossa-deps.yml
- lib/driver/fuzzPO.cpp
- lib/host/wasi/CMakeLists.txt
- lib/loader/CMakeLists.txt
- lib/system/CMakeLists.txt
- test/api/CMakeLists.txt
- utils/docker/Dockerfile.base
- utils/docker/Dockerfile.ubuntu2004_x86_64
- utils/docker/Dockerfile.ubuntu2104_armv7l
- utils/docker/build-manylinux.sh
- utils/ohos/build_for_ohos.sh
- utils/ohos/configuration/BUILD.gn
- utils/ohos/configuration/CMakeLists.txt
Since we removed all of the boost related part, we can also drop the boost dependency.
Fixes #2258
> [Misc] use std::boyer_moore_horspool_searcher instead of boost one

- .github/workflows/reusable-build-on-macos.yml
- .github/workflows/reusable-build-on-ubuntu.yml
- test/host/socket/wasi_socket.cpp
This PR fixes potential errors of sockets on macOS.
`sizeof(sockaddr_in) - sizeof(sockaddr_in::sin_family);` on Linux is 14 but on macOS it's 15.
That's because sin_family on Linux is unsigned long, but __uint8_t on macOS.
Adding a condition to handle this on both platforms.
> [Test] Fix socket test on macos.

- lib/system/allocator.cpp
> [Misc] Only define some 64 bits related constants on the corresponding platforms

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/reusable-build-on-android.yml
- .github/workflows/reusable-build-on-fedora.yml
- .github/workflows/reusable-build-on-macos.yml
- .github/workflows/reusable-build-on-manylinux.yml
- .github/workflows/reusable-build-on-ubuntu.yml
- .github/workflows/reusable-build-on-windows.yml
- .github/workflows/reusable-create-source-tarball.yml
`actions/create-release` and `actions/upload-release-asset` are deprecated workflow actions. Since GitHub no longer maintains them, some existing issues will never be fixed in the future.
To resolve this problem, we decide to use `gh`, the GitHub CLI tool, instead.
> Replace the broken release workflow

- .github/workflows/build.yml
- .github/workflows/release.yml
> [CI] Use arm64 arch name on macOS instead of aarch64

- examples/capi/mandelbrot-set-in-threads/Makefile
- examples/wasm/README.md
Replace "wasmedgec" invocations with "wasmedge compile" per the recent WasmEdge tool unification.
> [Examples] Replace wasmedgec with wasmedge compile

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/reusable-build-on-debian-static.yml
- utils/docker/Dockerfile.debian-static
- utils/docker/docker-bake.debian-static.hcl
This PR cross-compiles the `libwasmedge.a` static library for Linux `x86_64` and `aarch64`.
This generates two artifacts in the release:
* `WasmEdge-0.13.1-debian11_x86_64_static.tar.gz`
* `WasmEdge-0.13.1-debian11_aarch64_static.tar.gz`
> [CI] Build static library in github actions

- include/host/wasi/environ.h
- include/host/wasi/inode.h
- include/host/wasi/vinode.h
- lib/host/wasi/inode-linux.cpp
- lib/host/wasi/inode-macos.cpp
- lib/host/wasi/inode-win.cpp
- lib/host/wasi/wasifunc.cpp
Fix this CI error. https://github.com/WasmEdge/wasmedge_hyper_demo/actions/runs/5511875753/jobs/10047996074
This PR remove the unused file descriptor from FdDatas when the socket is closed.
> [WASI] Fix blocking when multiple requests have the same fds.

- CMakeLists.txt
- cmake/Helper.cmake
We build our libraries from source and libtinfo doesn't seem to be
required and isn't built in when we build zlib.
Add a cmake flag to disable needing that library
> Add a flag to disable libtinfo

- lib/aot/compiler.cpp
LLVM vector shift operator (e.g., [ashr](https://llvm.org/docs/LangRef.html#ashr-instruction)) requires two operands of the same type. Use a `splat` instruction to convert the shift count to vector type.
The tests that cover this is passed because of the alternate implementation using SSE on x64_64. These implementations come before the fallback impl but guarded by feature checking (check for SSE on x64_64, NEON on aarch64). The problem is confirmed by removing other implementations (two `ifdef` parts in the same function) and rerun the tests.
After applying this fix, these tests are passed (still keep other impl removed). (Under Linux in docker image wasmedge/wasmedge:latest)
> [AOT] Fix fallback impl of `compileVectorExtAddPairwise`.

- plugins/wasi_nn/torch.cpp
Correct fallback error message after adding support for tuple-type output tensors in PyTorch for Wasi-NN
> [WASI-NN] PyTorch Backend - Fallback Error Message Correction for Tuple type Output Tensors

- plugins/wasi_nn/ggml.cpp
- test/plugins/wasi_nn/CMakeLists.txt
- test/plugins/wasi_nn/wasi_nn.cpp
- utils/wasi-nn/download-ggml-fixtures.sh
- Add tests for wasi-nn GGML backend
- Use 1.8GB model `orca-mini-3b.ggmlv3.q4_0.bin` for testing to reduce memory usage on CI
> [Test] add tests for wasi-nn ggml backend

- .github/workflows/build-extensions.yml
- .github/workflows/release.yml
Due to the apt repository not working, we plan to disable the OpenVINO target on the CI workflow to prevent failing the releasing and testing process. We will re-enable it once the issue is resolved.
> [WASI-NN] Disable OpenVINO target temporary due to the failure of installation issue

- .github/workflows/build-extensions.yml
- .github/workflows/release.yml
- utils/wasi-nn/install-openvino.sh
Re-enable WASI-NN OpenVINO target, which is disabled by https://github.com/WasmEdge/WasmEdge/pull/2933
> [WASI-NN] Enable OpenVINO target again

- README.md
Added a reference link for the ROADMAP.md to the WasmEdge's README file.The URL of the roadmap file is(https://github.com/WasmEdge/WasmEdge/blob/master/docs/ROADMAP.md).
#2971
> Added a reference link for the ROADMAP.md to the WasmEdge's README file

- utils/install.py
Fixes https://github.com/WasmEdge/WasmEdge/issues/2990
> [Utils] Installer: Double quote the strings to prevent splitting in env file

- lib/aot/compiler.cpp
- lib/aot/llvm.h
* Add invariant.group attribute for global pointers and memory pointers
* fix #2963
> [AOT] Add invariant attribute for memory and global pointer

- cmake/Helper.cmake
- lib/aot/compiler.cpp
- lib/aot/llvm.h
* Use pipeline description string for llvm 13 and above.
* Add definition for LLD 17
* Suppress gcc 13.1 warning in spdlog/fmt
- See https://github.com/fmtlib/fmt/issues/3415
> [AOT] Add support for LLVM 17

- .github/workflows/release.yml
- .github/workflows/reusable-build-on-windows-msvc.yml
1. Fix the wrong Windows MSVC path names.
2. Add missing `-y` flag when installing packages with `apt install`
> [CI] Fix release workflows

- .github/ISSUE_TEMPLATE/bug_report.yml
This will prevent adding the code block on users' input.
> [Misc] Remove render:bash from the bug report template

- include/host/wasi/environ.h
- include/host/wasi/vinode.h
- lib/host/wasi/vinode.cpp
- lib/host/wasi/wasifunc.cpp
* Check `filestat_set_times` for invalid flags
* Check `fd_prestat_dir_name` buffer size
* Fix `path_open` for removing path relative rights on file
* Fix `path_open` for checking `O_TRUNC` rights
* Fix `path_readlink` to not following symbolic link
* Fix `path_unlink_file` for trailing slash path
* unix `rmdir` didn't support "." path
> Fix failures on wasi testsuite

- .github/workflows/IWYU_scan.yml
- plugins/wasi_nn/ggml.cpp
- plugins/wasi_nn/ggml.h
- plugins/wasi_nn/wasinnenv.h
- plugins/wasi_nn/wasinnfunc.cpp
- plugins/wasi_nn/wasinnfunc.h
- plugins/wasi_nn/wasinnmodule.cpp
- test/plugins/wasi_nn/wasi_nn.cpp
- When the graph builder length > 1, the data of builder[1] is the metadata.
- The metadata is a json string as before.
- Still support set metadata from set_input with index 1 for backward compatibility.
- Also support pass model parameter from cli (only support `n-gpu-layers` currently). For example: `--nn-preload default:GGML:AUTO:llama-2-7b-chat.Q5_K_M.gguf,ngl=99`.
- Move parameters to `struct Graph` and move `LlamaContext` to `struct Context`.
> [WASI-NN] ggml: support load_by_name_with_config

- plugins/wasi_nn/ggml.cpp
- plugins/wasi_nn/ggml.h
- plugins/wasi_nn/types.h
- plugins/wasi_nn/wasinnfunc.cpp
- plugins/wasi_nn/wasinnfunc.h
- plugins/wasi_nn/wasinnmodule.cpp
This pull request is for adding the function of single token inference. To implement this function, we need to make modifications to 3 different repositories:
1. wasmedge-wasi-nn: Add two host functions `compute_single` and `get_output_single`
- PR: https://github.com/second-state/wasmedge-wasi-nn/pull/3
2. WasmEdge: Implement the two WASI-NN functions `compute_single` and `get_output_single`
- PR: https://github.com/WasmEdge/WasmEdge/pull/3103
3. WasmEdge-WASINN-examples: Add examples for single token inference
- PR: https://github.com/second-state/WasmEdge-WASINN-examples/pull/75
> [WASI-NN] Add single token inference

- lib/host/wasi/linux.h
This commit fixes a bug in `toTimespec`.  The duration overflows with a large timestamp because `std::chrono::nanoseconds` is signed 64-bit integer.  Instead, we should explicitly use `uint64_t` because `__wasi_timestamp_t` is unsigned 64-bit.
fixes #3105
> Fix large timestamp causing overflow

- plugins/wasi_nn/CMakeLists.txt
- plugins/wasi_nn/ggml.cpp
- test/plugins/wasi_nn/wasi_nn.cpp
- In order to get the same build number as llama.cpp, we need to set `GIT_SHALLOW` to `FALSE` when fetching llama.cpp.
- Update ggml to b1698.
> [WASI-NN] ggml: show llama commit and build number in log

- include/plugin/plugin.h
- lib/driver/uniTool.cpp
The plugin versions can be now shown via the `wasmedge --version` CLI.
e.g.,
```console
$ /tmp/wasmedge/bin/wasmedge --version
/tmp/wasmedge/bin/wasmedge version 0.13.5-XX-gXXXXXXXX
/private/tmp/wasmedge/lib/../plugin/libwasmedgePluginWasiNN.dylib (plugin "wasi_nn") version 0.10.1.0
```
> [Tools] --version: add plugin versions

- lib/executor/engine/proxy.cpp
The `ProxyHelper::proxy` function may directly return `RefVariant`. Directly returning a C++ struct makes the ABI unstable. Fixed https://github.com/WasmEdge/WasmEdge/issues/3113
> [CI] Fix incorrect ABI in MSVC build (#3113)

- plugins/wasi_nn/ggml.cpp
- plugins/wasi_nn/ggml.h
- plugins/wasmedge_image/CMakeLists.txt
- Close #3133 
- Close #3134
- [WASI-NN] ggml: improved logging mechanism for ContextFull and PromptTooLong
- Use `spdlog::info()` instead of `spdlog::error`
- Only print log when `enable-log` flag is on
> [WASI-NN] ggml: print llama timing in fini_single

- plugins/wasi_nn/ggml.cpp
- Show llama.cpp version in metadata.
- Related PR: https://github.com/second-state/WasmEdge-WASINN-examples/pull/83
> [WASI-NN] ggml: return version in metadata

- .github/workflows/build-extensions.yml
- .github/workflows/release.yml
- plugins/wasi_nn/openvino.cpp
- plugins/wasi_nn/openvino.h
- test/plugins/wasi_nn/wasi_nn.cpp
- utils/wasi-nn/install-openvino.sh
Some points of my confusion during the work integration to 2.0 API. 
I noticed that the shape of the input tensor passed from WebAssembly (wasm) is NHWC, but the tensor dimensions in the parameters are given as [1, 3, 224, 224], leading to parsing errors. 
Currently, I manually hardcode {1, 224, 224, 3} in `openvino.cpp` to bypass this issue. 
@apepkuss , could you please take a look at the original example and check if the processing of image to tensor is handled correctly? Or if there's any misunderstanding on my part, please help correct me. Thanks!
Fix #3140
> Upgrade openvino 2.0

- include/loader/shared_library.h
- include/system/fault.h
- lib/aot/compiler.cpp
- lib/aot/llvm.h
- lib/executor/engine/proxy.cpp
- lib/executor/helper.cpp
- lib/loader/shared_library.cpp
- lib/system/fault.cpp
* Use hidden function `__register_frame` and `__deregister_frame` in libgcc and libunwind to apply FDE data in `.eh_frame` section
> [AOT] Support exception handling, stack unwinding across AOT binary

- plugins/wasi_nn/CMakeLists.txt
- test/spec/CMakeLists.txt
Fix #2791 
The issue was due to simdjson being exported with a namespace, which led to `find_package` successfully locating simdjson but failing to link the library without specifying the namespace. Prefixing simdjson with its namespace in `target_link_libraries` resolves this linking issue.
> Fix the linking error with simdjson

- plugins/wasi_nn/CMakeLists.txt
- plugins/wasi_nn/ggml.cpp
- plugins/wasi_nn/ggml.h
- thirdparty/ggml/ggml.patch
- Add `mmproj` and `image` options.
- Refactor inference code, separate evaluation and prediction.
- Related example PR https://github.com/second-state/WasmEdge-WASINN-examples/pull/97
> [WASI-NN] ggml: add llava support

- utils/install.py
Fix #3232 and #3234 
I've removed the `._` files after extraction to prevent them from being copied into the destination and getting written into the `env` file.
> [Installer] Remove macOS metadata during installation

- plugins/wasi_nn/CMakeLists.txt
- plugins/wasi_nn/ggml.cpp
- thirdparty/ggml/ggml.patch
* [WASI-NN] ggml: remove special ngl default value for macOS
* [WASI-NN] ggml: bump llama.cpp b2294
* [WASI-NN] ggml: add inline base64 prompt support for llava
> [WASI-NN] ggml: add inline base64 prompt support for llava 

- lib/host/wasi/inode-linux.cpp
There are two same name functions 'fromFileType' in /lib/host/wasi/linux.h . This PR fixes #1889 error by explicitly specifying the type of the argument when calling the fromFileType from lib/host/wasi/inode-linux.cpp.
> Fixing inode_linux.cpp fromFileType error

- lib/host/wasi/vinode.cpp
This patch attempt to fix #3231.
The resolvePath function uses fstatat for path resolution, which will return error when the relative path (foo) is not exist.
> [WASI] fix special case in vinode path resolving

- README.md
remove typo charctor '=' in readme file, English version, this typo error only exists in English version Readmefile
> remove typo charctor '=' in readme file

- plugins/wasi_nn/ggml.cpp
Fix the results of metadata about the number of input tokens when doing llava inference.
> [WASI-NN] ggml: set LlamaNInputs correctly when llava inference

- .github/workflows/test-python-install-script.yml
- utils/install.py
This PR allows users to install the specific build number version of the ggml plugin.
This is a workaround because the AI/LLM is moving too fast. Applying this patch will bypass two checks, including PLUGINS_AVAILABLE and SUPPORTTED_PLUGINS when the plugin name starts with `wasi_nn-ggml`.
Usage:
```
install.py --plugin wasi_nn-ggml-bxxxx
```
> [Installer] Allow users to install the specific build number of the ggml plugin

- plugins/wasi_nn/CMakeLists.txt
We could remove the ggml-metal.metal file after upgrading to the latest version of llama.cpp.
> [WASI-NN] ggml: use new metal file

- include/driver/wasi_nn_rpc/wasi_nn_rpcserver/wasi_nn_rpcserver.h
- lib/wasi_nn_rpc/wasi_ephemeral_nn.proto
- plugins/wasi_nn/wasinnfunc.cpp
- test/plugins/wasi_nn/wasi_nn.cpp
In this PR, I implement the `LoadByNameWithConfig` function in the `wasi_nn_rpcserver` tool and add the corresponding tests.
> [WASI-NN] rpc: implement `load_by_name_with_config`

- plugins/wasi_nn/CMakeLists.txt
- plugins/wasi_nn/ggml.cpp
- Update llama.cpp to the latest version.
- Fix the embedding generation to ensure that our result matches the output from [llama.cpp/examples/embedding](https://github.com/ggerganov/llama.cpp/tree/master/examples/embedding).
> [WASI-NN] ggml: bump llama.cpp b2479 and fix embeddings

- plugins/wasi_nn/CMakeLists.txt
- thirdparty/ggml/ggml.patch
- Set `LLAMA_METAL_EMBED_LIBRARY=ON` to embed the Metal library, which will prevent the generation of the `default.metallib` file.
- The `LLAMA_CUBLAS` option is deprecated; use `LLAMA_CUDA` instead.
> [WASI-NN] ggml: fix metal build & bump llama.cpp to b2534

- utils/install_v2.sh
Due to the rustls being optional, users can install it using an explicit option.
> [Installer] v2: disable rustls by default. Enable it via --rustls option

- plugins/wasi_nn/ggml.cpp
- plugins/wasi_nn/ggml.h
- Support `grammar` for #3314
- Example PR https://github.com/second-state/WasmEdge-WASINN-examples/pull/126
> [WASI-NN] ggml: support grammar

- plugins/wasi_nn/CMakeLists.txt
- This version of llama.cpp adds the support of command r plus model.
> [WASI-NN] ggml: update ggml to b2636

- plugins/wasi_nn/ggml.cpp
- Fix the computeSingle error: https://github.com/second-state/WasmEdge-WASINN-examples/actions/runs/8685945654/job/23816444215
- Only check the input size when the context is not initialized. The input will be moved after init.
> [WASI-NN] ggml: fix input size checking of computeSingle

- include/executor/executor.h
- lib/executor/executor.cpp
- lib/executor/helper.cpp
Fixes this issue: https://github.com/WasmEdge/wasmedge-rust-sdk/issues/101
> [Executor] Clean unused bits of values when passing in/out invokation

- plugins/wasi_nn/ggml.cpp
- plugins/wasi_nn/ggml.h
- Suport `ubatch-size`
- Ref: https://github.com/ggerganov/llama.cpp/pull/6017
- Use `add_special` instead of `add_bos`
- Ref: https://github.com/ggerganov/llama.cpp/pull/6498
- Check the batch size instead of the context size when generating embeddings
- Ref: https://github.com/ggerganov/llama.cpp/blob/1b67731e184e27a465b8c5476061294a4af668ea/examples/embedding/embedding.cpp#L119
> [WASI-NN] ggml: support ubatch-size

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/reusable-build-on-manylinux.yml
This PR only adds build & release on x86_64, aarch64 will be added after the docker image `manylinux_2_28_aarch64` is fixed; plugins will be added after the docker images `*-plugin-deps` are fixed.
> [CI] Add manylinux_2_28 (x86_64) to workflows

- .github/workflows/docker.yml
- utils/docker/Dockerfile.ci-image-base
- utils/docker/docker-bake.ci-image-base
0. Add `:ci-image-base_aarch64`
0. Add CI workflows to build `:manylinux_2_28_aarch64*` images
NOTE: Please prevent from hitting the "Update branch" button unless necessary, since it would take hours for the CI checks to finish.
> [CI] Build aarch64 images

- .github/actions/expand-variables/dist/index.js
- .github/actions/expand-variables/main.js
- .github/workflows/reusable-build-extensions-on-manylinux.yml
- plugins/wasi_crypto/utils/handles_manager.h
Fix build errors and add to CI workflows.
> [CI] Build plugins on manylinux_2_28 aarch64

- plugins/wasi_nn/ggml.cpp
- plugins/wasi_nn/ggml.h
This pull request integrates simple support on mmap by adding the parameter to `Graph`, `load()`, `parseMetadata()` of GGML plugin.
`UseMMap` is set to true by default, and will be set to false if `--no-mmap` is presented to the program calling `wasi-nn` SDK.
In upcoming updates of this PR, I will attach changes made to example of LlamaEdge that support `--no-mmap` since it is only adjustable through parameter passed to the end program.
Is mmap in [lib/system/mmap.cpp](https://github.com/WasmEdge/WasmEdge/blob/master/lib/system/mmap.cpp) more preferred than simply passing into llama.cpp using model parameter?
> enables usage of parameter `--no-mmap` from llama.cpp

- bindings/java/README.md
> Fix java code examples in README

- docs/book/en/src/use_cases/kubernetes/demo/wasi.md
> [Docs] Remove module.wasm.image annotation when building wasm container images

- utils/install_v2.sh
cc @juntao 
According to Vivian's report, the `ldconfig` detection will fail. In this PR, I am going to remove the detection of `libcudart`. Also, the `nvidia-smi` may report the cuda version, but libcudart is not installed, so I removed it either.
> [Installer] v2: Remove nvidia-smi detection

- .github/workflows/reusable-build-on-windows-msvc.yml
- .github/workflows/reusable-build-on-windows.yml
- .github/workflows/wasi-testsuite.yml
* Use prebuilt clang
* Report ctest failure
* Add step name
* Use Invoke-WebRequest from powershell
* Add windows test on wasi-testsuite
> [CI] Remove vswhere for windows-clang building

- .github/workflows/reusable-build-on-fedora.yml
Try to fix the CI build: `Test WasmEdge Core` when building on `fedora:latest` image.
I was able to reproduce it on my machine with `Unpack error: ...` and it should be resolved by adding the `--privileged` option when running the docker container.
> [CI] Try to fix the build on fedora:rawhide with options

- docs/OWNER.md
In this PR, I am pleased to nominate the following four individuals as new committers:
1. csh(@L-jasmine), the previous reviewer, works hard on reviewing the [WasmEdge Rust SDK](https://github.com/WasmEdge/wasmedge-rust-sdk), WasmEdge Rust Plugin SDK, and other rust-related projects.
2. Vivian Hu(@alabulei1), who applies herself to hosting the community meetings and maintaining the [docs repository](https://github.com/WasmEdge/docs).
3. Wang-Yang Li(@LFsWang), who contributed to the WasmEdge WASI socket in 2022, fixes several Windows bugs and implements the relaxed SIMD proposal(#3311).
4. HanWen Tsao(@grorge123), the mentee of our LFX mentorships program, implements the WASI-NN Neural Speed backend(#3303). After finishing his mentorship, he continued contributing to the Stable …
> [Community] nominate new committers

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/reusable-build-extensions-on-manylinux.yml
- .github/workflows/reusable-build-on-manylinux.yml
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
> [CI] Allow node16 on manylinux

- .github/workflows/test-install-script.yml
- .github/workflows/test-python-install-script.yml
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
Note: This PR only fixes `actions/checkout`, CentOS 7 will still fail on `yum`
> [CI] Workaround for (the lack of) node20 on Ubuntu 16 & 18, and CentOS 7

- plugins/wasi_nn/wasinnenv.cpp
Fixes #3533 
As mentioned in issue #3533, this PR aims to fix the model path in the Windows environment.
The cause of this issue lies in the definition of nn-preload in wasi-nn, which allows multiple model paths for the same name, such as `<name>:<backend>:<device>:<model-path-1>:<model-path-2>`. However, in a Windows environment, using `:` as a delimiter will disrupt paths. 
Fortunately, because GGML currently only supports a single model path for the same name, and we will place `Builder[1]` as the location for the config parameter, this pull request modification mainly treats the string after `<name>:<backend>:<device>:` in the nn-preload as the model path for the GGML backend, thereby avoiding cutting off paths in the Windows environment.
> [WASI-NN] ggml: fix model path in nn-preload string on Windows

- lib/common/errinfo.cpp
fmt::join() was moved into fmt/ranges.h, which is in turn included by spdlog/fmt/ranges.h or spdlog/fmt/bundled/ranges.h, so let's include either of them.
this should address the build failure like:
```
/builddir/build/BUILD/wasmedge-0.14.0-build/wasmedge/lib/common/errinfo.cpp: In member function fmt::v11::context::iterator fmt::v11::formatter<WasmEdge::ErrInfo::InfoMismatch>::format(const WasmEdge::ErrInfo::InfoMismatch&, fmt::v11::format_context&) const:
/builddir/build/BUILD/wasmedge-0.14.0-build/wasmedge/lib/common/errinfo.cpp:165:25: error: join is not a member of fmt
165 |                    fmt::join(Info.ExpParams, " , "sv),
|                         ^~~~
```
> [Common] include spdlog/fmt/ranges.h for fmt::join()

- .github/workflows/matrix-extensions.json
This PR includes those marked with `o` in the table.
| | `manylinux2014` | `manylinux_2_28` |
| --- | --- | --- |
| Stable Diffusion | o | o |
| WASI-NN Neural Speed | x | #3574 |
| WASI-NN OpenVINO | x | #3575 |
| WASI-NN Piper | x | #3576 |
| Whisper | o | o |
| zlib | x | o |
Those marked with `x` will not release on `manylinux2014`.
- (zlib) dependency: `zlib` is `1.2.7`
- (piper) dependency: `fatal error: ucd/ucd.h: No such file or directory`
> [CI] Sync build-extensions from Ubuntu to manylinux

- include/runtime/instance/memory.h
- test/memlimit/MemLimitTest.cpp
If the page size limit is set in configuration, and the `min` in memory type is smaller than the limited page size value when creating the memory instance, modify the `min` in memory type and create with the limited size.
> [Runtime] Create limited page size of memory instance if configured.

- utils/install_v2.sh
cc @L-jasmine 
This should prevent the installer v2 from installing a was-logging plugin for the toxin use cases.
We will remove the wasi-logging plugin from all installers after it is migrated into the built-in libwasmedge.
> [Installer] v2: Allow users to disable WASI-Logging via --nowasilogging

- utils/install_v2.sh
This will use the installed nvcc version instead of our previous detection.
> [Installer] v2: Let Jetson platform detect the installed nvcc version

- .github/workflows/release.yml
Adds the Ubuntu 20.04 release CI for WASI-NN Piper.
> [CI] Ubuntu 20.04: WASI-NN Piper

- .github/workflows/release.yml
- .github/workflows/reusable-build-extensions-on-manylinux.yml
- .github/workflows/reusable-build-on-manylinux.yml
- .github/workflows/test-install-script.yml
- .github/workflows/test-python-install-script.yml
* For the installer tests, we replace the mirrors.
* For manylinux2014, we use the pre-installed gh client inside the
docker image instead.
* For non-EOL manylinux, it's fine to use the package manager to install
the gh client.
> [CI] Fix mirrors on manylinux2014(CentOS 7)

- CMakeLists.txt
In #3626, .git detection was introduced to avoid the error triggered by the git describe command. However, the GIT_VERSION_NOT_FOUND variable is defined and set within the git describe command call. After applying #3626, GIT_VERSION_NOT_FOUND will never be defined and set if the git command exists but the .git folder does not.
In this PR, we define and initialize GIT_VERSION_NOT_FOUND to 1. This will ensure that CPACK_PACKAGE_VERSION is set to "0.0.0-unreleased" if `git describe` is not working or the .git folder does not exist.
@q82419 
We need to merge this PR into rc.2.
> [CMake] Fix the .git Detection Issue

- plugins/wasi_nn/CMakeLists.txt
Some related updates between llama.cpp b3499 ~ b3567
```
- metal : fix uninitialized abort_callback (#8968)
- llama : default n_swa for phi-3 (#8931)
- llava : support MiniCPM-V-2.5 (#7599)
- CUDA: fix padding logic for FP16/FP32 (#8884)
- [Vulkan] Fix compilation of `vulkan-shaders-gen` on w64devkit after `e31a4f6` (#8880)
- Stop the generation when <|eom_id|> token is encountered - needed for Llama 3.1 tool call support (#8858)
- cmake: fix paths for vulkan shaders compilation on Windows (#8573)
- vulkan : fix Qantized Mat-Vec Mul on AMD GPUs for ncols < 64 (#8855)
- cuda : fix dmmv cols requirement to 2*GGML_CUDA_DMMV_X (#8800)
```
> [WASI-NN] ggml: bump llama.cpp b3567

- cmake/Helper.cmake
- cmake/WASINNDeps.cmake
- lib/common/CMakeLists.txt
- plugins/wasi_nn/piper.patch
WASI-NN Piper plug-in dependency: Piper also uses spdlog and fmt.
It uses `ExternalProject_Add` to download and install spdlog 1.12.0 and fmt 10.0.0.
It expects spdlog and fmt installations to have a directory containing include and lib directories (does not fit for `FetchContent` so a patch is required).
For includes, Piper uses its installed spdlog and fmt headers.
For linking (libwasmedgePluginWasiNN.so), it chooses to link with spdlog and fmt selected by the top-level project (wasmedge).
Before https://github.com/WasmEdge/WasmEdge/commit/bc1e277db997df63175556f7d90ffe0f0ac1f903, the ABI was the same so  it happened to worked.
https://github.com/WasmEdge/WasmEdge/commit/bc1e277db997df63175556f7d90ffe0f0ac1f903 bumped fmt from 10.2.1 to 11.0.2 and we got this error when running …
> [WASI-NN] piper: make piper dependency use the same fmt and spdlog as the top-level project

- CMakeLists.txt
- plugins/wasmedge_stablediffusion/CMakeLists.txt
- Add option `WASMEDGE_PLUGIN_STABLEDIFFUSION_CUBLAS` to enable `SD_CUBLAS` if required.
> [Plugin] Stable Diffusion: enable CUBLAS

- .github/workflows/build-extensions.yml
- .github/workflows/release.yml
- CMakeLists.txt
- plugins/wasmedge_stablediffusion/CMakeLists.txt
- Add Metal support by `WASMEDGE_PLUGIN_STABLEDIFFUSION_METAL`
- Build and upload plugin with Metal support on CI. Pack with related files (`.metal`, `.h` files).
> [Plugin] stable diffusion: add Metal support

- .github/workflows/release.yml
This is a workaround before we have `wasmedge/wasmedge:ubuntu-*-plugins-deps` built with `ubuntu:20.04`.
> [CI] Fix ubuntu image version

- utils/docker/docker-bake.ubuntu.hcl
As long as we still (mainly) release with `ubuntu:20.04`, I think it's better to keep the docker images up to date.
> [Docker] Add ubuntu 20.04 to bake list

- plugins/wasi_nn/CMakeLists.txt
> [WASI-NN] ggml: bump to b3651

- .github/workflows/docker.yml
This workflow does not have release-related jobs.
> [CI] Docker: remove `on.push.tags`

- .github/workflows/docker.yml
TLDR: `if: always()` cause jobs being non-cancellable. Seems like `if: !failure()` results in the same behavior here.
See https://github.com/actions/runner/issues/1846
> To cancel the workflow run, the server re-evaluates if conditions for all currently running jobs. If the condition evaluates to true, the job will not get canceled. For example, the condition if: always() would evaluate to true and the job continues to run. When there is no condition, that is the equivalent of the condition if: success(), which only runs if the previous step finished successfully.
Docs quoted from: https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/canceling-a-workflow#steps-github-takes-to-cancel-a-workflow-run
Force cancel: …
> [CI] Workaround for jobs not cancellable

- .github/workflows/build-extensions.yml
This PR enables Metal support of stable-diffusion plugin by default on arm64 macOS.
Fixes #3757
> [CI] plugins: enable Metal by default on arm64 macOS

- .github/workflows/docker.yml
- utils/docker/Dockerfile.ubuntu-base
- utils/docker/Dockerfile.ubuntu-gcc
- utils/docker/Dockerfile.ubuntu-plugins-deps
- utils/docker/docker-bake.ubuntu.hcl
Reduce docker-bake time for `docker-bake.ubuntu.hcl` (target: `default`) roughly from 2 hrs to 1 hr.
The main change for the base image `wasmedge/wasmedge:latest` (`wasmedge/wasmedge:ubuntu-build-clang`) is that both `gcc` (`g++`) and `clang` are installed, just the `ENV`s differs from `wasmedge/wasmedge:ubuntu-build-gcc`.
> [Docker] Ubuntu: Refine structure for better caching

- plugins/wasi_nn/ggml.cpp
> [WASI-NN] Fix `fmt::format` error in embedding

- CMakeLists.txt
- examples/embed_cxx/CMakeLists.txt
- utils/docker/Dockerfile.ubuntu-base
Fixes #3787
This PR does:
1. update utils/docker/Dockerfile.ubuntu-base to install latest cmake from Kitware PPA for ubuntu 20.04
2. cmake_minimum_required(VERSION 3.18) for the root project and examples/embed_cxx
reference:
https://github.com/WasmEdge/WasmEdge/pull/3788
> [CMake] bump cmake to 3.18

- .github/workflows/winget-submit.yml
- Resolves https://github.com/WasmEdge/WasmEdge/issues/2673
1. Uses [WinGet Releaser](https://github.com/marketplace/actions/winget-releaser).
2. Will ONLY submit artifacts ending with `windows.msi` (NOT `windows-msvc.msi`), since Microsoft VCRedist is added as a dependency in the [manifest itself](https://github.com/microsoft/winget-pkgs/blob/master/manifests/w/WasmEdge/WasmEdge/0.14.0/WasmEdge.WasmEdge.installer.yaml).
3. Will only run on Stable releases (NOT on Pre-releases)
> use winget-releaser to submit package to winget

- plugins/wasm_bpf/CMakeLists.txt
- test/plugins/wasmedge_zlib/wasmedge_zlib.cpp
- Error caused by https://github.com/libbpf/libbpf/commit/42d77b062c0e483bbc176b2d27f5ced02b19ecb3 (2023-01-26)
- Original tag`cf46d44f0a06aa8b9400691ea3eb86ca4f066d5c` (2023-03-07)
- New tag `950cffc0366981d4e41b08f007b37bd6af931f25` https://github.com/libbpf/libbpf/commit/950cffc0366981d4e41b08f007b37bd6af931f25 (2023-03-16)
> Fix build errors (ubuntu 24.04, clang)

- .github/workflows/bindings-java.yml
- .github/workflows/build-extensions.yml
- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/reusable-build-extensions.yml
- cmake/Helper.cmake
- utils/docker/Dockerfile.ubuntu-base
- utils/docker/docker-bake.ubuntu.hcl
This PR added docker images for ubuntu 24.04:
- `wasmedge/wasmedge:ubuntu-24.04-build-clang`
- `wasmedge/wasmedge:ubuntu-24.04-build-clang-plugins-deps`
- `wasmedge/wasmedge:ubuntu-24.04-build-gcc`
- `wasmedge/wasmedge:ubuntu-24.04-build-gcc-plugins-deps`
Also changed all `latest`-related tags from ubuntu 22.04 to ubuntu 24.04:
- `wasmedge/wasmedge:latest`
- `wasmedge/wasmedge:ubuntu-build-clang`
- `wasmedge/wasmedge:ubuntu-build-clang-plugins-deps`
- `wasmedge/wasmedge:ubuntu-build-gcc`
- `wasmedge/wasmedge:ubuntu-build-gcc-plugins-deps`
Since workflows are not 100% ready for ubuntu 24.04, all jobs previously using `ubuntu-build-*` were changed to use `ubuntu-22.04-build-*`.
> [CI] Prepare to upgrade Ubuntu latest from 22.04 to 24.04

- .github/workflows/IWYU_scan.yml
- cmake/WASINNDeps.cmake
- plugins/wasi_nn/wasinn_ggml.cpp
- test/plugins/wasi_nn/CMakeLists.txt
- Bump llama.cpp to b4034 for tool calling
- Use the new `llama_batch_get_one` API
- The `fedora:latest` is Fedora 41 and `llvm` in upgrade to 19 by default. Use `llvm18` to specify the llvm version.
> [WASI-NN] ggml: bump llama.cpp b4034

- utils/docker/Dockerfile.ubuntu-plugins-deps
- utils/opencvmini/install-opencvmini.sh
This will fix dependency issue of `wasmedge_ffmpeg` on Ubuntu 24.04 docker images.
* Install FFmpeg 6.1 via apt (24.04)
* Install FFmpeg 6.0 to `/usr/local` (20.04, 22.04)
* Install PyTorch to `/usr/local`
* Fix clean-up files for `install-opencvmini.sh`
> [Docker] Update Ubuntu dependencies

- include/system/winapi.h
- lib/host/wasi/inode-win.cpp
`GetOverlappedResult` occasionally succeeds but returns zero inlpNumberOfBytesTransferred`. After switching to
`ReadFile/WriteFile`, this issue no longer occurs.
* Fix #3811
> [WASI] win: Use `ReadFile/WriteFile` instead of `ReadFileEx/WriteFileEx`

- cmake/WASINNDeps.cmake
- plugins/wasi_nn/wasinn_ggml.cpp
- Update llama.cpp to the b4179 release.
- Update the parameter names.
- Add `-fPIC` to ggml related target libraries.
> [WASI-NN] ggml: bump llama.cpp b4179

- CMakeLists.txt
In the future, any changes made to any part of the wasi-nn plugin should also bump `WASMEDGE_WASI_NN_VERSION`.
> [WASI-NN] bump to 0.1.1

- include/loader/loader.h
- lib/loader/ast/component.cpp
This fixed the Windows-MSVC build.
> [Component] fix: sizeof(ComponentSection)=uint64_t, but loadComponent takes uint32_t

- CMakeLists.txt
- plugins/wasi_nn/wasinn_ggml.cpp
- plugins/wasi_nn/wasinn_ggml.h
* [WASI-NN] ggml: disable warmup by default to match previous behavior
* [WASI-NN] ggml: reload llama context if embedding status changed
* [WASI-NN] bump to 0.1.3
After we changed the context initialization at commit https://github.com/WasmEdge/WasmEdge/commit/e80cdcd8d88b1a77960ec062eb9ddcf1212b648f, we should recreate the context when some parameters change (currently, only the ⁠embedding parameter). Additionally, I disabled warm-up by default to match the previous behavior.
> [WASI-NN] Fix gaianet embeddings issue

- lib/api/CMakeLists.txt
Fix undefined symbols related to fmt.
Based on the latest (0.14.1) release, libfmt.a is no longer included. Therefore, the previous method of actively linking libfmt.a at the FFI layer (build.rs) is no longer work.
> [CMake] Link libfmt to the target in the static build

- .github/workflows/reusable-build-on-windows-msvc.yml
- .github/workflows/reusable-build-on-windows.yml
See: https://github.com/actions/runner-images/issues/11174
It's not possible to install a specific version of cmake on the GitHub Windows Image currently.
> [CI] Windows: use the preinstalled cmake as a workaround

- examples/capi/unix_domain_socket/README.md
- examples/plugin/wasi-crypto-signature/README.md
Specifically:  
1. Fixed improper use of articles ("a" vs. "an") in the following locations:  
- **File**: `examples/capi/unix_domain_socket/README.md`  
- Changed "A example" to "An example".  
- Changed "an string" to "a string".  
- **File**: `examples/plugin/wasi-crypto-signature/README.md`  
- Changed "a example" to "an example".  
These changes improve the clarity and grammatical correctness of the documentation.  
Allow edits by maintainers.
> Fix Typographical Errors

- utils/install_v2.sh
Windows detection implemented inside check_os_arch() and removing empty lines
to resolve this issue (https://github.com/WasmEdge/WasmEdge/issues/3920)
Fixes #3920
> Windows detection implemented inside check_os_arch() 

- CMakeLists.txt
- cmake/WASINNDeps.cmake
- plugins/wasi_nn/wasinn_ggml.cpp
- plugins/wasi_nn/wasinn_ggml.h
- Update option types according to llama.cpp
- In llama.cpp, the types of context parameters and common parameters are actually different.
- For instance, `cparams.n_ctx` is `uint32_t` while `params.n_ctx` is `int32_t`.
- This is because some parameters are initially set in common params and are only assigned to context params after evaluation.
- The ggml plugin mainly follows the types of common params.
- Ref:
- https://github.com/ggerganov/llama.cpp/blob/master/common/common.h
- https://github.com/ggerganov/llama.cpp/blob/master/include/llama.h
- Do not append SEP when getting embeddings
- Ref: https://github.com/ggerganov/llama.cpp/blob/7eee341/examples/embedding/embedding.cpp#L147-L154
- Bump llama.cpp version and WASI-NN plugin version
> [WASI-NN] ggml: update options types and embeddings generation

- plugins/wasi_nn/wasinn_ggml.cpp
- plugins/wasi_nn/wasinn_ggml.h
This is the part 3 of mllama implementation in WASI-NN GGML.
(base on #3956)
1. Move the sampler to context level.
2. Fix the batch encoding.
3. Update the metadata and config structure.
4. Merge the redundant codes.
5. Refine the model/sampler reloading in set_input.
> [WASI-NN] GGML: various refactoring (PART 3)

- examples/capi/wasi-env/README.md
- examples/plugin/wasi-crypto-signature/README.md
- examples/plugin/wasi-logging/README.md
- examples/wasm/README.md
Well, Rust changed the wasm triple from wasm32-wasi to wasm32-wasip1 ◡ ヽ(`Д´)ﾉ ┻━┻
That's why we have to change the docs.
> [Docs] Rust 1.84 uses wasm32-wasip1 instead of wasm32-wasi

- .github/workflows/docker.yml
- .github/workflows/reusable-build-on-alpine-static.yml
- .github/workflows/reusable-build-on-debian-static.yml
- According to the new doc of `docker/bake-action`, we don't need to do checkout anymore.
- For alpine-static and debian-static, we need `git describe` to fetch current version.
See #3971
> [CI] Fix failure after upgrading `docker/bake-action`, and remove unused `actions/checkout`

- lib/validator/formchecker.cpp
closed: #3481 
Some atomic instructions were omitted in the previous repair PR.
and I have removed some unused imports.
> Add detection of missing atomic instructions for memory alignment.

- CMakeLists.txt
- cmake/Helper.cmake
- include/host/mock/wasmedge_image_func.h
- include/host/mock/wasmedge_image_module.h
- plugins/wasi_nn/wasinn_whisper.h
- plugins/wasi_nn/wasinnfunc.cpp
- plugins/wasmedge_image/CMakeLists.txt
- plugins/wasmedge_image/image_func.cpp
- plugins/wasmedge_image/image_func.h
- plugins/wasmedge_image/image_module.cpp
- test/host/mock/mockTest.cpp
- test/plugins/wasmedge_image/wasmedge_image.cpp
This PR includes the following commits:
1f3b7b5f [WASI-NN] bump to 0.1.9 (#3983)
d76ae2f9 [WASI-NN] Fix wrong function dispatch. (#3979)
a64a8641 [Plugin] Use `stb_image` to replace the libpng and libjpeg.
> [Plugin] Update 0.14.1_plugin_lts branch

- include/common/int128.h
- lib/llvm/llvm.h
* Ignore c++17 deprecated warning in `<ciso646>` header
* Support fmt v11.1.2
> Support new fedora rawhide

- .github/dependabot.yml
Expected PR should look like
```
[CI] dependabot: bump actions/checkout from 3 to 4
[CI] dependabot: bump the docker group with 2 updates
```
After #3850 merged, we should also update prefix from `[CI] dependabot` to `ci(dependabot)`.
> [CI] Add groups and prefix for dependabot

- CMakeLists.txt
- cmake/WASINNDeps.cmake
- plugins/wasi_nn/wasinn_ggml.cpp
- plugins/wasi_nn/wasinn_ggml.h
- Change `LlamaOutputs` from `string` to `vector<uint8_t>`.
- Save the tts output audio to the output buffer.
- I think it's better to merge this PR after #3995 to avoid more conflict in that PR.
- Upgrade llama.cpp to b4743.
> [WASI-NN] ggml: tts writes wav to output buffer

- CMakeLists.txt
- cmake/WASINNDeps.cmake
This version supports the s390x platform.
> [WASI-NN] ggml: bump to b4762; bump wasi-nn plugin to 0.1.13

- CMakeLists.txt
- cmake/WASINNDeps.cmake
- plugins/wasi_nn/wasinn_ggml.cpp
- test/plugins/wasi_nn/CMakeLists.txt
This PR contains:
21a0f5a6 [WASI-NN] ggml: bump to b4762; bump wasi-nn plugin to 0.1.13 (#4030)
d9e415b9 [WASI-NN] whisper: fix the modified test file path
36458f91 [WASI-NN] ggml: fix the warmup regression
> Update `0.14.1_plugin_lts` branch

- .github/extensions.paths-filter.yml
- .github/workflows/matrix-extensions.json
- .github/workflows/reusable-build-extensions-on-macos.yml
- .github/workflows/reusable-build-extensions.yml
- CMakeLists.txt
- plugins/wasmedge_stablediffusion/CMakeLists.txt
The refactor of workflows caused #3757 happened again.
This PR changed the default value for `WASMEDGE_PLUGIN_STABLEDIFFUSION_METAL` to `ON` (also to be consistent with `WASMEDGE_PLUGIN_WASI_NN_GGML_LLAMA_METAL` and  `WASMEDGE_PLUGIN_WASI_NN_WHISPER_METAL`) and updated related workflows; also added `CMakeLists.txt` to paths-filter of all plugins.
> [CMake] Enable Metal for stable-diffusion by default

- .github/workflows/README.md
- .github/workflows/build.yml
WasmEdge release for Ubuntu is built on Ubuntu 20.04, but no tests were run for the exact same settings.
> [CI] Test WasmEdge (Core) on Ubuntu 20.04 (x86_64)

- CMakeLists.txt
- cmake/WASINNDeps.cmake
- plugins/wasi_nn/wasinn_ggml.cpp
Starts from b4875: support gemma-3 text-only model
> [WASI-NN] ggml: bump to b4875; bump wasi-nn plugin to 0.1.15

- cmake/Helper.cmake
This new version brings stb_image_resize2.h 2.13.
> [Plugin] image: bump stb_image to f056911

- include/common/enum.inc
- include/validator/validator_component.h
- lib/validator/validator_component.cpp
Validates each <importname> in `c` must match a name in `a` with an argument, compared as strings. Types must match for the validation to pass.
Maintaining the Context class, will be extended in future to store the index spaces for further validation.
ref: https://github.com/WebAssembly/component-model/blob/main/design/mvp/Binary.md
> [Component Validation] Validate instantiate imports and arguments

- cmake/WASINNDeps.cmake
- plugins/wasi_nn/wasinn_openvino_genai.cpp
- plugins/wasi_nn/wasinnenv.cpp
Another bug may not be fixed here: setting a u8 Tensor in Rust will result in an i32 Tensor in the plugin. (#4068)
> [WASI-NN] Fix symbol of openvino genai

- include/ast/component/type.h
- include/validator/validator_component.h
- test/component/CMakeLists.txt
- test/component/componentvalidatortest.cpp
- Validation failed due to a typo in [IndexKind](https://github.com/WasmEdge/WasmEdge/blob/master/include/ast/component/type.h#L189)
FuncType should have the byte identifier `0x01`. See https://github.com/WebAssembly/component-model/blob/main/design/mvp/Binary.md#type-definitions
- tested with `hello_wasi_http.wasm` (ref: https://github.com/sunfishcode/hello-wasi-http/tree/29205a0749835bd65be65841640af913be9be794)
```
[2025-03-31 05:34:18.273] [warning] component model is enabled, this is experimental.
[2025-03-31 05:34:18.273] [warning] component model is an experimental proposal
[2025-03-31 05:34:18.277] [warning] component validation is not done yet.
[2025-03-31 05:34:18.277] [warning] component validation is not done yet.
[2025-03-31 05:34:18.277] [error] instantiation failed: unknown …
```
> [Component Model Validator] Fix InstanceExpr Validation, Add tests

- CMakeLists.txt
- cmake/WASINNDeps.cmake
- plugins/wasi_nn/wasinn_ggml.cpp
* There is no model, model_url, hf_repo, and hf_file. Instead, all these options are now inside the common_params_model structure.
* Support llama4-text only
> [WASI-NN] ggml: bump to b5074; bump wasi-nn plugin to 0.1.18

- include/common/enum.inc
- include/validator/context.h
- include/validator/validator_component.h
- lib/validator/validator_component.cpp
- test/component/componentvalidatortest.cpp
Changes:
- Used stack based approach to store the Component and its context. Now it will be easy to maintain the index spaces for each component separately, also parent component be accessed to validate the `Alias section`.
- Updated old flaky test
Tests:
```
Running main() from /home/sridamul/Desktop/open-source/WasmEdge/build/_deps/gtest-src/googletest/src/gtest_main.cc
[==========] Running 6 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 4 tests from ComponentValidatorTest
[ RUN      ] ComponentValidatorTest.CorrectMatchingMultipleComponents
[2025-04-07 03:44:55.590] [info] Started Component Model Validation.
[2025-04-07 03:44:55.590] [info] Started Component Model Validation.
[2025-04-07 03:44:55.590] [info] Started Component Model Validation.
[ …
```
> Validate CoreInstance Section, Improve Context, Add Tests for nested components

- .commitlintrc.js
- .github/dependabot.yml
- .github/workflows/commitlint.yml
Previously, WasmEdge maintainers manually checked the commit messages to see if their title meets the following format, `[Type] optionalScope: subject`. However, it's not possible to avoid fat finger merging some PR that doesn't meet this standard. So, I propose to use commitlint and the conventional commits spec for automatic detection.
If the commit message doesn't meet the standard, then the CI will fail to notify the contributors that their commit messages need to be fixed.
An example of failure will be like this:
Reference:
* Conventional commits: https://www.conventionalcommits.org/en/v1.0.0/
> [Voting Passed] ci(commitlint): introduce conventional commits

- .github/workflows/matrix-extensions.json
- plugins/wasi_nn/wasinn_chattts.cpp
- test/plugins/wasi_nn/wasi_nn.cpp
In chattts v0.1.1, ChatTTS.Chat.infer returns a Python list.
In chattts v0.2.1, ChatTTS.Chat.infer returns a numpy.ndarray.
Use PyObject_GetItem (the equivalent of the Python expression o[index]) instead of PyList_GetItem (works only for list).
> [WASI-NN] ChatTTS: modify compute function to be compatible with v0.2.1

- docs/CONTRIBUTING.md
Add a reduced version of commit message guidelines, including:
- commit sign-off (DCO)
- Conventional Commit
Because #3850 introduced conventional commit.
> docs: updates Contribution Guide

- include/common/enum.inc
- include/validator/context.h
- include/validator/validator.h
- include/validator/validator_component.h
- lib/loader/ast/component/component_type.cpp
- lib/validator/validator_component.cpp
~- SortCase (`alias export`) needs to be validated, the [InstanceDecl] (https://github.com/WasmEdge/WasmEdge/blob/master/include/ast/component/type.h#L253) always returning the CoreType for different cases !?~
~- Need to manage the shared context that persist between components~
Tests:
```
test/component/componentTests 
Running main() from /home/sridamul/Desktop/open-source/WasmEdge/build/_deps/gtest-src/googletest/src/gtest_main.cc
[==========] Running 5 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 3 tests from Component
[ RUN      ] Component.LoadAndValidate_TestWasm
[2025-05-02 00:58:18.589] [warning] component model is an experimental proposal
[2025-05-02 00:58:18.589] [warning] Component Model Validation is in active development.
[       OK ] …
```
> [Component Model] Validation of Alias section

- examples/plugin/wasi-crypto-signature/src/signatures.rs
The current WASI-Crypto-Signature example in [`examples/plugin/wasi-crypto-signature/src/signatures.rs`](https://github.com/WasmEdge/WasmEdge/blob/d2e412a66e87720e840f4122e05b4f5f18c340bf/examples/plugin/wasi-crypto-signature/src/signatures.rs) uses basic error handling with simple `Result<u32, i32>` return types, where the error is just a numeric code returned from the wasi-crypto-signature plugin. This makes the example less user-friendly and harder to understand.
My contribution features an Error Enum that maps the numeric errors to meaningful error names.
```rust
pub enum Error {
// i32 is the error code from the WASI-Crypto-Signature plugin
SignatureImport(i32),
SignatureExport(i32),
ArrayOutputLen(i32),
ArrayOutputPull(i32),
}
```
> [EXAMPLE] wasi-cryptography-signature: add proper error handling

- CMakeLists.txt
- cmake/WASINNDeps.cmake
- plugins/wasi_nn/wasinn_ggml.cpp
- plugins/wasi_nn/wasinn_ggml.h
- Bump ggml to b5463
- Bump wasi-nn plugin to 0.1.22
- Remove deprecated `dump-kv-cache`
- Use the new `media_marker` in mtmd
> feat(wasi-nn): bump ggml to b5463; bump wasi-nn plugin to 0.1.22

- utils/install.py
The command
```bash
curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --plugins wasi_nn-tensorflowlite
```
fails on Apple Silicon machines (darwin/arm64) with the following error:
```
ERROR - Plugin not compatible: darwinarm64wasi_nn-tensorflowlite
```
**Change:**
Added the following line to the plugin compatibility map in the install script:
```python
"darwin" + "arm64" + WASI_NN_TENSORFLOW_LITE: VersionString("0.13.0"),
```
This enables successful installation of the plugin on Apple Silicon machines (M1/M2/M3/M4) using the install script.
> Fix install.sh failure for Mac M4 with wasi_nn-tensorflowlite plugin

- cmake/WASINNDeps.cmake
- plugins/wasi_nn/CMakeLists.txt
- plugins/wasi_nn/wasinn_ggml.cpp
This PR contains
982b8556 feat(wasi-nn): bump ggml to b5593 and wasi-nn plugin to 0.1.25 (#4144)
26d79dbd fix(wasi-nn): clear the context before mtmd evaluation (#4143)
> feat(plugin): update 0.14.1_plugin_lts branch

- .github/workflows/build-extensions.yml
- .github/workflows/build.yml
- .github/workflows/docker.yml
- .github/workflows/release.yml
- .github/workflows/reusable-build-extensions.yml
- .github/workflows/reusable-build-on-ubuntu.yml
- .github/workflows/test-install-script.yml
- .github/workflows/test-python-install-script.yml
> ci(runner): Use github hosted arm runner instead of ours

- plugins/wasi_nn/wasinn_ggml.cpp
Fixes #4132 
This PR fix the `n_ubatch` assignment in metadata, which related to issue #4132 .
> fix(wasi-nn): fix n_ubatch assignment

- cmake/WASINNDeps.cmake
- plugins/wasi_nn/CMakeLists.txt
- plugins/wasi_nn/wasinn_ggml.cpp
- Upgrade ggml to b5640
- Update depreated `llama_kv_self_clear` to `llama_memory_claer`.
> feat(wasi-nn): bump ggml to b5640 and wasi-nn plugin to 0.1.26

- lib/loader/ast/section.cpp
- lib/loader/ast/type.cpp
1. Add GC proposal detection when loading recursive types
2. Simplify the valtype and reftype loading and support type index cases for valtype
> fix(loader): various fix

- include/api/wasmedge/wasmedge.h
Fixes #4147
Replace #4188 due to inactivity.
> fix(CAPI): no longer include stdbool.h after C23

- test/plugins/wasm_bpf/assets/bpf-sources/simple_map.bpf.c
- test/plugins/wasm_bpf/assets/bpf-sources/simple_ringbuf.bpf.c
Not sure why the dual license triggers the license failure. If reordering doesn't help, maybe we should separate these BPF tests into a standalone repo or remove them.
> chore(bpf): reorder the dual licenses to avoid the false positive license issue

- utils/docker/docker-bake.ubuntu.hcl
Update `"tags-simplified"` so that images for both base and plugins have a default one.
Before this PR:
- `ubuntu-24.04-build-clang` -> `ubuntu-24.04` 
After this PR:
- `ubuntu-24.04-build-clang` -> `ubuntu-24.04` 
- `ubuntu-20.04-build-clang-plugins-deps` -> `ubuntu-20.04-plugins`
> docker(ubuntu): simplify image names for plugins

- .github/workflows/release.yml
Unfortunately, we introduce a regression for the release process.
> ci(release): fixed the incorrect GitHub permissions

- .github/workflows/misc-linters.yml
- .lineguardrc
This PR adds support for **EOF (End Of File) newline enforcement** using `linelint`, integrated into the existing CI via the `misc-linters.yml` workflow. The goal is to detect and prevent missing trailing newlines in modified files during pull requests, ensuring consistency and adherence to best practices.
Closes: #3519
Related earlier PRs: #3558, #3559, #3560, #3592, #4083
---
* **New CI job: `linelint`**
* Uses `@linelint/cli` installed via `npm` (instead of the GitHub Action wrapper) to allow argument-based control.
* Automatically detects files changed in the PR using `git diff`.
* Skips third-party or irrelevant directories (`thirdparty/`, `dist/`, `.git/`).
* Runs linelint only on changed files (as required by previous feedback).
* Fails CI if any file is missing an EOF newline.
* …
> WIP: ci(linters): add EOF newline check via linelint to misc CI workflow

- .github/workflows/test-installers.yml
this fixes the code merged in #4261 which had one of the tests defined incorrectly , the workflow results are also available on the [master](https://github.com/0x-74/WasmEdge/actions/runs/16316070207/job/46082324759) branch of the fork .
> fix: fixed previously merged PR for symlink uninstallation with correct code

- include/api/wasmedge/wasmedge.h
- include/runtime/storemgr.h
- lib/api/wasmedge.cpp
- test/api/APIVMCoreTest.cpp
Closes: #2481 
Currently, the WasmEdge C API does not provide a way to delete or unregister a module that has been registered to a `WasmEdge_VMContext`. This can lead to inefficient memory/resource usage in long-running applications or when modules are dynamically managed.
This PR introduces a new API function:
```c
WASMEDGE_CAPI_EXPORT extern void
WasmEdge_VMDeleteRegisteredModule(const WasmEdge_VMContext *Cxt,
const WasmEdge_String ModuleName);
```
This allows users to explicitly delete a named module registered in a VM, enabling better control over module lifecycle and resource management.
* **API Definition**
Added the `WasmEdge_VMDeleteRegisteredModule` function declaration to the public C API header (`include/api/wasmedge/wasmedge.h`).
* **Core Implementation**
Implemented the …
> feat(c-api): add method to delete registered modules from VM

- .commitlintrc.js
See:
* https://github.com/WasmEdge/WasmEdge/actions/runs/16891220877/job/47851216236?pr=4313
* https://github.com/WasmEdge/WasmEdge/actions/runs/16891048853/job/47850646700?pr=4312
> ci(commitlint): set header-max-length to warning level due to Dependabot will create long commit header

- .github/workflows/test-installers.yml
- utils/install_v2.sh
- Handle new directory structure for v0.15.0+
- Remove obsolete wasi-logging plugin logic
- Add tests for tarball structure detection
- Fix non-ASCII characters in CI output
> feat(installer,v2): support WasmEdge 0.15.0 tarball structure

- include/common/statistics.h
- lib/common/errinfo.cpp
- test/api/APIUnitTest.cpp
- test/host/socket/wasi_socket.cpp
- test/host/wasi/wasi.cpp
- test/plugins/unittest/testplugin.cpp
* round nan to max uint64_t
* avoid using invalid input to shift number
* free unused module instance
* avoid unaligned access in unittest
> test: fix ubsan warnings

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/reusable-build-extensions-on-macos.yml
- .github/workflows/reusable-build-extensions.yml
- .github/workflows/reusable-build-on-macos.yml
- .github/workflows/test-installers.yml
See: https://github.com/actions/runner-images/issues/13046
The macOS 13 Ventura based runner images will begin deprecation on September 22nd and will be fully unsupported by December 4th.
> ci(runner): update macOS 13 runner to 14-large, due to deprecation
