README.md
Listed projects that use SSVM for real-world applications.
=> [Doc] Improve the introduction section

include/host/wasi/wasienv.h, include/po/argument_parser.h, include/po/helper.h, include/po/list.h, include/po/option.h, include/po/parser.h, lib/host/wasi/wasienv.cpp, tools/ssvm-aot/ssvmr.cpp
* add helper for argument parsing
=> [WASI] add dir bind options

include/host/wasi/wasienv.h, lib/host/wasi/wasienv.cpp, lib/host/wasi/wasifunc.cpp
* add flag for preopened dir
* prevent closing or renumbering preopened dir
=> [Wasi] change guest-host fd mapping to std::map

include/common/ast.h, include/common/ast/description.h, include/common/ast/expression.h, include/common/ast/instruction.h, include/common/ast/module.h, include/common/ast/section.h, include/common/ast/segment.h, include/common/ast/type.h, include/common/errinfo.h, include/interpreter/interpreter.h, include/validator/formchecker.h, lib/aot/compiler.cpp, lib/ast/expression.cpp, lib/ast/instruction.cpp, lib/interpreter/engine/engine.cpp, lib/support/log.cpp, lib/validator/formchecker.cpp
Refactor instruction class and apply to all modules.
* Loader
* Validator
* Interpreter
* AOT
* Log
=> Refactor instruction classes for 2-byte instructions.

.lgtm.yml
https://lgtm.com/projects/g/second-state/SSVM/
=> [Misc] add lgtm config file

lib/aot/compiler.cpp, test/CMakeLists.txt, test/aot/AOTwagonTest.cpp, test/aot/CMakeLists.txt
* Fix codegen bug on unreachable sections
=> [AOT] Add testcase for AOT

include/runtime/instance/memory.h
On low memory platform, overcommitting memory is decline by kernel.
By parsing smaps, we find a usable memory region and request exact
address and not overcomitting memory.
=> [Runtime] Allocate on request, don't preserve full 4G memory at once.

include/common/statistics.h, include/common/timer.h, lib/interpreter/engine/engine.cpp
=> [Misc] Use stantard steady clock for timer

include/common/variant.h, include/interpreter/engine/binary_numeric.ipp, include/interpreter/engine/cast_numeric.ipp, lib/aot/compiler.cpp, lib/interpreter/engine/memory.cpp, lib/interpreter/engine/table.cpp, lib/validator/formchecker.cpp, test/expected/observers.cpp, test/loader/filemgrTest.cpp, test/spec/spectest.cpp
* Run clang-format-10
* Fix LLVM-9 errors
=> [AOT] Support LLVM 11

include/common/types.h, include/common/value.h, include/interpreter/engine/binary_numeric.ipp, include/interpreter/engine/memory.ipp, include/interpreter/engine/unary_numeric.ipp, lib/interpreter/engine/engine.cpp
* Add all subtype of V128
* Remove redundant reinterpret_cast
=> v128 subtype

lib/host/wasi/wasifunc.cpp, lib/interpreter/engine/engine.cpp, thirdparty/wasi/core.h, tools/ssvm/ssvmr.cpp
* Update size of linkcount to u64
* Accept existing fd for renumbering
* Change to .wasm filename extension for argv[0]
* Don't report error on Terminate status
=> WASI misc fix

.github/workflows/build.yml, utils/docker/Dockerfile.base
* Change CI workflows to use ninja generator
=> [Misc] Add ninja-build on docker image

lib/aot/compiler.cpp
=> [AOT] Fix AArch64 testcase

.github/workflows/build.yml, include/CMakeLists.txt, include/aot/compiler.h, include/aot/version.h, include/common/config.h.in, include/po/argument_parser.h, include/po/helper.h, include/po/list.h, include/po/option.h, lib/aot/CMakeLists.txt, lib/aot/compiler.cpp, lib/common/CMakeLists.txt, lib/loader/loader.cpp, lib/vm/CMakeLists.txt, test/CMakeLists.txt, test/po/CMakeLists.txt, test/po/gtest.cpp, test/po/po.cpp, tools/ssvm/CMakeLists.txt, tools/ssvm/ssvmc.cpp, tools/ssvm/ssvmr.cpp
* add check for version option
* add noexcept in PO classes
* add cmake command for generating version infomation
=> [Misc] Add version infomation in command line

.github/workflows/docker.yml, utils/docker/Dockerfile.ci-image-base
Try to fix this permission issue: https://github.com/second-state/SSVM/runs/1685193865?check_suite_focus=true
=> [CI] Create a CI docker env for building the remaining docker images

lib/interpreter/helper.cpp
Fix problem on https://github.com/jedisct1/webassembly-benchmarks
=> [Hostfunc] Return error on error

test/host/wasi/wasi.cpp
=> [WASI] Add testcases for path

.github/workflows/build.yml, .github/workflows/doc.yml, .github/workflows/docker.yml, .github/workflows/release.yml
=> [CI] Enable Concurrency in the workflows

.editorconfig
=> [Misc] Preserve trailing whitespaces in markdown files

utils/docker/Dockerfile.manylinux1_x86_64, utils/docker/Dockerfile.manylinux2010_x86_64, utils/docker/Dockerfile.manylinux2014_aarch64, utils/docker/Dockerfile.manylinux2014_x86_64
=> [Docker] Provide cpu infomation for gmp to build more generic code

lib/common/CMakeLists.txt
=> [Misc] Don't show message when spdlog not found

CMakeLists.txt, lib/common/CMakeLists.txt, lib/host/wasi/CMakeLists.txt, lib/host/wasi/wasifunc.cpp, lib/host/wasmedge_process/CMakeLists.txt, lib/interpreter/CMakeLists.txt, lib/loader/CMakeLists.txt, lib/system/CMakeLists.txt, lib/vm/CMakeLists.txt, test/CMakeLists.txt
* Use git shallow clone to speed up downloading
=> [Misc] Fetch boost source when boost is not found

.github/workflows/docker.yml
=> [CI] Make docker image build when PR is merged into master branch

include/system/path.h, lib/aot/cache.cpp, lib/system/CMakeLists.txt, lib/system/config.h.in, lib/system/path.cpp
=> [AOT] Move system-depended code to system library

test/spec/CMakeLists.txt
=> [Test] Use master branch for rapidjson

.github/workflows/release.yml, CMakeLists.txt
=> [CI] Fix release workflow on manylinux2010 and manylinux1

.CurrentChangelog.md, Changelog.md
@ibmibmibm  @hydai 
You can update the change log here.
=> [Doc] Update Changelog for 0.8.1 release.

.CurrentChangelog.md, Changelog.md, doc/build.md, doc/contribution.md
=> [Doc] Update Changelog, Docs for 0.8.1 release

README.md
=> [Doc] Update links

doc/c_api_quick_start.md
=> [Doc] Add the C API documentation.

doc/roadmap.md
=> [Doc] Update ROADMAP

doc/showcase.md
=> [Doc] Add showcase.md

doc/showcase.md
=> [Doc] Add YoMo

README.md
I noticed that you had a Twitter account, so I added it.
Signed-off-by: actly <actlyster@gmail.com>
=> [Doc] Add Twitter link

include/common/configure.h, lib/aot/compiler.cpp, tools/wasmedge/wasmedgec.cpp
=> [AOT] Add --generic-binary to disable using host features

.CurrentChangelog.md, Changelog.md, doc/build.md
=> [Doc] Prepare for 0.8.2-rc.1 prerelease

.github/workflows/build.yml
=> [CI] Disable build when there is only doc changes

lib/aot/compiler.cpp
=> [AOT] Set CPUName to generic once the --generic-binary is set

.github/workflows/codeql-analysis.yml
=> [CI] Enable CodeQL

.github/scripts/clang-format.sh, .github/workflows/linter.yml, include/host/wasi/inode.h, include/host/wasi/vinode.h, lib/host/wasi/inode-linux.cpp, lib/host/wasi/linux.h, lib/interpreter/engine/proxy.cpp
=> [CI] Enable clang-format checker in workflow

.github/workflows/codeql-analysis.yml
=> [CI] CodeQL should exclude test folder

include/common/int128.h, include/common/types.h, include/interpreter/engine/binary_numeric.ipp, include/runtime/instance/memory.h, lib/host/wasmedge_process/processfunc.cpp, lib/system/allocator.cpp, lib/validator/formchecker.cpp, test/spec/spectest.cpp
* Add uint128 class
* Add padding to ExternRef for 32-bit pointer
=> [Misc] Add support 32-bit environment for interpreter

.CurrentChangelog.md, .github/workflows/build.yml, Changelog.md
=> [Docs] Update Changelog for 0.8.2-rc.4 pre-release

.CurrentChangelog.md, Changelog.md
=> [Docs] Update Changelog for 0.8.2-rc.5 pre-release.

docs/use_cases.md
=> [Docs] Improve the use cases document

docs/c_api_quick_start_zh.md
translate doc/c_api_quick_start to simplified Chinese
=> [Docs] translate doc/c_api_quick_start to simplified Chinese

docs/build.md, docs/build_zh.md
Changes include:
- `build.md` remove duplicated sentence.
- `build_zh.md` translation for `build.md`.
=> [Docs] Translate docs/build.md to simplified Chinese

README-zh-TW.md, README-zh.md, README.md
=> [Docs] Add CII best practice badge

README.md, docs/install.md, docs/run.md
Update the install and run docs to use the new scripts.
=> [Docs] Use the new install script

utils/install.sh
* Checks if script is being run with `root` permissions
* Installs into current users home directory
* When run by `root` Checks if `sudo` is present and installs into current user's home directory
* If `sudo` is absent it does not manipulate $HOME
Ref - #381
=> Install into User's Home by default #381 

.github/ISSUE_TEMPLATE/feature_request.md
=> [Misc] Update GitHub issue template

docs/install.md, utils/install.sh
- Checks for `git` and if not available then exits.
- Checks for `wget`, if not then checks for `curl`, if not then exits.
=> [Install Script] Improve Install script

utils/docker/Dockerfile.appdev_aarch64, utils/docker/Dockerfile.appdev_x86_64, utils/docker/build-appdev.md
Those Dockerfiles create images that are suitable for application developers using WasmEdge.
=> [Utils] Add app dev Docker files

docs/use_cases-zh.md
Signed-off-by: MileyFu <furao@wespoke.com>
=> [docs] Create use_cases-zh.md

.github/workflows/linter.yml
=> [CI] Use ubuntu-latest to run linter

.github/workflows/build.yml, .github/workflows/release.yml, docs/build.md, docs/build_zh.md, utils/docker/Dockerfile.base, utils/docker/Dockerfile.build-clang, utils/docker/Dockerfile.ci-image-base
=> [Misc] Rollback the development environment from 21.04 to 20.04 LTS

utils/install.sh
* Removed dangerous removal of path #412 
* Quoting of variables as per shellcheck 2086
https://github.com/koalaman/shellcheck/wiki/SC2086.
* Apologies to the affected users ;-(
=> [Utils] Install Script Fix

README-zh-TW.md
Append "zh" to end of the link http://reactor.secondstate.info/
Signed-off-by: 牟展佑 <william.mou1024@gmail.com>
=> [Docs] Fixed Serverless Reactor hyperlink

.github/ISSUE_TEMPLATE/bug_report.md
=> [docs]Update bug_report.md

.github/ISSUE_TEMPLATE/feature_request.md
=> [docs]Update feature_request.md

docs/install.md, utils/install.sh, utils/uninstall.sh
=> [Utils] Uninstall script improvements

include/aot/version.h, include/ast/module.h, include/ast/section.h, include/common/configure.h, include/common/enum_ast.h, include/loader/loader.h, include/loader/shared_library.h, include/system/allocator.h, lib/aot/compiler.cpp, lib/ast/module.cpp, lib/ast/section.cpp, lib/loader/ldmgr.cpp, lib/loader/loader.cpp, lib/loader/shared_library.cpp, lib/system/allocator.cpp, test/aot/AOTcoreTest.cpp, tools/wasmedge/wasmedgec.cpp
* Add test for custom section version
* Changes in aot format:
- Remove init function
- Remove types/codes array
- Add intrinsic variable
=> [AOT] Create custom section for aot binary format

README.md, docs/install.md, docs/run.md
=> [Docs] Adding docker instructions

docs/build.md, docs/build_on_mac.md
=> [Docs] Add build guide for macos

utils/install.sh, utils/uninstall.sh
* Added support for macOS 
* Suggestions given at #433
=> [Utils] Scripts:MacOS support

.github/workflows/test-install-script.yml, utils/install.sh, utils/uninstall.sh
* Suggestion menstioned in https://github.com/WasmEdge/WasmEdge/issues/514#issue-1031461951
* Uses bash variable expansion to make libsome.so.xx.yy.zz to libsome.so and libsome.so.xx
* Minor: Removed exit trap for help
=> [Utils] Install and Uninstall Script Improvements

include/common/errcode.h, include/common/roundeven.h, include/common/timer.h, include/executor/executor.h, include/runtime/stackmgr.h, lib/aot/compiler.cpp, lib/executor/engine/proxy.cpp, lib/executor/instantiate/data.cpp, lib/executor/instantiate/elem.cpp, lib/system/allocator.cpp, lib/system/fault.cpp, test/spec/spectest.cpp
=> [Misc] Add assuming to help compiler generating better codes

.github/codecov.yml
=> [CI] Add codecov.yml

README-zh-TW.md, README-zh.md, README.md
=> [Docs] Add CodeQL badge

include/common/enum_configure.h, include/common/enum_errcode.h, include/common/enum_types.h
=> [Common] Add the checking of c++17 in api headers.

.github/workflows/rust-crate-release.yml
Signed-off-by: Antonio Yang <yanganto@gmail.com>
=> [CI] Fix Rust crate build and publish

bindings/rust/wasmedge-sdk/Cargo.toml, bindings/rust/wasmedge-sys/Cargo.toml, bindings/rust/wasmedge-sys/build.rs
=> [Rust] Path compatible with version less than 0.9

.github/workflows/static-code-analysis.yml
- Downgrade the clang version to 11
- Fixes #618 
- https://github.com/avinal/WasmEdge/runs/4124582894?check_suite_focus=true
Signed-off-by: Avinal Kumar <avinal.xlvii@gmail.com>
=> [CI] Fix static analysis GitHub Actions

include/loader/shared_library.h, lib/loader/ast/section.cpp
* Add `unlikely` on error checks
=> [AOT] Allow zero address used in aot section

utils/install.sh
* Fixes `sourcing` not being appended to $HOME/.shellrc
=> [Utils] Install Script: Fix sourcing not appended in case of path from CLI

utils/docker/Dockerfile.appdev_aarch64, utils/docker/Dockerfile.appdev_x86_64
Allow CLI and NAPI to work together on the same image
Signed-off-by: Michael Yuan <michael@secondstate.io>
=> [Docker] Update appdev Docker images for the latest install script

docs/use_cases-zh.md
Signed-off-by: MileyFu <furao@wespoke.com>
=> [Docs]Update use_cases-zh.md

lib/loader/ast/section.cpp
=> [Loader] Handle unsupported OS and ARCH type

.github/workflows/static-code-analysis.yml
=> [CI] Fix deps issues in infer workflow

.github/workflows/build.yml, utils/docker/test-ubuntu.sh
=> [CI] Make ctest output failure logs

bindings/rust/wasmedge-sys/src/import_obj.rs
fix #673 
Signed-off-by: Antonio Yang <yanganto@gmail.com>
=> [Rust] Implement create wasi

bindings/rust/wasmedge-sys/Cargo.toml, bindings/rust/wasmedge-sys/examples/hostfunc2.rs, bindings/rust/wasmedge-sys/src/import_obj.rs, bindings/rust/wasmedge-sys/src/module.rs
=> [Rust] Module load from buffer

.github/workflows/build.yml
=> [CI] Upload build artifacts for nightly build

README.md
=> [Docs] Add the community meeting  details

rpm/WasmEdge.spec
=> [Misc] Add rpm spec file

rpm/WasmEdge.spec
=> [Misc] Update version in rpm spec file

docs/run.md
=> [Docs] Add tutorials for the universal wasm binary format

.github/workflows/build.yml, .github/workflows/release.yml
=> [CI] Upload windows assets

include/common/roundeven.h
=> [Platform] Fix frintn on armv7-a

.CurrentChangelog.md, Changelog.md
=> [Docs] Update changelog to thank all the contributors

.CurrentChangelog.md, Changelog.md, docs/c_api.md, docs/go_api.md
Merge this after the other all required PR for 0.9.0.
=> [Changelog] Update the changelog and docs for the 0.9.0 release.

.github/workflows/release.yml
=> [CI] Fix the source tarball name in the release workflow

.github/workflows/release.yml
=> [CI] Sleep 5 second to avoid GitHub API ECONNRESET error

utils/docker/Dockerfile.manylinux1_x86_64, utils/docker/Dockerfile.manylinux2010_x86_64, utils/docker/Dockerfile.manylinux2014_aarch64, utils/docker/Dockerfile.manylinux2014_x86_64
=> [Utils] Update isl link

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/linter.yml, .github/workflows/static-code-analysis.yml
=> [CI] Disable unrelated CI workflow via adding ignore-paths

utils/docker/Dockerfile.appdev_aarch64, utils/docker/Dockerfile.appdev_x86_64, utils/docker/build-appdev.md
Signed-off-by: Michael Yuan <michael@secondstate.io>
=> [Utils] Update appdev Docker images to 0.9.0

.github/workflows/build.yml, docs/build.md, docs/build_on_windows.md
=> [Docs] Add build on windows instructions

include/api/wasmedge/wasmedge.h
=> [API] Fix the doc comment of `WasmEdge_CompilerCompile`.

docs/book/en/src/frameworks/app/reactr.md
=> book/frameworks/reactr: fix typo

bindings/rust/wasmedge-sys/src/executor.rs
This PR is to add the necessary descriptions for the Executor struct.
=> [Rust] Added doc comments for Executor

docs/book/en/src/frameworks/app/reactr.md
* Fixes a typo in the reactr doc
=> fix(reactr.md): s/suit/suite

docs/c_api.md, docs/go_api.md, include/api/wasmedge/wasmedge.h
=> [Docs] Fix the typos and comments of API.

include/api/wasmedge/wasmedge.h, include/common/configure.h, include/common/enum_errcode.h, include/executor/executor.h, include/runtime/instance/function.h, include/vm/async.h, include/vm/vm.h, lib/aot/compiler.cpp, lib/api/wasmedge.cpp, lib/executor/helper.cpp, lib/vm/vm.cpp, test/aot/AOTcoreTest.cpp, test/api/APIAOTCoreTest.cpp, test/api/APIUnitTest.cpp, test/api/APIVMCoreTest.cpp, test/executor/ExecutorTest.cpp, tools/wasmedge/wasmedgec.cpp, tools/wasmedge/wasmedger.cpp
* Support asynchronous execution
* Add new option for timeout execution
* Add new option for support interruptible execution in AOT
=> [Misc] Add interruptible execution

bindings/rust/wasmedge-sys/src/statistics.rs
This PR is to add the necessary descriptions for the Statistics struct.
=> [Rust] Added doc comments for Statistics

bindings/rust/wasmedge-sys/src/loader.rs
This PR is to add the necessary descriptions for the Loader struct.
=> [Rust] Added doc comments for Loader

bindings/rust/wasmedge-sys/src/validator.rs
This PR is to add the necessary descriptions for the Validator struct.
=> [Rust] Added doc comments for Validator

docs/book/en/src/SUMMARY.md
=> [Docs] Fix typoes in book ToC

README.md, docs/wish_list.md
Use book links when possible. Add new features we want to highlight.
=> [Docs] Improve README

docs/book/en/src/embed/go/bindgen.md, docs/book/en/src/embed/go/function.md, docs/book/en/src/embed/go/tensorflow.md
Signed-off-by: Michael Yuan <michael@secondstate.io>
=> [Docs] Add chapters for wasmedge_bindgen

.github/workflows/witx.yml
=> [CI] Rename doc.yml to witx.yml. This is only handle the *.witx files

docs/book/en/src/index.md, docs/book/en/src/start/cli.md, docs/run.md, include/common/configure.h, include/common/statistics.h, include/executor/executor.h, lib/executor/engine/engine.cpp, lib/executor/executor.cpp, tools/wasmedge/wasmedger.cpp
=> [Tools] Enable --gas-limit for wasmedge cli

docs/book/en/src/SUMMARY.md, docs/book/en/src/os/raspberrypi.md
Signed-off-by: KernelErr <45716019+KernelErr@users.noreply.github.com>
This pull request is intended to close issue #443.
=> [Docs] Add running on Raspberry Pi documentation

lib/api/wasm_c.cpp, lib/api/wasmedge.cpp
Signed-off-by: William-Mou <william.mou1024@gmail.com>
=> [API] Add runtime wrapper of C API

bindings/rust/wasmedge-sys/src/instance/function.rs, bindings/rust/wasmedge-sys/src/instance/global.rs, bindings/rust/wasmedge-sys/src/instance/memory.rs, bindings/rust/wasmedge-sys/src/instance/table.rs, bindings/rust/wasmedge-sys/src/lib.rs, bindings/rust/wasmedge-sys/src/store.rs, bindings/rust/wasmedge-sys/src/types.rs
This PR is to add the necessary descriptions for the Function, Memory, and Table structs.
=> [Rust] Added doc comments for Function, Memory, and Table

.github/workflows/test-install-script.yml, utils/uninstall.sh
Suggestions from https://github.com/WasmEdge/WasmEdge/issues/946#issue-1088600259
=> [Utils] Uninstall Script Improvement

bindings/rust/wasmedge-sys/src/vm.rs
This PR is to add the necessary description for the Vm struct.
=> [Rust] Added doc comments for Vm

bindings/rust/wasmedge-sys/src/store.rs
This PR is to add the necessary description for the Store struct.
=> [Rust] Added doc comments for Store

bindings/rust/wasmedge-sys/examples/hostfunc.rs, bindings/rust/wasmedge-sys/examples/hostfunc2.rs, bindings/rust/wasmedge-sys/src/lib.rs, bindings/rust/wasmedge-sys/src/module.rs
This PR is to add the necessary description for the Import and Export structs.
=> [Rust] Added doc comments for Import and Export.

.github/CODEOWNERS
=> [Misc] Update CODEOWNERS

bindings/rust/wasmedge-sys/Cargo.toml, bindings/rust/wasmedge-sys/src/compiler.rs, bindings/rust/wasmedge-sys/src/config.rs, bindings/rust/wasmedge-sys/src/error.rs, bindings/rust/wasmedge-sys/src/executor.rs, bindings/rust/wasmedge-sys/src/import_obj.rs, bindings/rust/wasmedge-sys/src/instance/function.rs, bindings/rust/wasmedge-sys/src/instance/global.rs, bindings/rust/wasmedge-sys/src/instance/memory.rs, bindings/rust/wasmedge-sys/src/instance/table.rs, bindings/rust/wasmedge-sys/src/lib.rs, bindings/rust/wasmedge-sys/src/loader.rs, bindings/rust/wasmedge-sys/src/module.rs, bindings/rust/wasmedge-sys/src/statistics.rs, bindings/rust/wasmedge-sys/src/store.rs, bindings/rust/wasmedge-sys/src/types.rs, bindings/rust/wasmedge-sys/src/utils.rs, bindings/rust/wasmedge-sys/src/validator.rs, bindings/rust/wasmedge-sys/src/version.rs, bindings/rust/wasmedge-sys/src/vm.rs
This PR is to refactor the original error handling design.
=> [Rust] Refactored error handling design.

bindings/rust/wasmedge-sys/src/lib.rs, bindings/rust/wasmedge-sys/src/utils.rs
This PR is to support two logging C-APIs:
- Fix #765 
- Fix #766
=> [Rust] Implemented the logging APIs

docs/book/en/src/kubernetes/kubernetes/kind.md
Hi,
As as requested in https://github.com/Liquid-Reply/kind-crun-wasm/issues/1 we started with a description of the KinD wasmedge/crun image. 
Feedback is welcome 🙂
=> Add guide how to use Kind with wasmedge

cmake/FindFilesystem.cmake
=> [Misc] Fix SPDX license identifier

lib/executor/engine/variableInstr.cpp
Signed-off-by: Harinath Nampally <harinath922@gmail.com>
=> [Code Quality] Null pointer dereference check #527

docs/book/zh/src/os/openharmony.md
Move the Openharmony standard OS tutorial.
=> [Doc] Add OpenHarmony.md

utils/install.sh, utils/uninstall.sh
* Fix for https://github.com/WasmEdge/WasmEdge/issues/1003#issue-1099922443
* Minor Spelling correction
=> [Utils] Scripts: Minor improvements

.CurrentChangelog.md, Changelog.md, ReleaseProcess.md, docs/ecosystem.md, include/api/wasmedge/wasmedge.h, lib/host/wasi/wasimodule.cpp
This PR should be merged after the #979 .
=> Changelog for 0.9.1-alpha.1

docs/book/en/src/index.md, docs/book/zh/src/index.md, docs/book/zh/src/start/cli.md, docs/book/zh/src/start/docker.md
Signed-off-by: SonOfMagic <qq1324318532@gmail.com>
=> [Docs] Translate index.md cli.md docker.md into zh-cn

.CurrentChangelog.md, Changelog.md
=> [Changelog] Update the changelog for the 0.9.1-beta.1 pre-release.

bindings/rust/wasmedge-sys/tests/test_aot.rs
This PR is to add an integration test case for the AOT feature.
=> [Rust] Added integration test for the AOT feature.

docs/book/en/src/embed/c/ref.md
=> [Docs] Update C API - Async

.github/workflows/build.yml, .github/workflows/release.yml, utils/android/standalone/build_for_android.sh
=> [CI] Add the CI for Android build.

docs/book/zh/src/kubernetes/cri/containerd.md
Signed-off-by: villanel <56783950+villanel@users.noreply.github.com>
=> Translate the kubernetes/cri/containerd.md to zh

docs/book/zh/src/kubernetes/kubernetes/kind.md
#1075  Add translation for kind chapter
=> [Docs] Add translation for kind chapter

docs/book/zh/src/dev/js/tensorflow.md
Signed-off-by: Dong Zhe <dreammyboy@163.com>
=> Translate dev/js/tensorflow.md to zh #1113 finished by dz

docs/book/en/src/os/android.md, docs/book/zh/src/os/android.md
Signed-off-by: CChristal <564429983@qq.com>
=> [Docs] Add the doc of using wasmedge-tensorflow-tools on Android

docs/book/en/src/embed/go.md
1. unified in the second person 
2. make the document read more fluently
=> [Docs]improve go.md

docs/book/zh/src/os/raspberrypi.md
Signed-off-by: zephoon <zephoonyu@protonmail.com>
=> adjustion for raspberrypi.md

docs/book/zh/src/embed/go/function.md
Signed-off-by: peterbi <peterbi@live.com>
Issue: Translate embed/go/function.md to zh #1090
=> Translate embed/go/function.md to zh #1090

docs/book/zh/src/extend/plugin.md
Signed-off-by: xiaoqi <1099046071@qq.com>
Translate extend/plugin.md to zh
=> Translate extend plugin.md to zh

.github/workflows/test-install-script.yml, utils/install.sh
* Behaviour: Creates Shell profiles/configuration files only if these pre-exist.
* Suggestions from https://github.com/WasmEdge/WasmEdge/issues/1058
=> [Utils] Install Script Improvement

docs/book/en/src/extend/build_on_windows.md
=> [Docs] Fix the extension name 'dyld' -> 'dll'. Fix #1149

rpm/wasmedge.spec
* Split the all-in-one rpm into three rpm: wasmedge, wasmedge-devel, and
wasmedge-lib
=> [Misc] Update RPM files for 0.9.1 release.

docs/book/en/src/index.md, docs/book/en/src/start/install.md, docs/book/zh/src/index.md, docs/book/zh/src/start/install.md
Signed-off-by: Rui Li <me@lirui.tech>
Sorry, I don't quite know about Traditional Chinese.
=> [Doc] Add winget installation method

docs/book/en/src/embed/node.md, docs/book/en/src/index.md, docs/book/en/src/start/install.md, docs/book/zh/src/dev/js/quickstart.md, docs/book/zh/src/embed/go.md, docs/book/zh/src/embed/node.md, docs/book/zh/src/extend/plugin/hostfunction.md, docs/book/zh/src/frameworks/mesh.md, docs/book/zh/src/index.md, docs/book/zh/src/kubernetes/demo/wasi.md, docs/book/zh/src/os/android.md, docs/book/zh/src/os/android/apk.md, docs/book/zh/src/os/android/cli.md, docs/book/zh/src/os/android/ndk.md, docs/book/zh/src/start/install.md
=> [Docs] Fix the markdown errors.

.github/workflows/fossa-scan.yml
=> [CI] Enable FOSSA action

include/host/wasi/inode.h, lib/host/wasi/linux.h
=> [Misc] Defined __GLIBC_PREREQ to 1 for musl libc

docs/book/zh/src/frameworks/mesh/dapr.md
Signed-off-by: vaniot <vaniot@yeah.net>
=> [Docs] Translate frameworks/mesh/dapr.md

include/common/dense_enum_map.h, include/common/spare_enum_map.h
* Cast unsigned index to signed type
* Add const method for ConstIterator
=> [Misc] Fix error in windows

docs/book/zh/src/frameworks/app.md
Fix: #1203 
Signed-off-by: mydreamer4134 <adamsa@foxmail.com>
=> [Doc] Translate #frameworks/app.md to zh

docs/book/en/src/extend/build.md
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
=> [Docs] "without AOT" section should belong to "Build WasmEdge"

docs/book/zh-TW/src/extend/build.md, docs/book/zh/src/extend/build.md
See https://github.com/WasmEdge/WasmEdge/pull/1284#issuecomment-1050619125
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
=> [Docs] Sync change to other versions

.github/workflows/bindings-rust.yml, bindings/rust/wasmedge-sys/build.rs
This PR is to add support for building rust-binding on MacOS.
- Fixed #1269
=> [CI] Added support for building rust-binding on MacOS.

include/executor/executor.h, include/runtime/stackmgr.h, lib/executor/instantiate/export.cpp, lib/executor/instantiate/function.cpp, lib/executor/instantiate/import.cpp, lib/executor/instantiate/memory.cpp, lib/executor/instantiate/module.cpp, lib/executor/instantiate/table.cpp
=> [Executor] Simplify the function signature.

docs/book/en/src/rust/wasmedge-sys-api.md
This PR is to remove the unused markdown file from the mdbook.
=> [Docs] Removed the unused markdown file.

docs/book/zh/src/embed/rust/sys_run_host_func.md
Signed-off-by: JSCZhongJian <11638005@qq.com>
=> This is my commit message

docs/book/zh/src/SUMMARY.md, docs/book/zh/src/embed/go/host_function.md
Signed-off-by: DarumaDocker <DarumaDocker@gmail.com>
=> [Book] zh Page for Host Function

include/po/argument_parser.h, include/po/error.h, include/po/helper.h, include/po/list.h, include/po/option.h, include/po/parser.h
* Add `PO::Error` to replace exception
=> [PO] Remove all usage of throwing exceptions

include/ast/module.h, include/common/enum.inc, lib/aot/compiler.cpp, lib/executor/instantiate/module.cpp, lib/validator/validator.cpp, test/api/APIUnitTest.cpp
=> [AST] Add the validated flag in module.

include/executor/executor.h, include/runtime/stackmgr.h, lib/executor/engine/controlInstr.cpp, lib/executor/engine/engine.cpp, lib/executor/executor.cpp, lib/executor/helper.cpp, lib/executor/instantiate/data.cpp, lib/executor/instantiate/elem.cpp, lib/executor/instantiate/module.cpp, lib/validator/formchecker.cpp
=> [Executor] Refine the value stack pop mechanism in execution.

include/api/wasmedge/wasmedge.h, lib/api/wasmedge.cpp, test/api/APIUnitTest.cpp
Signed-off-by: Xin Liu <sam@secondstate.io>
=> [C-API] Implemented WasmEdge_ImportObjectGetModuleName.

bindings/rust/wasmedge-sys/src/instance/table.rs, bindings/rust/wasmedge-sys/src/types.rs
In this PR, the refactored C-APIs, `WasmEdge_ValueGenFuncRef` and `WasmEdge_ValueGetFuncRef`, are supported. The failed CI workflows in PR #1357, `binding-rust / Ubuntu 20.04` and `binding-rust / MacOS (macos-11)`, are fixed.
- Fixed #1357.
=> [Rust]: Supported the new C-APIs.

include/common/enum.inc, include/executor/executor.h, include/runtime/stackmgr.h, lib/aot/compiler.cpp, lib/executor/engine/controlInstr.cpp, lib/executor/engine/engine.cpp, lib/executor/helper.cpp, lib/loader/ast/instruction.cpp, lib/validator/formchecker.cpp, test/spec/CMakeLists.txt, test/spec/spectest.cpp, tools/wasmedge/wasmedgec.cpp, tools/wasmedge/wasmedger.cpp
@ibmibmibm  Please help to complete the `tail-call` in AOT. Thanks.
=> [Proposal] WASM Tail-call Proposal

bindings/rust/wasmedge-sys/src/instance/table.rs, bindings/rust/wasmedge-sys/src/types.rs, include/api/wasmedge/wasmedge.h, include/common/types.h, include/runtime/instance/function.h, include/runtime/instance/memory.h, include/runtime/storemgr.h, lib/api/wasmedge.cpp, lib/common/errinfo.cpp, lib/executor/engine/controlInstr.cpp, lib/executor/engine/engine.cpp, lib/executor/engine/proxy.cpp, test/api/APIUnitTest.cpp, test/errinfo/errinfoTest.cpp, test/spec/spectest.cpp
The C API docs will be updated after the alpha stage.
=> Remove the function address mechanism in the store

docs/book/en/src/embed/rust.md, docs/book/en/src/embed/rust/concurrent_fib.md, docs/book/en/src/embed/rust/sys_run_host_func.md
This PR is to sync up the changes in `wasmedge-sys v0.5.0` to the MDBook.
=> [MDBook][rust]: Updated the Rust-related sections.

.github/workflows/build.yml, .github/workflows/static-code-analysis.yml
=> [CI] Ignore useless workflow path

docs/book/en/src/embed/c/ref.md
=> [Docs] Fix the errors in C-API reference.

utils/docker/build-manylinux.sh
* Set git config `safe.directory` for root directory owned by someone else
=> [Misc] Update boost in manylinux build

README.md
Signed-off-by: tpmccallum <mistermac2008@gmail.com>
=> [Docs] Update wording and fix spelling

.github/workflows/build.yml, CMakeLists.txt, include/host/wasi_nn/wasinncontext.h, include/host/wasi_nn/wasinnfunc.h, include/host/wasi_nn/wasinnmodule.h, lib/api/wasmedge.cpp, lib/host/wasi_nn/CMakeLists.txt, lib/host/wasi_nn/wasinnfunc.cpp, lib/host/wasi_nn/wasinnmodule.cpp, lib/vm/CMakeLists.txt, tools/wasmedge/wasmedger.cpp, utils/docker/build-wasinn-ubuntu-openvino.sh, utils/docker/test-wasinn-ubuntu-openvino.sh
=> [WASI] support OpenVINO backend for WASI-NN

docs/book/en/src/extend/build.md
Signed-off-by: abhinandanudupa <67597710+abhinandanudupa@users.noreply.github.com>
=> [Docs] Fix wording and add dockerhub link

.github/workflows/build.yml
=> [CI] Fix the artifact uploading.

include/host/wasi/environ.h, include/host/wasi/inode.h, include/host/wasi/vinode.h, include/host/wasi/wasifunc.h, lib/host/wasi/CMakeLists.txt, lib/host/wasi/inode-linux.cpp, lib/host/wasi/inode-macos.cpp, lib/host/wasi/inode-win.cpp, lib/host/wasi/wasifunc.cpp, lib/host/wasi/win.h, test/host/socket/CMakeLists.txt, test/host/socket/wasi_socket.cpp, test/host/wasi/wasi.cpp
* ```sockListen(uint32)``` to ```sockListen(int32)```
* fix address buffer issue when use IPv6
=> [Socket] Support win socket

.CurrentChangelog.md, Changelog.md, docs/book/en/src/embed/c/ref.md, docs/book/en/src/os/android/cli.md, docs/book/en/src/os/android/ndk.md, docs/book/en/src/start/install.md, docs/book/zh/src/os/android/cli.md, docs/book/zh/src/os/android/ndk.md
=> [Docs] Update installation version to the newest one.

.github/workflows/test-install-script.yml, utils/install.sh
=> [Installer] feat: Support darwin x86_64 platform for the extensions.

.github/workflows/post-release.yml
=> [CI] Run libsodium tests on post-release

.github/CODEOWNERS
=> [Misc] Add @SAtacker to CODEOWNERS for install and uninstall scripts

.github/workflows/build.yml, .github/workflows/release.yml
=> [CI] Fix the unsafe repository issue.

.github/workflows/build.yml, .github/workflows/release.yml
=> [CI] Fix windows CI

.CurrentChangelog.md, Changelog.md
=> [Changelog] Update the changelog for the 0.10.0-alpha.2 pre-release.

lib/aot/CMakeLists.txt, lib/aot/compiler.cpp
=> [AOT] Upgrade to llvm 14

.github/workflows/IWYU_scan.yml
Upgrades IWYU on Linux to support llvm-14
=> [Chore] Update IWYU to 0.18 to support LLVM 14

utils/uninstall.sh
* Ref: https://github.com/WasmEdge/WasmEdge/issues/1470
=> [utils] Uninstaller: don't exit on missing env file

docs/book/zh/src/dev/python.md
tranlaste 
docs/book/en/src/dev/python.md
to 
docs/book/zh/src/dev/python.md
=> [docs] add Chinese python dev doc

docs/book/en/src/extend/build_on_windows.md
Updates instructions to use LLVM 13.0.1
=> [Docs] Update the build instructions for Windows

.github/workflows/test-install-script.yml, utils/install.sh
Installer Script: Tweak sort version sort for better semantic soring
* Fix https://github.com/WasmEdge/WasmEdge/issues/1501
=> [utils] Fix https://github.com/WasmEdge/WasmEdge/issues/1501

docs/book/en/src/dev/rust/wasinn.md
Add documentation for WASI-NN's OpenVINO backend.
=> [Docs] add doc for wasi-nn

lib/host/wasi/inode-linux.cpp, lib/host/wasi/inode-macos.cpp, lib/host/wasi/inode-win.cpp, test/host/socket/wasi_socket.cpp
=> [Socket] Fix IPv6 connect

include/host/wasi/environ.h, include/host/wasi/inode.h, include/host/wasi/vinode.h, lib/host/wasi/inode-linux.cpp, lib/host/wasi/inode-macos.cpp, lib/host/wasi/inode-win.cpp
=> [WASI] provide a helper function to get the native handler

.github/workflows/build.yml, .github/workflows/release.yml
=> [CI] Remove the wasmedge_process on Darwin in CI.

.github/scripts/clang-format.sh, .github/workflows/IWYU_scan.yml, .github/workflows/bindings-rust.yml, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/inventory.yml, .github/workflows/linter.yml, .github/workflows/static-code-analysis.yml, examples/embed_cxx/script/fibonacci.cpp
=> [CI] Use paths to disable unnecessary workflows

utils/install.sh
=> [Installer] Update the descriptions in installer.

bindings/rust/wasmedge-sdk/src/instance.rs
In this PR, three new APIs are implemented:
- WasiInstance
- initialize
- exit_code
- WasmEdgeProcessInstance
- initialize
=> [Rust] Implemented new APIs for WasiInstance and WasmEdgeProcessInstance

rpm/wasmedge.spec.in
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>
@dm4 @hydai PTAL.
=> [RPM] Update Spec file

lib/api/CMakeLists.txt
=> [API] Fix LLVM 14 library issue when building static library

docs/book/en/src/SUMMARY.md
=> [Docs] Sorry typo in the ToC

.CurrentChangelog.md, Changelog.md, docs/book/en/src/intro/standard.md, test/spec/CMakeLists.txt
=> [Changelog] Update the changelog for the 0.10.1-alpha.1 pre-release.

.github/workflows/release.yml
=> [CI] Fix the release CI of WASI-NN.

lib/executor/instantiate/function.cpp
* check the first item and dispatch to different loops
Signed-off-by: eat4toast <shihaohang@outlook.com>
=> [Feat] Fix extra branch in addfunc

.CurrentChangelog.md, Changelog.md
=> [Changelog] Update the changelog for the 0.10.1-alpha.2 pre-release.

.github/workflows/release.yml
=> [CI] Fix the WASI-NN release CI.

.github/workflows/release.yml
=> [CI] Upload from artifect for manylinux2014 to prevent from ECONNRESET

test/api/APIUnitTest.cpp, test/api/CMakeLists.txt
=> [Test] Fix the API unit test error of wasmedge_process on non-Linux

.github/workflows/IWYU_scan.yml, .github/workflows/build.yml, .github/workflows/release-published.yml, .github/workflows/release.yml, utils/docker/Dockerfile.release
- Build release images using DockerSlim 
- Push release images to DockerHub
- Split to PR #1630
=> [Docker] Release DockerSlim images

.github/workflows/mdbook.yml, docs/book/en/theme/css/general.css, docs/book/en/theme/css/variables.css, docs/book/zh-TW/theme/css/general.css, docs/book/zh-TW/theme/css/variables.css, docs/book/zh/theme/css/general.css, docs/book/zh/theme/css/variables.css
=> [Docs] Fix the CSS for extend the book page content width on widened

include/runtime/instance/module.h
=> [Runtime] Fix the name of template.

cmake/Helper.cmake, include/api/wasmedge/wasmedge.h, include/vm/vm.h, lib/api/wasmedge.cpp, test/api/APIUnitTest.cpp, test/api/hostfunc_c.c
=> Export the loader, validater, and executor components in VM  context.

docs/book/en/src/SUMMARY.md, docs/book/en/src/dev/rust.md
=> [Docs] Add missing link to wasi-nn

.CurrentChangelog.md, Changelog.md
=> [Changelog] Update the changelog for the 0.10.1-alpha.3 pre-release.

.github/workflows/bindings-rust.yml, bindings/rust/wasmedge-sdk/src/import.rs, bindings/rust/wasmedge-sdk/src/lib.rs, bindings/rust/wasmedge-sys/src/config.rs, bindings/rust/wasmedge-sys/src/instance/module.rs, bindings/rust/wasmedge-sys/src/lib.rs, bindings/rust/wasmedge-sys/src/types.rs, bindings/rust/wasmedge-sys/src/utils.rs, bindings/rust/wasmedge-sys/src/vm.rs, bindings/rust/wasmedge-types/src/error.rs, bindings/rust/wasmedge-types/src/lib.rs
In this PR, the `build-windows` job is refactored to fix the known issues.
- Fixed #1527 
- Fixed #1504 
- Fixed #1500
=> [CI] Fixed the issues in bindings-rust workflow for the Windows platform

.github/workflows/release.yml
=> [CI] Fix the release CI of plugins.

.github/workflows/release.yml
=> [CI] Fix the release package path of wasi-nn.

.github/workflows/release.yml
=> [CI] Fix the release build of wasi-crypto.

bindings/rust/wasmedge-sdk/README.md, bindings/rust/wasmedge-sdk/src/lib.rs, bindings/rust/wasmedge-sys/README.md, bindings/rust/wasmedge-sys/src/lib.rs, docs/book/en/src/embed/rust.md
In this PR, the API docs of Rust bindings and the rust section of WasmEdge Book are updated.
=> [Rust] Updated API docs and the Rust section of WasmEdge Book 

lib/driver/compiler.cpp, lib/driver/tool.cpp
=> [Driver] Fix the lost threads proposal option in tools.

bindings/rust/wasmedge-sdk/src/config.rs, bindings/rust/wasmedge-sys/src/config.rs
Signed-off-by: Xin Liu <sam@secondstate.io>
=> [Rust] Supported MultiMemories config option.

.github/workflows/build-extensions.yml, .github/workflows/build.yml, .github/workflows/release.yml
=> [CI] Upload the extension artifect and drop macos-10.15.

.CurrentChangelog.md, Changelog.md
=> [Changelog] Update the changelog for the 0.10.1 release.

docs/book/en/src/start/docker.md
- Add documents about docker release images from PR #1627
- Merge after `0.10.1` released
=> [Docs] Add documents about docker release images

docs/book/en/src/dev/js/es6.md, docs/book/en/src/dev/js/networking.md, docs/book/en/src/dev/js/nodejs.md, docs/book/en/src/dev/js/npm.md, docs/book/en/src/dev/js/quickstart.md, docs/book/en/src/dev/js/ssr.md, docs/book/en/src/dev/js/tensorflow.md
=> Simplify the developer experience

docs/book/en/theme/css/general.css, docs/book/zh-TW/theme/css/general.css, docs/book/zh/theme/css/general.css
=> [Docs] Fix the content width for fitting the small screens.

lib/aot/compiler.cpp
=> [AOT] Add a mask on shift operands

.github/workflows/README.md, .github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/reusable-build-on-android.yml, .github/workflows/reusable-build-on-fedora.yml, .github/workflows/reusable-build-on-macos.yml, .github/workflows/reusable-build-on-manylinux.yml, .github/workflows/reusable-build-on-windows.yml, .github/workflows/reusable-build-srpm.yml, .github/workflows/reusable-create-source-tarball.yml
=> [CI] Reduce duplicates in build.yml and release.yml

lib/loader/ast/instruction.cpp, test/spec/CMakeLists.txt
=> [Loader] Fix for the binary format change in multi-memory proposal.

.github/scripts/wasmedge.wxs
=> [CI] Fix lost file when packaging on Windows.

.github/workflows/build-extensions.yml, plugins/wasi_nn/CMakeLists.txt, plugins/wasi_nn/wasinnenv.h, plugins/wasi_nn/wasinnfunc.cpp, test/plugins/wasi_nn/CMakeLists.txt, test/plugins/wasi_nn/wasi_nn.cpp, utils/wasi-nn/download-pytorch-fixtures.sh, utils/wasi-nn/install-pytorch.sh
Enable pytorch backend in the Wasi-NN plugin.
=> [WASINN] Support PyTorch Backend

examples/wasm/README.md
fix hello.wasm output 
closes:#1762
=> fix hello.wasm output

bindings/rust/wasmedge-sys/src/utils.rs, include/api/wasmedge/wasmedge.h, include/vm/async.h, include/vm/vm.h, lib/api/wasmedge.cpp, test/api/APIUnitTest.cpp
=> [API] Add the const qualifer for some APIs.

.CurrentChangelog.md, Changelog.md, test/spec/CMakeLists.txt
=> [Changelog] Update the changelog for the 0.11.0-alpha.1 pre-release.

.github/workflows/release.yml
=> [CI] Fix the release CI.

.github/workflows/reusable-build-on-macos.yml, CMakeLists.txt, docs/book/en/src/extend/build.md
=> [CMake] Add warning of statically link the tools.

docs/book/zh-TW/src/os.md
I translated /docs/book/en/src/os.md into zh-TW. Please check.
Signed-off-by: Cheng-En Lee <chengenl@usc.edu>
=> DOCs-zh-TW:Translate /docs/book/en/src/os.md into zh-TW

docs/book/en/src/SUMMARY.md, docs/book/en/src/embed/c/0.10.1/ref.md, docs/book/en/src/embed/c/0.10.1/upgrade_to_0.11.0.md, docs/book/en/src/embed/c/0.9.1/upgrade_to_0.10.0.md, docs/book/en/src/embed/c/ref.md, docs/book/en/src/embed/go/0.9.1/upgrade_to_0.10.0.md
=> [Docs] Update API docs to 0.11.0.

.CurrentChangelog.md, Changelog.md
=> [Changelog] Update the changelog for the 0.11.0-rc.1 pre-release.

.github/workflows/build-extensions.yml, .github/workflows/reusable-build-on-macos.yml, cmake/Helper.cmake
=> [CI] Link system libc++ instead of brew llvm on MacOS

.CurrentChangelog.md, Changelog.md, docs/book/en/src/embed/c/ref.md
=> [Changelog] Update the changelog for the 0.11.0 release.

.github/workflows/mdbook.yml
=> [CI] Use slim markdown linter

docs/book/en/src/SUMMARY.md
=> [Docs] fix book toc

lib/aot/compiler.cpp
Signed-off-by: hydai <z54981220@gmail.com>
=> [AOT] Support LLVM 15

CMakeLists.txt, cmake/Helper.cmake, include/driver/fuzzPO.h, include/driver/fuzzTool.h, include/loader/loader.h, include/po/argument_parser.h, lib/api/wasmedge.cpp, lib/driver/CMakeLists.txt, lib/driver/compilerTool.cpp, lib/driver/fuzzPO.cpp, lib/driver/fuzzTool.cpp, lib/driver/runtimeTool.cpp, lib/loader/ast/instruction.cpp, lib/loader/ast/module.cpp, lib/loader/ast/section.cpp, lib/loader/ast/segment.cpp, lib/loader/ast/type.cpp, lib/loader/loader.cpp, lib/loader/shared_library.cpp, lib/po/argument_parser.cpp, test/po/help.cpp, test/po/po.cpp, test/po/subcommand.cpp, tools/CMakeLists.txt, tools/fuzz/CMakeLists.txt, tools/fuzz/po.cpp, tools/fuzz/tool.cpp
* Reject None type in function type definitions
* Reject unreasonable long vector sizes
* Add output file option for redirecting output to a file
* Use `fmt::print` for output
=> Add fuzzing test

.github/workflows/inventory.yml, bindings/rust/wasmedge-sdk/examples/create_host_func_in_host_func.rs, bindings/rust/wasmedge-sys/src/instance/function.rs, bindings/rust/wasmedge-sys/src/lib.rs, bindings/rust/wasmedge-types/src/error.rs
In this PR, we refactor the original design of the host function storage so that some potential deadlock issues caused by the read/write contention can be solved entirely.
- Fixed #1813
=> [Rust] Fixed the potential deadlock issue.

.CurrentChangelog.md, Changelog.md
=> [Changelog] Update the changelog for the 0.11.1-rc.1 pre-release.

.github/workflows/reusable-build-on-macos.yml
=> [CI] Use LLVM-14 for the MacOS release.

.github/workflows/build.yml, .github/workflows/release.yml
=> [CI] Statically link LLVM on ubuntu 20.04 with clang++

.github/workflows/release.yml
=> [CI] Add httpsreq plugin into release assets

.github/workflows/build-extensions.yml, .github/workflows/release.yml, docs/book/en/src/SUMMARY.md, docs/book/en/src/cli/wasmedgec.md, docs/book/en/src/contribute/build_from_src.md, docs/book/en/src/contribute/build_from_src/plugin_wasi_crypto.md, docs/book/en/src/contribute/build_from_src/plugin_wasi_nn.md, docs/book/en/src/contribute/build_from_src/plugin_wasmedge_httpsreq.md, docs/book/en/src/features/proposals.md, docs/book/en/src/plugin.md, docs/book/en/src/write_wasm/rust/networking-https.md, docs/book/en/src/write_wasm/rust/networking.md, docs/book/en/src/write_wasm/rust/wasicrypto.md, docs/book/en/src/write_wasm/rust/wasinn.md, docs/book/zh/src/dev/rust/networking-https.md
=> [Docs] Update the plugin release status.

.github/workflows/release.yml
=> [CI] Fix ubuntu release CI

.github/workflows/rust-wasmedge-macro-docs.yml, .github/workflows/rust-wasmedge-macro-release.yml, bindings/rust/wasmedge-macro/Cargo.toml, bindings/rust/wasmedge-macro/README.md, bindings/rust/wasmedge-macro/src/lib.rs
In this PR, `wasmedge-macro v0.1.0` is ready to release. The tag for this release is `rust-macro/0.1.0`.
=> [Rust] wasmedge-macro v0.1.0

docs/book/en/src/sdk/c/0.10.1/ref.md, docs/book/en/src/sdk/c/ref.md, docs/book/en/src/sdk/go/0.10.1/ref.md, docs/book/en/src/sdk/go/0.10.1/upgrade_to_0.11.0.md, docs/book/en/src/sdk/go/ref.md
=> [Docs] Update the WasmEdge-Go doc to 0.11.0.

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/reusable-build-on-macos.yml, .github/workflows/reusable-build-on-ubuntu.yml
=> [CI] Fix the LLVM on MacOS 12

bindings/rust/wasmedge-sdk/README.md, bindings/rust/wasmedge-sdk/src/lib.rs, bindings/rust/wasmedge-sys/README.md, bindings/rust/wasmedge-sys/examples/mdbook_example_module_instance.rs, bindings/rust/wasmedge-sys/src/lib.rs, docs/book/en/src/sdk/rust.md, docs/book/en/src/sdk/rust/concurrent_fib.md, docs/book/en/src/sdk/rust/how_to_use_module_instance.md, docs/book/en/src/sdk/rust/memory_manipulation.md, docs/book/en/src/sdk/rust/say_hello.md, docs/book/en/src/sdk/rust/sys_run_host_func.md, docs/book/en/src/sdk/rust/table_and_funcref.md
In this PR, the example files related to Rust SDK are updated.
=> [mdbook] Updated Rust SDK related files.

lib/api/CMakeLists.txt, lib/api/libwasmedge.lds
=> [API] Add linker script to hide local symbols

.github/workflows/IWYU_scan.yml
=> [CI] Fix IWYU on MacOS.

.github/dependabot.yml
=> [CI] Enable dependabot

docs/book/en/src/contribute/build_from_src/plugin_wasi_nn.md, docs/book/en/src/write_wasm/rust/wasinn.md
=> [Docs] Fix wrong typo of commands in OpenVINO installation.

.github/workflows/test-install-script.yml, utils/install.sh
=> [Utils] Installer CI: Change debug option

.github/workflows/IWYU_scan.yml, .github/workflows/build-extensions.yml, .github/workflows/build.yml, .github/workflows/build_for_openwrt.yml, .github/workflows/test-install-script.yml, .github/workflows/witx.yml
=> [CI] Refine workflow name

.github/workflows/bindings-rust.yml, bindings/rust/wasmedge-sdk/src/config.rs, bindings/rust/wasmedge-sdk/src/externals/memory.rs, bindings/rust/wasmedge-sys/src/config.rs
In this PR, new APIs are introduced into `Memory` and `Config`. In addition, the `bindings-rust` workflow is refactored.
=> [Rust] Implemented new APIs for Memory and Config.

lib/executor/instantiate/import.cpp
=> [Executor] Add additional import hint message when instantiation failed.

.github/workflows/README.md, .github/workflows/build-extensions.yml, .github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/test-install-script.yml
=> [CI] Use the linux-arm64 runner instead of the ARM64 runner

.github/workflows/release.yml
=> [CI] Fix the host runner of releasing plug-in.

lib/loader/ast/module.cpp, lib/loader/ast/section.cpp
=> [Loader] Downgrade the log level from error to info if the AOT section is not correct and fallback to the interpreter mode

CMakeLists.txt, utils/ohos/configuration/CMakeLists.txt
=> [Misc] Change minimum required cmake from 3.9.4 to 3.10.2

.github/workflows/bindings-java.yml
=> [CI] Trigger bindings-java workflow only when the related files are modified

.github/workflows/release.yml
=> [CI] Release the WASI-NN TFLite backend for ubuntu.

cmake/Helper.cmake
=> [Fuzz] Remove sanitizer flag for oss-fuzz build

lib/plugin/plugin.cpp
=> [Plugin] Use the library path to load the default plug-in path.

.CurrentChangelog.md, Changelog.md, docs/book/en/src/sdk/c.md, docs/book/en/src/sdk/go.md, docs/book/en/src/sdk/go/ref.md, docs/book/en/src/write_wasm/rust/wasinn.md
=> [Changelog] Update the changelog for the 0.11.2-rc.2 pre-release.

.CurrentChangelog.md, Changelog.md
=> [Changelog] Update changelog for 0.11.2-rc.3

docs/book/en/src/sdk/c/ref.md
Signed-off-by: dm4 <dm4@secondstate.io>
=> [Docs] Update SOVERSION in the document

.github/workflows/rust-wasmedge-macro-release.yml, .github/workflows/rust-wasmedge-sdk-release.yml, .github/workflows/rust-wasmedge-sys-release.yml, .github/workflows/rust-wasmedge-types-release.yml
Signed-off-by: Xin Liu <sam@secondstate.io>
=> [CI] refactor release workflows for Rust bindings

docs/book/en/src/SUMMARY.md
=> [Docs] Fix the lost link of wish_list.

test/spec/CMakeLists.txt
=> [Test] Fix the header not found if re-run cmake.

lib/api/CMakeLists.txt
=> [CMake] Support using libtool to archive static libs.

bindings/rust/wasmedge-sdk/src/executor.rs
related to #2075
Co-authored-by: dm4 <dm4@users.noreply.github.com>
Signed-off-by: Lîm Tsú-thuàn <dannypsnl@secondstate.io>
=> [Rust] Add `From<sys::Executor>` for `Executor`

lib/loader/ast/instruction.cpp
=> [Loader] Fix the detection of code segment boundary.

.github/workflows/IWYU_scan.yml
=> [CI] Bump IWYU to 0.19 for using LLVM 15

.github/workflows/bindings-rust.yml, bindings/rust/wasmedge-sdk/Cargo.toml, bindings/rust/wasmedge-sdk/examples/run_func_in_aot_mode.rs, bindings/rust/wasmedge-sdk/examples/work_in_parallel.rs, bindings/rust/wasmedge-sdk/src/compiler.rs, bindings/rust/wasmedge-sdk/src/config.rs, bindings/rust/wasmedge-sdk/src/module.rs, bindings/rust/wasmedge-sdk/src/store.rs, bindings/rust/wasmedge-sdk/src/vm.rs, bindings/rust/wasmedge-sys/Cargo.toml, bindings/rust/wasmedge-sys/examples/func_call_across_different_modes.rs, bindings/rust/wasmedge-sys/src/config.rs, bindings/rust/wasmedge-sys/tests/test_aot.rs
In this PR, the default features in `wasmedge-sdk` and `wasmedge-sys` are updated.
=> [Rust] Update default features

.github/workflows/rust-wasmedge-macro-release.yml, .github/workflows/rust-wasmedge-types-release.yml
In this PR, the release workflows for `wasmedge-macro` and `wasmedge-types` are updated.
=> [CI] Refactor the release workflows

plugins/wasi_nn/wasinnenv.h, plugins/wasi_nn/wasinnfunc.cpp
=> [Plugin] Fix the wasi_nn::TensorType from u32 to u8.

docs/book/en/src/SUMMARY.md, docs/book/en/src/cli.md, docs/book/en/src/plugin.md, docs/book/en/src/use_cases.md
Signed-off-by: RRobot-lm <RRobot-lm@users.noreply.github.com>
=> [Docs] fix various typo

docs/book/en/src/sdk/go/memory.md
Update for this https://github.com/WasmEdge/WasmEdge/issues/2156.
Return string with pointer and length in the wasm.
Signed-off-by: DarumaDocker <DarumaDocker@gmail.com>
=> [Docs] Update tinygo memory management

test/host/wasi/wasi.cpp
It may fix #1909.
Signed-off-by: Harry Chiang <harry900831@gmail.com>
=> [MISC] Sleep to prevent from the dalay of socket send

flake.lock, flake.nix
Signed-off-by: Rafael Fernández López <rfernandezl@vmware.com>
=> nix flake: fix wasmedge build

utils/install.py
@hydai  these are the changes I made to your PR.
Thanks
=> [Utils] Python Installer: Add ldconfig

.github/workflows/bindings-rust.yml
=> [CI] Not to test WasmEdge in rust binding.

test/spec/CMakeLists.txt
=> [Test] Change to use the 0.12.0 tag for the spec tests.

.github/workflows/release.yml, .github/workflows/reusable-build-on-manylinux.yml, .github/workflows/reusable-build-on-ubuntu.yml
=> [CI] Fix the job title in release CI.

.github/workflows/test-install-script.yml, .github/workflows/test-python-install-script.yml, utils/install.py
- Reference: https://github.com/WasmEdge/WasmEdge/issues/2180
=> [Utils] Installer Improvements and Fixes

bindings/rust/wasmedge-sdk/src/module.rs, bindings/rust/wasmedge-sdk/src/vm.rs, bindings/rust/wasmedge-sys/src/loader.rs, bindings/rust/wasmedge-sys/src/vm.rs
=> [Rust] Fix issue 2189

.github/workflows/test-install-script.yml, .github/workflows/test-python-install-script.yml, utils/install.py
- CI should fail when a .bashrc is generated. Instead it reports both pass and fail and does not exit
=> [Utils] Installer and CI: fixes and improvements

docs/book/en/src/features/proprietary_extend.md
=> [Docs] Add the WasmEdge extension description.

.github/workflows/test-install-script.yml, .github/workflows/test-python-install-script.yml, utils/install.py
- [PARTIAL] https://github.com/WasmEdge/WasmEdge/issues/2196
- [PARTIAL] https://github.com/WasmEdge/WasmEdge/issues/2193
=> [Utils] Installer: Improvements for plugin and platform specific package management

plugins/wasi_crypto/signatures/rsa.cpp
#2210 
Signed-off-by: Puelloc <shentukeqin@hotmail.com>
=> fix: wasi-crypto keypair import read pem as pkcs8

plugins/wasi_crypto/signatures/rsa.cpp
#2212 
Signed-off-by: Puelloc <shentukeqin@hotmail.com>
=> fix: wasi-crypto keypair_generate for rsa-pss

docs/book/en/src/write_wasm/rust/networking-https.md, docs/book/en/src/write_wasm/rust/wasicrypto.md, docs/book/en/src/write_wasm/rust/wasinn.md
=> [Docs] Update the installation of plugins to use the installer.

.github/workflows/build_for_openwrt.yml
Fix the `build_for_openwrt.yml`.
=> [CI]Fix the error of installing packages when building Openwrt.

lib/host/wasi/inode-linux.cpp, lib/host/wasi/inode-macos.cpp
=> [MISC] Fix symlink lookup at path_filestat_set_times

docs/book/en/src/SUMMARY.md, docs/book/en/src/contribute/installer.md
=> [Docs] Add installer guide

lib/host/wasi/inode-linux.cpp, lib/host/wasi/inode-macos.cpp
In order to pass this [test](https://github.com/WebAssembly/wasi-testsuite/blob/prod/testsuite-base/tests/rust/src/bin/fd_filestat_get.rs).
=> [WASI] Set filestat of special fd to 0

.github/workflows/mdbook.yml, docs/book/en/src/SUMMARY.md, docs/book/en/src/sdk/c.md, docs/book/en/src/sdk/c/multimodule.md
=> [Docs] Add the docs to execute with multiple modules.

docs/book/en/src/use_cases/kubernetes/kubernetes/kubeedge.md, docs/book/zh/src/kubernetes/kubernetes/kubeedge.md
=> [Docs] Migrate from k8s.gcr.io to registry.k8s.io.

.github/workflows/release.yml
=> [CI] Rename docker-slim.

lib/plugin/plugin.cpp
=> [Plugin] Fix the C API plugin register failed.

.github/workflows/bindings-rust.yml, .github/workflows/rust-wasmedge-sdk-release.yml, .github/workflows/rust-wasmedge-sys-release.yml, bindings/rust/wasmedge-sdk/Cargo.toml, bindings/rust/wasmedge-sdk/src/import.rs, bindings/rust/wasmedge-sdk/src/plugin.rs, bindings/rust/wasmedge-sys/src/instance/module.rs, bindings/rust/wasmedge-sys/src/plugin.rs, bindings/rust/wasmedge-types/src/error.rs
In this PR, new plugin data structures are implemented to support the relevant C-API.
=> [Rust] Implement plugin data structures

bindings/rust/wasmedge-sys/examples/func_call_across_different_modes.rs, bindings/rust/wasmedge-sys/examples/store_get_named_module.rs, bindings/rust/wasmedge-sys/examples/threads.rs, bindings/rust/wasmedge-sys/src/executor.rs
This PR is to fix the memory leak issue reported in #2370.
=> [Rust] Fix the memory leak issue

include/executor/executor.h, include/vm/async.h, include/vm/vm.h, lib/executor/helper.cpp, test/executor/ExecutorTest.cpp
* Add test for multiple VM instance
=> [VM] Allow two VM instance create in one thread

.github/scripts/wasi-testsuite-adapter.py, .github/workflows/wasi-testsuite.yml
This should be merge after fixing all the issues inside #2249.
I'm new to GitHub Action. If there's any suggestion, please let me know.
Thanks!
=> Add wasi-testsuite to CI

lib/aot/compiler.cpp, lib/aot/llvm.h
* Change enumerate attributes value to zero
* Change import helper function to private linkage to hide symbols
* Detect OS version
=> [AOT] Fix AOT Error on MacOS, fix #2427

bindings/rust/wasmedge-sys/README.md, bindings/rust/wasmedge-sys/build.rs
In this PR, the config related to the `standalone` mode has been updated for the coming release.
=> [Rust] Update standalone config

.github/workflows/rust-wasmedge-macro-release.yml, .github/workflows/rust-wasmedge-types-release.yml
In this PR, the release workflows of `wasmedge-types` and `wasmedge-macro` are updated.
=> [CI] Update crate release workflows

.github/workflows/rust-wasmedge-macro-release.yml, .github/workflows/rust-wasmedge-sdk-release.yml, .github/workflows/rust-wasmedge-sys-release.yml, .github/workflows/rust-wasmedge-types-release.yml
In this PR, update the cargo registry tokens in the release workflows.
=> [CI] Update cargo tokens in the crates release workflows

.github/workflows/rust-wasmedge-macro-release.yml, .github/workflows/rust-wasmedge-sdk-release.yml, .github/workflows/rust-wasmedge-sys-release.yml, .github/workflows/rust-wasmedge-types-release.yml
In this PR, the crates' release workflows are updated.
=> [CI] Update crates release workflows

bindings/rust/wasmedge-sdk/src/vm.rs
Add an auto-detect mechanism to load plugins into the VM. 
Because I need to set the plugin's path after the VM is built In the runwasi's scenario.
=> [Rust] Add a second phase mechanism to load plugins after the vm has already been built.

.github/workflows/rust-wasmedge-macro-release.yml, .github/workflows/rust-wasmedge-sdk-release.yml, .github/workflows/rust-wasmedge-sys-release.yml, .github/workflows/rust-wasmedge-types-release.yml
In this PR, the issues related to the rustdoc deployment are fixed.
=> [CI] Fix the issues in the rust-sdk release workflows

include/common/enum.inc, include/common/types.h, include/validator/formchecker.h, include/validator/validator.h, lib/driver/runtimeTool.cpp, lib/validator/formchecker.cpp, lib/validator/validator.cpp
=> feat: add support for function reference proposal for validation.

.github/workflows/rust-standalone.yml
In this PR the `rust-standalone` workflow has been updated.
=> [CI] Update rust-standalone workflow

.github/workflows/IWYU_scan.yml, .github/workflows/build-extensions.yml, .github/workflows/build.yml, .github/workflows/docker.yml, .github/workflows/release.yml, .github/workflows/reusable-build-on-ubuntu.yml, .github/workflows/reusable-build-on-windows.yml
=> Fix GitHub CI deprecated warning

.github/workflows/test-install-script.yml, .github/workflows/test-python-install-script.yml, utils/install.py, utils/installer_changes.sh
- Ref https://github.com/WasmEdge/WasmEdge/issues/2488
=> [Utils] Installer: Add deprecated warning for 0.9.x and below

test/api/APIAOTCoreTest.cpp, test/api/APIStepsCoreTest.cpp, test/api/APIVMCoreTest.cpp
=> [Test] Fix the API tests error.

include/host/wasi/environ.h, include/host/wasi/vinode.h, lib/host/wasi/inode-linux.cpp, lib/host/wasi/vinode.cpp, lib/host/wasi/wasifunc.cpp, test/host/wasi/wasi.cpp
* Deny absolute path access
* open directory with `__WASI_OFLAGS_DIRECTORY` flag
=> [WASI] Fix WASI ci test

include/common/enum_ast.hpp, include/common/enum_errcode.hpp, include/common/enum_errinfo.hpp, include/common/enum_types.hpp, include/common/errcode.h, include/common/errinfo.h, include/common/log.h, include/host/wasi/error.h, lib/common/CMakeLists.txt, lib/common/errinfo.cpp, plugins/wasi_nn/wasinnfunc.cpp, test/errinfo/errinfoTest.cpp
* Replace all `std::ostream` usage to `fmt::format`
=> Upgrade spdlog to v1.11.0

.gitignore, flake.lock, flake.nix
1. `nix build` generates `result/bin/wasmedge`
2. `nix develop` open shell with supportings
=> fix nix flake, build executable `wasmedge`

lib/loader/filemgr.cpp
=> [Loader] Fix the undefined behavior when decoding signed LEB128.

lib/validator/formchecker.cpp
=> [Validator] Fix the undefined behavior in validating expressions.

.github/workflows/build_for_riscv.yml, .github/workflows/reusable-build-on-macos.yml, include/po/argument_parser.h, lib/driver/uniTool.cpp, lib/po/argument_parser.cpp, test/po/help.cpp
=> [CI] update for unified tool

examples/plugin/get-string/getstring.cpp
fix compile error for plugin/get-string/getstring.cpp
=> fix function params in plugin/get-string/getstring.cpp

plugins/wasi_nn/torch.cpp
=> [Plugin] Fix the incorrect function signature of internal WASI-NN

docs/book/en/src/quick_start/install.md
Hopefully footnotes will be properly rendered!
=> More docs for MacOS installation - #2568

include/common/types.h, include/runtime/instance/table.h, lib/api/wasmedge.cpp, lib/common/errinfo.cpp, lib/executor/engine/controlInstr.cpp, lib/executor/engine/engine.cpp, lib/executor/engine/proxy.cpp, lib/executor/engine/tableInstr.cpp, lib/executor/instantiate/elem.cpp, test/errinfo/errinfoTest.cpp, test/spec/spectest.cpp
=> refactor: unify all reference value to RefVariant

lib/vm/vm.cpp
As mentioned in [discussion#2548](https://github.com/WasmEdge/WasmEdge/discussions/2548)
=> [Misc] Fix debug log empty messages

docs/book/en/src/use_cases/kubernetes/kubernetes/kubernetes-containerd.md, docs/book/zh/src/kubernetes/kubernetes/kubernetes-containerd.md
Fix incorrect containerd unix sock
=> [Docs] fix k8s containerd use case

include/experimental/expected.hpp, test/expected/issues.cpp
* Let `emplace` use inplace nonthrow constructor.
=> [Misc] Add new testcase from https://github.com/TartanLlama/expected/

test/host/wasi/wasi.cpp
* Set ready flag after server socket listening, not binding
=> [WASI] Fix wasi-socket testcase timeout error

.github/CODEOWNERS, docs/OWNER.md
Dear community,
I am nominating a new reviewer for the WasmEdge community, WenYuan Hung (@michael1017). WenYuan has significantly contributed to the community through his work on the WASI-Logging proposal (#2535). I kindly ask for approval from other maintainers. Please leave your comments and decision below. 
Best regards,
hydai
=> [Community] Propose new reviewer, WenYuan Huang, for the WASI-Logging proposal

utils/install.py
Fixes - https://github.com/WasmEdge/WasmEdge/issues/2595
=> [Utils] Installer: Install 20.04 package for any ubuntu version >= 20.04

utils/install.py
- Ref - https://github.com/WasmEdge/WasmEdge/issues/2622
=> [Utils] Installer: Use ubuntu20.04 packages only for x86

utils/install.py, utils/install.sh
=> [Utils] Make Installer uses the correct version on the Ubuntu aarch64 platform

docs/OWNER.md
Dear WasmEdge Community,
It gives me great pleasure to nominate Mr. Shreyas Atre (@SAtacker) for the esteemed position of committer within our WasmEdge community. He has been instrumental in our work thus far, diligently serving as the primary reviewer and contributor for the Installer component. 
His exceptional contributions are evident in his development of the initial bash installer for WasmEdge, launched on September 6, 2021 (#376), followed by his creation of an improved Python installer, which went live on October 18, 2022 (#1914). His profound efforts have significantly eased the user experience by simplifying access to WasmEdge.
Therefore, I kindly invite the other maintainers to review this nomination and share their thoughts or approval. Your input is highly appreciated in …
=> [Community] Nominate Shreyas Atre(@SAtacker) as WasmEdge Committers

.CurrentChangelog.md, Changelog.md
This PR should be merged after #2662 gets merged.
=> [Misc] Update Changelog for the 0.13.2 release

include/host/wasi/environ.h, lib/host/wasi/wasifunc.cpp
Fix PR #2662 so that the unused fds are closed successfully.
=> [WASI] Remove unused fds before closing them.

.github/workflows/build_for_nix.yml
=> [CI] Build wasmedge on Nix

.github/workflows/IWYU_scan.yml, .github/workflows/build-extensions.yml, .github/workflows/build.yml, .github/workflows/build_for_openwrt.yml, .github/workflows/reusable-build-on-macos.yml, .github/workflows/reusable-build-on-manylinux.yml, .github/workflows/reusable-build-on-ubuntu.yml
=> [CI] Clean up the redundant lines all workflows

.github/workflows/build-extensions.yml
=> [CI] use pre-built image to get deps

lib/aot/compiler.cpp
=> [AOT] Fix the neontbl1 codegen error on macOS

plugins/wasi_nn/types.h, plugins/wasi_nn/wasinnenv.cpp, plugins/wasi_nn/wasinnenv.h, plugins/wasi_nn/wasinnfunc.cpp, plugins/wasi_nn/wasinnfunc.h, plugins/wasi_nn/wasinnmodule.cpp
~~Pending wait for https://github.com/bytecodealliance/wasi-nn/pull/87 merged first.~~ Merged.
=> Add load_by_name implementation into wasi-nn plugin

include/runtime/instance/table.h
Fix issue [2744](https://github.com/WasmEdge/WasmEdge/issues/2744)
=> fix issue 2744

include/runtime/instance/memory.h
=> Fixing segmentation fault error 

.github/workflows/test-python-install-script.yml, utils/install.py
- Ref https://github.com/WasmEdge/WasmEdge/issues/2749
=> Fix checking of shell paths

.CurrentChangelog.md, Changelog.md
This is the last PR of the 0.13.4 release. Please merge the other PRs first.
=> [Docs] Update Changelog for the 0.13.4 release

.github/workflows/test-install-script.yml, .github/workflows/test-python-install-script.yml, utils/install.py
We provided WASI-NN ggml plugin from 0.13.4. This PR enables the installer to handle this case.
=> [Installer] Enable WASI-NN ggml plugin

utils/install.py
I will update the WASI-NN ggml plugin on the macOS apple silicon model manually.
=> [Installer] Enable WASI-NN ggml plugin on macOS apple silicon model

LICENSE.spdx, plugins/wasi_nn/ggml.cpp, plugins/wasi_nn/thirdparty/ggml/CMakeLists.txt, plugins/wasi_nn/thirdparty/ggml/common.cpp, plugins/wasi_nn/thirdparty/ggml/common.h, plugins/wasi_nn/thirdparty/ggml/ggml-alloc.c, plugins/wasi_nn/thirdparty/ggml/ggml.c, plugins/wasi_nn/thirdparty/ggml/ggml.h, plugins/wasi_nn/thirdparty/ggml/llama.cpp, plugins/wasi_nn/thirdparty/ggml/llama.h, test/plugins/wasi_nn/CMakeLists.txt
- Support `LLAMA_N_CTX` env for the context size
- Support `LLAMA_N_PREDICT` env for max tokens predicted
- Update ggml backend to b1273
=> [WASI-NN] Support more options for llama

.github/workflows/build-extensions.yml, plugins/wasi_nn/ggml.cpp, plugins/wasi_nn/types.h, plugins/wasi_nn/wasinnenv.cpp
- [WASI-NN] Unified preload options with case-insensitive matching 
- [WASI-NN] Add AUTO device support in ggml backend 
- [WASI-NN] Add STREAM_TO_STDOUT support in ggml backend
=> [WASI-NN] Unified preload options & support streaming to stdout

test/plugins/wasmedge_zlib/wasmedge_zlib.cpp
Changed a few naming style issues on the zlib plugin test source file.
Followup of PR #2562.
To whom it may concern.
@hydai
=> [WASMEDGE-Zlib] Changed a few naming style issues.

plugins/wasi_nn/CMakeLists.txt, plugins/wasi_nn/ggml.cpp, plugins/wasi_nn/ggml.h
- Use `setInput()` with index = 1 for llama.cpp options
- Encode options with JSON string
- Example will update in https://github.com/second-state/WasmEdge-WASINN-examples/pull/52
=> [WASI-NN] Add metadata support

plugins/wasi_nn/ggml.cpp, plugins/wasi_nn/ggml.h, plugins/wasi_nn/thirdparty/ggml/llama.cpp
- `batch-size`
- `reverse-prompt`
- Fix llama log printing
=> [WASI-NN] Support more llama options

.CurrentChangelog.md, Changelog.md
This should be merged after #3004
=> [Docs] Update changelog for 0.13.5 release

.github/workflows/README.md, .github/workflows/build-extensions.yml, .github/workflows/build.yml, .github/workflows/release.yml
This should fix performance issue about macOS CI, and 11 is unsupported via Apple too.
should fix #3013
=> [CI] remove or upgrade macOS 11 to 12

examples/plugin/wasi-logging/Cargo.toml
=> Update Cargo.toml to fix the breaking issue

plugins/wasi_nn/ggml.cpp, plugins/wasi_nn/ggml.h
=> [WASI-NN] ggml: add repeat-penalty and temp

plugins/wasi_nn/CMakeLists.txt, plugins/wasi_nn/ggml.cpp, plugins/wasi_nn/ggml.h
* [WASI-NN] ggml: init repeat-penalty and temp
* [WASI-NN] ggml: do not save llama_context, reset llama_context every time
* [WASI-NN] ggml: update ggml to b1616
=> [WASI-NN] ggml: update ggml to b1614, fix llama context initialization

lib/executor/instantiate/import.cpp
=> [WASI] Fix the function signature matching for WASI imports.

plugins/wasi_nn/ggml.cpp, plugins/wasi_nn/ggml.h
@dm4 
Please check if there is anything I missed or I put too much debug info.
=> [WASI-NN] ggml backend: add more debug log

utils/install.py
- Fixed https://github.com/WasmEdge/WasmEdge/issues/3078
=> [Installer] Fix: Append correct path for ggml metal file

docs/OWNER.md
Dear community,
I am nominating a new reviewer for the WasmEdge community, 王纪开(@am009). He has significantly contributed to the community through his work on [MSVC support](https://github.com/WasmEdge/WasmEdge/pull/2751). I kindly ask for approval from other maintainers. Please leave your comments and decision below.
Best regards,
hydai
=> [Community] Nominate 王纪开(@am009) as WasmEdge Reviewers

utils/install.py
We are going to provide wasi-nn-ggml-blas plugin on ubuntu 20.04.
=> [Installer] Enable ggml-blas plugin

plugins/wasi_nn/CMakeLists.txt, plugins/wasi_nn/ggml.cpp, plugins/wasi_nn/ggml.h, plugins/wasi_nn/types.h, plugins/wasi_nn/wasinnfunc.cpp, plugins/wasi_nn/wasinnfunc.h, plugins/wasi_nn/wasinnmodule.cpp, test/plugins/wasi_nn/wasi_nn.cpp
Related PRs:
- https://github.com/second-state/wasmedge-wasi-nn/pull/4
- https://github.com/WasmEdge/WasmEdge/pull/3119
=> [WASI-NN] ggml: add fini_single and ContextFull error

.github/workflows/release.yml
Tries to fix issue #2975.
Uses third party Github action [https://github.com/marketplace/actions/sbom-generator-action.](url)
I was not able to test it locally and it is first time editing such a huge workflow file, hence it may result in some error.
I would like to request a review , and also request a feedback about how it can be done in a better way.
=> Added Sbom generator action

plugins/wasi_nn/CMakeLists.txt, plugins/wasi_nn/ggml.cpp, plugins/wasi_nn/ggml.h, plugins/wasi_nn/types.h
- Related to https://github.com/WasmEdge/WasmEdge/issues/3130
- Also update ggml to b1743
=> [WASI-NN] ggml: handle prompt too long error

lib/plugin/plugin.cpp
Fixed https://github.com/WasmEdge/WasmEdge/issues/3014
=> Proper initialization of DLInfo

.github/labeler.yml, .github/workflows/labeler.yml
=> [CI] Fix labeler config

plugins/wasi_nn/CMakeLists.txt
Try to update llama.cpp to latest version every Thursday.
=> [WASI-NN] ggml: update ggml to b1808

README-ja.md, README-zh-TW.md, README-zh.md, README.md
I created Japanese translated README.
=> [Docs] Add Japanese README

utils/install.py
Fixes https://github.com/second-state/LlamaEdge/issues/74
=> [Utils] Detect CUDA 12.x via nvidia-smi

plugins/wasi_nn/ggml.cpp, plugins/wasi_nn/ggml.h
=> [WASI-NN] ggml: support top_p and presence_penalty

.github/workflows/IWYU_scan.yml, .github/workflows/bindings-java.yml, .github/workflows/build-extensions.yml, .github/workflows/build.yml, .github/workflows/build_for_riscv.yml, .github/workflows/wasi-testsuite.yml, .github/workflows/winget-submit.yml
For issue #2979 
Permissions for following files added
- IWYU-scan
- build.yml
- build-extensions.yml
- build_for_riscv.yml
- wasi-testsuite.yml
=> permissions added for workflow files

include/ast/module.h, lib/validator/validator.cpp
#3150 should based on these changes.
=> [component model] the least needed validation

plugins/wasi_nn/ggml.cpp, plugins/wasi_nn/ggml.h
=> [WASI-NN] ggml: add experimental embedding support

utils/wasi-nn/install-openvino.sh
=> [Misc] Update the printed messages to match the actual installed version of OpenVINO

cmake/Helper.cmake, lib/aot/CMakeLists.txt, lib/aot/compiler.cpp, lib/aot/llvm.h, lib/executor/helper.cpp
* Change StrictFP value to 0
* Change UWTable value to 2 (UWTable::Default)
* Move ErrCode handling code after try-catch block
* Adjust compile options on windows
=> [AOT] Fix windows build

include/ast/module.h, include/ast/section.h, include/loader/loader.h, lib/loader/ast/component.cpp, lib/loader/ast/section.cpp, lib/validator/validator.cpp
which means these orders have semantic
=> [component model] section order will affect index space

lib/host/wasi/inode-win.cpp
=> [WASI] Ignore NONBLOCK flags on windows, fix #3084

cmake/Helper.cmake
=> [Misc] enable -Wno-deprecated-literal-operator only if clang >= 17.0.0

plugins/wasi_nn/ggml.cpp, plugins/wasi_nn/ggml.h
=> [WASI-NN] ggml: support main-gpu and tensor-split

plugins/wasi_nn/CMakeLists.txt
Related issue: https://github.com/second-state/WasmEdge-WASINN-examples/pull/98
=> [WASI-NN] ggml: bump to b2230 for supporting the gemma model

.github/workflows/reusable-build-on-macos.yml, CMakeLists.txt
=> [Misc] Only build wasi_nn_rpc when WASMEDGE_BUILD_WASI_NN_RPC is ON

utils/docker/Dockerfile.manylinux2014_plugins_deps_x86_64, utils/install.py
=> [Installer] Support WasmEdge rustls plugin installation on the manylinux2014 aarch64

lib/common/CMakeLists.txt
=> [Misc] Upgrade spdlog to 1.13.0

.github/workflows/test-installer-v2.yml, utils/install_v2.sh
=> [Installer] Support a pure bash script installer

examples/plugin/get-string/getstring.cpp
=> [Example] Fix the get-string plugin example.

plugins/wasi_nn/ggml.cpp
This PR updates the `getEmbedding` function to generate the same results as the [embedding example in llama.cpp](https://github.com/ggerganov/llama.cpp/tree/master/examples/embedding).
I have tested it locally to ensure that it generates the same results for the models `llama-2-7b-chat.Q5_K_M.gguf` and `gritlm-7b_q4_1.gguf` as those in `llama.cpp`. I think we should include one of those models in our example CI later to ensure that it executes successfully.
=> [WASI-NN] ggml: fix embedding with batch decode

plugins/wasi_nn/CMakeLists.txt, plugins/wasi_nn/ggml.cpp, plugins/wasi_nn/ggml.h, plugins/wasi_nn/wasinnenv.h, plugins/wasi_nn/wasinnfunc.cpp, plugins/wasi_nn/wasinnfunc.h, plugins/wasi_nn/wasinnmodule.cpp, thirdparty/ggml/ggml.patch
To add `unload()` function to `wasmedge-wasi-nn` and use it in our WasmEdge WASINN examples, we need:
- Merge PR in wasmedge-wasi-nn
- [PR](https://github.com/second-state/wasmedge-wasi-nn/pull/12)
- Merge PR in WasmEdge runtime
- Also bump llama.cpp to b2715
- [PR](https://github.com/WasmEdge/WasmEdge/pull/3350)
- Release the new wasmedge-wasi-nn crate
- Will need to update Cargo.toml and README in another [PR]()
- Update the WasmEdge WASINN examples to use the newer version of wasmedge-wasi-nn crate
- [PR]()
=> [WASI-NN] ggml: add unload function

.github/workflows/IWYU_scan.yml
* Use 0.21 on macos
* Use ninja-build for IWYU build
=> [CI] Update IWYU to 0.22

thirdparty/wasi_crypto/api.hpp
=> chore: fix typos

lib/loader/ast/type.cpp
=> [Loader] Fix heap type syntax checking.

lib/host/wasi/inode-linux.cpp
Fix https://github.com/WasmEdge/WasmEdge/issues/2953
=> [Misc] Fix the return value of fdAllocate

lib/host/wasi/win.h, test/host/wasi/wasi.cpp
=> [Misc] Fix time conversion constant on Windows

include/system/winapi.h, lib/plugin/plugin.cpp
=> [Misc] dladdr for Windows

.github/workflows/dco.yml
See https://github.com/dcoapp/app/issues/211
=> [CI] Use dco-check workflow because the dcobot is stuck

.github/workflows/build.yml, .github/workflows/reusable-build-on-debian.yml, .github/workflows/reusable-build-on-fedora.yml
=> [CI] Use Fedora:rawhide and Debian:testing

utils/install_v2.sh
cc @juntao 
Please check if we prefer this kind of short alias or not.
=> [Installer] v2: Add more short options alias

.github/CODEOWNERS
=> [Misc] Update CODEOWNER based on the current file structures

.github/workflows/test-install-script.yml, .github/workflows/test-python-install-script.yml, utils/install.py
Fixes #3432, #3199
- Ref- https://github.com/WasmEdge/WasmEdge/issues/3432
=> [Utils] Installer:  Deprecate 0.12.x

.github/workflows/build-extensions.yml, .github/workflows/docker.yml, .github/workflows/reusable-build-extensions-on-manylinux.yml, utils/docker/Dockerfile.manylinux_2_28-build-plugins-deps, utils/docker/Dockerfile.manylinux_2_28_aarch64, utils/docker/Dockerfile.manylinux_2_28_x86_64
- Build docker images conditionally with [@dorny/paths-filter](https://github.com/dorny/paths-filter)
- Move all `yum install gh` outside Dockerfile.
- Install `libelf` for wasm_bpf on `manylinux_2_28`.
- Remove `manylinux2014` from workflows to build docker images.
=> [CI] Dockerfile-related changes

.github/actions/expand-variables/dist/index.js, .github/actions/expand-variables/main.js, utils/docker/Dockerfile.manylinux_2_28-build-plugins-deps
Fix #3512 and enable workflows.
=> [CI] Build extensions on manylinux_2_28 x86_64

plugins/CMakeLists.txt, plugins/wasi_llm/CMakeLists.txt, plugins/wasi_llm/types.h, plugins/wasi_llm/wasillmbase.h, plugins/wasi_llm/wasillmfunc.cpp, plugins/wasi_llm/wasillmfunc.h, plugins/wasi_llm/wasillmmodule.cpp, plugins/wasi_llm/wasillmmodule.h
=> [WASI-LLM] Implement wasi_llm module

include/host/wasi/inode.h, include/system/winapi.h, lib/host/wasi/CMakeLists.txt, lib/host/wasi/inode-linux.cpp, lib/host/wasi/inode-macos.cpp, lib/host/wasi/inode-win.cpp, lib/host/wasi/vinode.cpp, lib/host/wasi/wasifunc.cpp, lib/host/wasi/win.h, lib/system/mmap.cpp
* Remove emuration of append flag on pwrite
* Add missing error codes
* Always pass output varable for GetOverlappedResult
* Treat EOF error as recoverable
=> [WASI] Fix wasi-testsuite errors on windows

plugins/wasi_nn/CMakeLists.txt, plugins/wasi_nn/ggml.cpp
- Bump llama.cpp b3445
- Add json-schema suuport
- Add example in [PR](https://github.com/second-state/WasmEdge-WASINN-examples/pull/151)
=> [WASI-NN] ggml: add json-schema suuport and bump llama.cpp b3445

utils/docker/Dockerfile.manylinux_2_28-plugins-deps, utils/wasi-nn/install-onnxruntime.sh
This PR updates the docker image manylinux_2_28-plugins-deps for CI: https://github.com/WasmEdge/WasmEdge/pull/3614.
=> [Docker] install onnxruntime in manylinux_2_28-plugins-deps for WASI-NN Piper CI

plugins/wasmedge_stablediffusion/sd_func.cpp
Fix the result image pointer when writing the PNG file.
=> [Plugin] Stable Diffusion: fix segment fault

.github/workflows/test-installer-v2.yml, .github/workflows/test-python-install-script.yml, utils/install.py, utils/install_v2.sh
=> [Installer] all: ignore wasi-logging plugin installation after 0.14.1-rc.1

lib/loader/filemgr.cpp
=> [Loader] Fix GCC 14 maybe-uninitialized warning

.github/workflows/build-extensions.yml, .github/workflows/matrix-extensions.json, .github/workflows/release.yml, cmake/Helper.cmake
=> [CMake] Set CXX_VISIBILITY_PRESET to hidden. Regression by 0b285f7b

bindings/java/wasmedge-java/build.gradle, bindings/java/wasmedge-java/wasmedge-jni/FindWasmEdge.cmake, bindings/java/wasmedge-java/wasmedge-jni/README.md
1. fix variable misused in `FindWasmEdge.cmake`
2. fix build command in gradle (I'm also surprised that affect the result)
NOTE: since C code unchanged, this will not fix the whole binding, but fundamental work before #3663.
=> [Java] fix some build script problems

utils/install_v2.sh
This fixed https://github.com/moxin-org/moxin/issues/225
=> [Installer] v2: check all possible nvcc location

.github/extensions.paths-filter.yml, .github/workflows/build-extensions.yml, .github/workflows/matrix-extensions.json, .github/workflows/reusable-build-extensions-on-legacy-manylinux.yml, .github/workflows/reusable-build-extensions.yml
This aims to
- Restructure the jobs for easier implementation of #3616.
* Separating workflow for legacy platform make it more flexible to restructure.
Closes #3616
Ubuntu-related parts are moved to #3677
=> [CI] Refactor workflows for plugins for paths-filter

.github/workflows/release.yml
=> [CI] Fix JSON error

plugins/wasi_nn/CMakeLists.txt, plugins/wasi_nn/whispercpp.cpp, plugins/wasi_nn/whispercpp.h
=> [Plugin] Support `translate` and `language` option for WASI-NN whisper backend.

.github/extensions.paths-filter.yml, .github/workflows/matrix-extensions.json, .github/workflows/reusable-build-extensions.yml
=> [CI] Add wasmedge_llmc for manylinux

plugins/wasmedge_llmc/CMakeLists.txt, plugins/wasmedge_llmc/llmc_env.cpp, plugins/wasmedge_llmc/llmc_fwd.h, test/plugins/wasmedge_llmc/CMakeLists.txt
Related #3523 
Depends on https://github.com/WasmEdge/llm.c/pull/5
=> [Plugin] llmc: Support training GPT2 on GPU (CUDA)

plugins/wasi_nn/whispercpp.cpp, plugins/wasi_nn/whispercpp.h
=> [Plugin] WASI-NN Whisper: supporting metadata in set_input.

utils/install_v2.sh
=> [Installer] v2: give a better output for the usage of the --version option

lib/loader/serialize/serial_instruction.cpp, test/loader/serializeInstructionTest.cpp
Signed-off-by: Mohamed Atef <mohamedatef1698@gmail.com>
=> [Loader][Serializer]: Add Function References Instructions and their tests

plugins/wasmedge_stablediffusion/CMakeLists.txt
=> [Plugin] Stable Diffusion: update SD version to 14206fd

lib/llvm/llvm.h
* Remove unused and deprecated llvm-c functions
=> [LLVM] Support LLVM 19

utils/docker/Dockerfile.manylinux2014-build-plugins-deps, utils/docker/Dockerfile.manylinux_2_28-plugins-deps, utils/docker/Dockerfile.ubuntu-plugins-deps, utils/wasi-nn/install-pytorch.sh
=> [Plugin] Update pytorch version to 2.4.1

plugins/wasmedge_stablediffusion/sd_func.cpp, test/plugins/wasmedge_stablediffusion/wasmedge_stablediffusion.cpp
=> [Plugin] Stable Diffusion: fix reuse context segment fault

.github/workflows/reusable-build-on-macos.yml
=> [CI] Use llvm@18 temporary on MacOS.

utils/docker/Dockerfile.manylinux_2_28-plugins-deps
=> [Docker] Disable pytorch c++11 abi on manylinux_2_28

plugins/wasmedge_stablediffusion/sd_env.cpp, plugins/wasmedge_stablediffusion/sd_func.cpp, test/plugins/wasmedge_stablediffusion/wasmedge_stablediffusion.cpp
- Add test for reusing context
- Add test for non exist sessionId
=> [Plugin] Stable Diffusion: add more test

cmake/WASINNDeps.cmake, plugins/wasi_nn/wasinn_ggml.cpp, plugins/wasi_nn/wasinn_ggml.h
- bump llama.cpp b3942
- use new llama sampler and common params
=> [WASI-NN] ggml: bump llama.cpp b3942

docs/self-assessment.md
=> [Docs] fix minor typo

cmake/WASINNDeps.cmake, plugins/wasi_nn/wasinn_whisper.cpp, plugins/wasi_nn/wasinn_whisper.h
=> [WASI-NN] Whisper: fix the token timestamp option.

.github/workflows/static-code-analysis.yml
=> [CI] Bump llvm 11 to 18 for static code analysis

cmake/WASINNDeps.cmake
- No breaking change, use update the version in cmake file.
=> [WASI-NN] ggml: bump llama.cpp b4067

.github/workflows/README.md
List combinations of test and release for each platforms:
- MacOS 13, 14
- manylinux_2_28
- Ubuntu 20.04, 22.04, 24.04
Closes #3847
=> [CI] Update README.md

test/loader/serializeTypeTest.cpp
This PR adds the missing tests for https://github.com/WasmEdge/WasmEdge/pull/3821
Signed-off-by: Mohamed Atef <mohamedatef1698@gmail.com>
=> [Loader] Serializer: Finish GC type tests

.github/workflows/test-install-script.yml, .github/workflows/test-python-install-script.yml, utils/install.py
This PR will allow the old versions use the assets' URL instead.
=> [Installer] v1: update the assets' urls for the 0.13.5 and 0.14.0 ggmlbn

CMakeLists.txt, cmake/WASINNDeps.cmake, plugins/wasi_nn/wasinn_ggml.cpp, plugins/wasi_nn/wasinn_ggml.h
* [WASI-NN] ggml: add the warmup option
* [WASI-NN] ggml: bump llama.cpp b4242
=> [WASI-NN] ggml: bump llama.cpp b4242

utils/docker/Dockerfile.manylinux2014-build-plugins-deps, utils/docker/Dockerfile.manylinux_2_28-plugins-deps, utils/docker/Dockerfile.ubuntu-plugins-deps, utils/wasi-nn/install-pytorch.sh
for https://github.com/WasmEdge/WasmEdge/pull/3724
=> [Plugin] Update pytorch version

CMakeLists.txt, cmake/WASINNDeps.cmake, plugins/wasi_nn/wasinn_ggml.cpp, plugins/wasi_nn/wasinn_ggml.h
* [WASI-NN] ggml: add the warmup option
* [WASI-NN] ggml: bump llama.cpp b4242
* [WASI-NN] ggml: disable warmup by default to match previous behavior
* [WASI-NN] ggml: reload llama context if embedding status changed
* [WASI-NN] bump to 0.1.3
=> [WASI-NN] Update 0.14.1_plugin_lts branch

CMakeLists.txt, cmake/WASINNDeps.cmake, plugins/wasi_nn/wasinn_ggml.cpp
* [WASI-NN] ggml: fix reloading llama context
* [WASI-NN] ggml: bump llama.cpp b4273
* [WASI-NN] bump to 0.1.4
=> [WASI-NN] ggml: fix reloading llama context and bump version

CMakeLists.txt, cmake/WASINNDeps.cmake, plugins/wasi_nn/wasinn_ggml.cpp
* [WASI-NN] ggml: fix reloading llama context
* [WASI-NN] ggml: bump llama.cpp b4273
* [WASI-NN] bump to 0.1.4
=> [WASI-NN] update `0.14.1_plugin_lts` branch

SECURITY.md
- https://github.com/WasmEdge/docs/pull/258
=> [Docs] update supported version to 0.14.1

include/host/mock/wasmedge_stablediffusion_func.h, plugins/wasmedge_stablediffusion/CMakeLists.txt, plugins/wasmedge_stablediffusion/sd_env.cpp, plugins/wasmedge_stablediffusion/sd_func.cpp, plugins/wasmedge_stablediffusion/sd_func.h, test/plugins/wasmedge_stablediffusion/wasmedge_stablediffusion.cpp
=> [Plugin] Stable Diffusion: Upgrade to 9578fdc

cmake/WASINNDeps.cmake, plugins/wasi_nn/wasinn_ggml.cpp, plugins/wasi_nn/wasinn_ggml.h
- Bump llama.cpp b4381
- Support Qwen2VL
- Preserve clip context in Graph
=> [WASI-NN] ggml: support Qwen2VL and bump llama.cpp b4381

CMakeLists.txt
- Update `WASMEDGE_WASI_NN_VERSION`
=> [WASI-NN] bump to 0.1.5

docs/CONTRIBUTING.md, docs/CONTRIBUTOR_LADDER.md, docs/GOVERNANCE.md
1. Re-org the GOVERNANCE.md
2. Add docs/CONTRIBUTOR_LADDER.md
3. Add docs/CONTRIBUTING.md
=> [VOTE before merging] Update the givernance

CMakeLists.txt, cmake/WASINNDeps.cmake, include/host/mock/wasmedge_stablediffusion_func.h, plugins/wasi_nn/wasinn_ggml.cpp, plugins/wasi_nn/wasinn_ggml.h, plugins/wasi_nn/wasinnfunc.cpp, plugins/wasi_nn/wasinnfunc.h, plugins/wasi_nn/wasinnmodule.cpp, plugins/wasmedge_stablediffusion/CMakeLists.txt, plugins/wasmedge_stablediffusion/sd_env.cpp, plugins/wasmedge_stablediffusion/sd_func.cpp, plugins/wasmedge_stablediffusion/sd_func.h, test/plugins/wasmedge_stablediffusion/wasmedge_stablediffusion.cpp
* [WASI-NN] bump to 0.1.5 (#3932)
* [WASI-NN] ggml: support Qwen2VL and bump llama.cpp b4381 (#3930)
* [WASI-NN]: add finalize_execution_context function  (#3917)
* [Plugin] Stable Diffusion: fix build metal failed
* [Plugin] Stable Diffusion: Upgrade to 9578fdc
=> [Plugin] Update `0.14.1_plugin_lts` branch

plugins/wasi_nn/wasinn_chattts.cpp, plugins/wasi_nn/wasinn_chattts.h
As pointed out in https://github.com/WasmEdge/WasmEdge/pull/3936#issuecomment-2563290843, ChatTTS's dependency torch create threads which probably requires the GIL.
If we did not release the GIL, those threads will hang forever.
Calling `Py_Finalize` can shutdown the Python interpreter but it will also release other resources we still want to keep.
This PR:
Call `PyEval_SaveThread` to release the GIL if `Py_Initialize`d.
Added a new class `GIL`.
When constructed, it will ensure holding the GIL by calling `PyGILState_Check`.
When destructed, it will release the GIL if the GIL was acquired previously by calling `PyGILState_Release`.
This class should be used before calling Python/C API.
This class is to avoid the following pattern:
```c++
PyGILState GState = PyGILState_Ensure();
...use the …
```
=> [WASI-NN] ChatTTS: fix GIL problem and do not call Py_Finalize

include/runtime/instance/module.h, lib/executor/coredump.cpp
Fix #3945. The build failed issue of the older version GCC.
=> [Runtime] coredump: fix type convert issue

CMakeLists.txt, cmake/WASINNDeps.cmake, plugins/wasi_nn/wasinn_ggml.cpp, plugins/wasi_nn/wasinn_ggml.h
* [WASI-NN] ggml: bump llama.cpp b4419
* [WASI-NN] ggml: support split-mode option
* [WASI-NN] ggml: support seed option
* [WASI-NN] bump to 0.1.7
=> [WASI-NN] ggml: bump llama.cpp b4419

.github/workflows/matrix-extensions.json, CMakeLists.txt, cmake/WASINNDeps.cmake, include/host/mock/wasmedge_stablediffusion_func.h, plugins/wasi_nn/wasinn_ggml.cpp, plugins/wasi_nn/wasinn_ggml.h, plugins/wasmedge_stablediffusion/CMakeLists.txt, plugins/wasmedge_stablediffusion/sd_env.cpp, plugins/wasmedge_stablediffusion/sd_func.cpp, plugins/wasmedge_stablediffusion/sd_func.h, test/plugins/wasmedge_stablediffusion/wasmedge_stablediffusion.cpp
* [Plugin] Stable Diffusion: upgrade version to dcf91 (#3950)
* [WASI-NN] ggml: bump llama.cpp b4419
* [WASI-NN] ggml: support split-mode option
* [WASI-NN] ggml: support seed option
* [WASI-NN] bump to 0.1.7
=> [Plugin] Update 0.14.1_plugin_lts branch

cmake/Helper.cmake, plugins/wasi_nn/wasinn_ggml.cpp, plugins/wasi_nn/wasinn_ggml.h, plugins/wasmedge_image/CMakeLists.txt
This is the part 1 of mllama implementation in WASI-NN GGML.
=> [WASI-NN] GGML: refine logging. (PART 1)

plugins/wasi_nn/wasinn_chattts.cpp, plugins/wasi_nn/wasinn_chattts.h, plugins/wasi_nn/wasinn_ggml.cpp, plugins/wasi_nn/wasinn_ggml.h, plugins/wasi_nn/wasinn_mlx.cpp, plugins/wasi_nn/wasinn_mlx.h, plugins/wasi_nn/wasinn_neuralspeed.cpp, plugins/wasi_nn/wasinn_neuralspeed.h, plugins/wasi_nn/wasinn_onnx.h, plugins/wasi_nn/wasinn_openvino.cpp, plugins/wasi_nn/wasinn_openvino.h, plugins/wasi_nn/wasinn_piper.cpp, plugins/wasi_nn/wasinn_piper.h, plugins/wasi_nn/wasinn_tf.h, plugins/wasi_nn/wasinn_tfl.cpp, plugins/wasi_nn/wasinn_tfl.h, plugins/wasi_nn/wasinn_torch.cpp, plugins/wasi_nn/wasinn_torch.h, plugins/wasi_nn/wasinn_whisper.cpp, plugins/wasi_nn/wasinn_whisper.h, plugins/wasi_nn/wasinnenv.h, plugins/wasi_nn/wasinnfunc.cpp, test/plugins/wasi_nn/wasi_nn.cpp
This is the part 2 of mllama implementation in WASI-NN GGML.
(base on #3955)
=> [WASI-NN] GGML: add graph and context new/delete management. (PART 2)

cmake/WASINNDeps.cmake, plugins/wasi_nn/wasinn_ggml.cpp
Replaced #3962 
Related llama.cpp PR: https://github.com/ggerganov/llama.cpp/pull/11110/files
=> [WASI-NN] ggml: bump llama.cpp to b4466

CMakeLists.txt, cmake/WASINNDeps.cmake, plugins/wasi_nn/wasinn_ggml.cpp, plugins/wasi_nn/wasinn_ggml.h
- Follow [tts example in llama.cpp](https://github.com/ggerganov/llama.cpp/tree/master/examples/tts) to support text-to-speech.
- Bump WASI-NN version.
=> [WASI-NN] ggml: support text to speech (tts)

CMakeLists.txt, cmake/WASINNDeps.cmake, plugins/wasi_nn/wasinn_ggml.cpp
* [WASI-NN] ggml: check the projection model before loading
* [WASI-NN] ggml: apply clang-tidy
* [WASI-NN] ggml: bump llama.cpp b4681
=> [WASI-NN] ggml: check the projection model before loading 

CMakeLists.txt, cmake/WASINNDeps.cmake, plugins/wasi_nn/wasinn_ggml.cpp
This PR contains:
92897e44 [WASI-NN] bump to 0.1.11
04cdfa12 [WASI-NN] ggml: bump llama.cpp b4681
9ea26974 [WASI-NN] ggml: apply clang-tidy
e3e14d4a [WASI-NN] ggml: check the projection model before loading
=> [Plugin] Update 0.14.1_plugin_lts branch 

plugins/wasi_nn/wasinn_ggml.cpp, plugins/wasi_nn/wasinn_ggml.h
Following #3314 to add the new parameters for llama.cpp version: b4466. In the current implementation, we only parse it from metadata, which is not sure if the parameter indeed works in the ggml.
We skip some parameters the variable type is array or vector.
=> [WASI-NN] ggml: add parameters

test/expected/catch.hpp
This pull request updates the comments in the `catch.hpp` file to improve clarity. Specifically, it adds a comment regarding the normal distribution mean, which enhances the understanding of the code. The changes include:
- Added a comment to clarify the addition of the normal distribution mean (0) in the calculation.
This update aims to make the code more readable and maintainable for future developers.
=> [Misc] fix typo in catch.hpp

.github/workflows/matrix-extensions.json, .github/workflows/reusable-build-extensions-on-linux.yml, .github/workflows/reusable-build-on-ubuntu.yml, cmake/WASINNDeps.cmake, plugins/wasi_nn/CMakeLists.txt, plugins/wasi_nn/wasinn_openvino_genai.cpp, plugins/wasi_nn/wasinn_openvino_genai.h, plugins/wasi_nn/wasinnenv.h, plugins/wasi_nn/wasinntypes.h
Need #4032
* Add openvino genai support (LLMPipeline)
* Load bashrc in CI to build the openvino genai
=> [WASI-NN] Add openvino genai support

plugins/wasi_nn/wasinntypes.h, test/plugins/wasi_nn/wasi_nn.cpp
=> [WASI-NN] Update TensorType Index

utils/docker/Dockerfile.ubuntu-plugins-deps, utils/wasi-nn/install-chattts.sh
This updates the Dockerfile.ubuntu-plugins-deps to install WASI-NN ChatTTS dependencies.
=> [Docker] install ChatTTS in ubuntu-plugins-deps for WASI-NN ChatTTS CI

utils/wasi-nn/install-openvino-genai.sh
Fixes a EOF lint error on the mentioned file
=> refactor: lint install-openvino-genai.sh

include/common/enum.inc, include/validator/context.h, include/validator/validator_component.h, test/component/componentvalidatortest.cpp
Other Change:
- Replaced Correct Wasm tests with `wasm` files for better readability.
Tests:
<details>
<summary>Hello-wasi-http Test (with Debug enabled)</summary>
```
tools/wasmedge/wasmedge --enable-component /home/sridamul/Desktop/open-source/hello-wasi-http/target/wasm32-wasip1/debug/hello_wasi_http.wasm
[2025-04-14 04:18:52.379] [warning] component model is enabled, this is experimental.
[2025-04-14 04:18:52.381] [warning] component model is an experimental proposal
[2025-04-14 04:18:52.402] [warning] Component Model Validation is in active development.
[2025-04-14 04:18:52.402] [debug] Type Section
[2025-04-14 04:18:52.402] [info] Component Index Spaces 0x604cbf370650
[2025-04-14 04:18:52.402] [debug] Type -> 1
[2025-04-14 04:18:52.402] [info] Core Index Spaces 0x604cbf370650 …
```
=> [Component Model] Validate CompInline Exports and sort indices

cmake/WASINNDeps.cmake, plugins/wasi_nn/CMakeLists.txt, plugins/wasi_nn/MLX/mlx/activations.cpp, plugins/wasi_nn/MLX/mlx/base.cpp, plugins/wasi_nn/MLX/mlx/convolution.cpp, plugins/wasi_nn/MLX/mlx/convolution.h, plugins/wasi_nn/MLX/mlx/normalization.cpp, plugins/wasi_nn/MLX/mlx/normalization.h, plugins/wasi_nn/MLX/mlx/pooling.cpp, plugins/wasi_nn/MLX/mlx/pooling.h, plugins/wasi_nn/MLX/mlx/quantized.cpp, plugins/wasi_nn/MLX/model/gemma3/gemma3.cpp, plugins/wasi_nn/MLX/model/gemma3/gemma3.h, plugins/wasi_nn/MLX/model/gemma3/language.cpp, plugins/wasi_nn/MLX/model/gemma3/language.h, plugins/wasi_nn/MLX/model/gemma3/vision.cpp, plugins/wasi_nn/MLX/model/gemma3/vision.h, plugins/wasi_nn/MLX/model/llm/registry.cpp, plugins/wasi_nn/MLX/model/llm/registry.h, plugins/wasi_nn/MLX/model/llm/transformer.cpp, plugins/wasi_nn/MLX/model/llm/transformer.h, plugins/wasi_nn/MLX/model/vlm_base.cpp, plugins/wasi_nn/MLX/model/vlm_base.h, plugins/wasi_nn/MLX/model/vlm_sampling.cpp, plugins/wasi_nn/MLX/model/vlm_sampling.h, plugins/wasi_nn/wasinn_mlx.cpp, plugins/wasi_nn/wasinn_mlx.h
Support gemma3 model for MLX backend of WASI-NN plugin (#4035).
This PR adds the gemma3 model and integrates the LLM and VLM in the MLX backend. 
Currently, the VLM model only supports the non-quantized gemma3 model.
=> [WASI-NN] mlx: Support gemma3 model

cmake/WASINNDeps.cmake, plugins/wasi_nn/wasinn_ggml.cpp, plugins/wasi_nn/wasinn_ggml.h
Because llama.cpp will move clip support to libmtmd (you can refer to <https://github.com/ggml-org/llama.cpp/tree/master/tools/mtmd>), this PR attempts to change the original clip in the ggml plugin to use libmtmd.
=> feat(wasi-nn): use the new libmtmd for multimodal models

CMakeLists.txt, cmake/WASINNDeps.cmake, plugins/wasi_nn/CMakeLists.txt, plugins/wasi_nn/MLX/mlx/activations.cpp, plugins/wasi_nn/MLX/mlx/base.cpp, plugins/wasi_nn/MLX/mlx/convolution.cpp, plugins/wasi_nn/MLX/mlx/convolution.h, plugins/wasi_nn/MLX/mlx/normalization.cpp, plugins/wasi_nn/MLX/mlx/normalization.h, plugins/wasi_nn/MLX/mlx/pooling.cpp, plugins/wasi_nn/MLX/mlx/pooling.h, plugins/wasi_nn/MLX/mlx/quantized.cpp, plugins/wasi_nn/MLX/model/gemma3/gemma3.cpp, plugins/wasi_nn/MLX/model/gemma3/gemma3.h, plugins/wasi_nn/MLX/model/gemma3/language.cpp, plugins/wasi_nn/MLX/model/gemma3/language.h, plugins/wasi_nn/MLX/model/gemma3/vision.cpp, plugins/wasi_nn/MLX/model/gemma3/vision.h, plugins/wasi_nn/MLX/model/llm/registry.cpp, plugins/wasi_nn/MLX/model/llm/registry.h, plugins/wasi_nn/MLX/model/llm/transformer.cpp, plugins/wasi_nn/MLX/model/llm/transformer.h, plugins/wasi_nn/MLX/model/vlm_base.cpp, plugins/wasi_nn/MLX/model/vlm_base.h, plugins/wasi_nn/MLX/model/vlm_sampling.cpp, plugins/wasi_nn/MLX/model/vlm_sampling.h, plugins/wasi_nn/wasinn_ggml.cpp, plugins/wasi_nn/wasinn_ggml.h, plugins/wasi_nn/wasinn_mlx.cpp, plugins/wasi_nn/wasinn_mlx.h
With the following commits:
* d98e230d bump wasi-nn plugin to 0.1.21 (#4113)
* f2a64662 feat(wasi-nn): use the new libmtmd for multimodal models (#4112)
* 7e7e9acb feat(WASI-NN/MLX): support gemma3 for mlx plugin (#4085)
=> feat(plugin): update 0.14.1_plugin_lts branch

include/executor/engine/binary_numeric.ipp
=> fix(executor): pick the first nan value for min and max instructions

include/executor/executor.h, lib/executor/engine/engine.cpp, lib/executor/engine/proxy.cpp, lib/executor/engine/refInstr.cpp, lib/executor/helper.cpp, lib/llvm/compiler.cpp, lib/llvm/llvm.h, lib/loader/ast/section.cpp
=> refactor(compiler): refine aot codes

.github/workflows/commitlint.yml
The event trigger is changed. So the condition should also be modified.
https://github.com/WasmEdge/WasmEdge/actions/runs/15612136226/job/43975391907?pr=4160
=> ci(commitlint): change the condition to pull_request_target

.github/workflows/commitlint.yml
Replace #4175 
Replace #4178 
Replace #4179
=> ci(commitlint): no longer add labels or comments due to the permissions and events issues

.github/workflows/release.yml
fixes: https://github.com/WasmEdge/WasmEdge/issues/4193
trial run: https://github.com/PhantomInTheWire/WasmEdge/actions/runs/15766897704/job/44444967299
generated somb: [sbom.tar.gz](https://github.com/PhantomInTheWire/WasmEdge/releases/download/v0.0.1-test/sbom.tar.gz)
=> ci(sbom): migrate SBOM generation to REST API

.github/workflows/reusable-build-on-macos.yml, cmake/Helper.cmake, lib/llvm/CMakeLists.txt
* Due to brew splits lld from llvm package, we needs a new option for lld path
=> [CI] Add support for llvm19 on macos brew

plugins/wasi_nn/wasinn_ggml.cpp
**Resolves:**
* https://github.com/WasmEdge/WasmEdge/issues/3958
**Changes:**
`n_predict = -1` and `n_predict = -2` now correctly generate tokens during inference.
cc: @apepkuss
=> fix(wasi_nn, ggml):  Empty generation returned if n_predict is -1 or -2

cmake/WASINNDeps.cmake, plugins/wasi_nn/CMakeLists.txt, plugins/wasi_nn/wasinn_ggml.cpp
=> feat(WASI-NN,ggml): bump llama.cpp b5835

cmake/WASINNDeps.cmake, plugins/wasi_nn/CMakeLists.txt, plugins/wasi_nn/wasinn_ggml.cpp, plugins/wasi_nn/wasinn_mlx.cpp, plugins/wasi_nn/wasinn_openvino.cpp, test/plugins/wasi_nn/wasi_nn.cpp
This PR contains:
894a339f
e0dc3ff9
39ef6112
9e1e0c96
bcbbbf26
=> feat(plugin): update the `0.14.1_plugin_lts` branch

.github/scripts/installer-test-helpers.sh, .github/workflows/IWYU_scan.yml, .github/workflows/commitlint.yml, .github/workflows/reusable-build-on-android.yml, .github/workflows/wasi-testsuite.yml, .gitvote.yml, README-zh-TW.md, README-zh.md, README.md, docs/CONTRIBUTOR_LADDER.md, docs/GOVERNANCE.md, docs/self-assessment.md, examples/embed_cxx/script/CMakeLists.txt, examples/plugin/wasi-logging/README.md, examples/plugin/wasi-logging/src/lib.rs, examples/plugin/wasmedge-zlib/README.md, plugins/wasm_bpf/README.md, plugins/wasmedge_ffmpeg/CMakeLists.txt, test/plugins/wasi_crypto/CMakeLists.txt, test/plugins/wasmedge_ffmpeg/CMakeLists.txt, thirdparty/wasi_crypto/api.hpp, utils/android/app/README.md, utils/ohos/README-zh.md, utils/openwrt/configuration/Makefile, utils/uninstall.sh, utils/wasi-cpp-header/crypto_generate.sh
I am calling for a vote because the following files have been changed:
1. docs/CONTRIBUTOR_LADDER.md  
2. docs/GOVERNANCE.md  
3. docs/self-assessment.md  
Although these are only format issues, according to our policy, we still need to vote on them.
cc @ibmibmibm @q82419 @juntao @hydai 
/vote
=> chore(lineguard): apply lineguard for all files

lib/validator/component_validator.cpp, test/component/spectest.cpp
This fix the first test of the Component.
=> fix(validator): correct core module handling

cmake/WASINNDeps.cmake, plugins/wasi_nn/CMakeLists.txt, plugins/wasi_nn/wasinn_ggml.cpp, plugins/wasi_nn/wasinn_ggml.h
- feat(wasi-nn): bump ggml to b6191 and wasi-nn plugin to 0.1.30 
- feat(wasi-nn): remove `llama_context_default_params`, use default `common_params` value.
- support `cpu-moe` and `n-cpu-moe` options.
=> feat(wasi-nn): bump ggml to b6191 and wasi-nn plugin to 0.1.30 

lib/executor/helper.cpp, lib/llvm/codegen.cpp, lib/llvm/compiler.cpp, lib/llvm/llvm.h
* Check iterator is valid before using
* Ignore contents of virtual sections
* Fill correct null reference value, fix #4325
=> Fill correct null reference value

cmake/WASINNDeps.cmake, plugins/wasi_nn/CMakeLists.txt, plugins/wasi_nn/wasinn_ggml.cpp, plugins/wasi_nn/wasinn_ggml.h
This PR contains
6d05dcb3 feat(WASI-NN,ggml): bump llama.cpp b6301, support MiniCPM-V4.5 (#4336)
d19afc86 feat(wasi-nn): bump ggml to b6191 and wasi-nn plugin to 0.1.30
3e71cb1e feat(wasi-nn): remove llama_context_default_params, use default common_params value
=> Update `0.14.1_plugin_lts` branch

cmake/WASINNDeps.cmake, plugins/wasi_nn/CMakeLists.txt
=> feat(plugin): update the `0.15.0_plugin_lts` branch

include/host/wasi/environ.h, include/host/wasi/vfs_io.h, include/host/wasi/wasimodule.h, include/runtime/callingframe.h, include/runtime/instance/module.h, lib/api/wasmedge.cpp, lib/driver/runtimeTool.cpp, lib/executor/instantiate/import.cpp, lib/host/wasi/CMakeLists.txt, lib/host/wasi/environ.cpp, lib/host/wasi/vfs_io.cpp, plugins/wasi_nn/wasinn_ggml.cpp, plugins/wasi_nn/wasinn_mlx.cpp, plugins/wasi_nn/wasinn_whisper.cpp, plugins/wasi_nn/wasinnenv.h, plugins/wasi_nn/wasinnfunc.cpp, test/host/wasi/CMakeLists.txt, test/host/wasi/vfs_io.cpp
Implements a WasmEdge IO stream class (#4197).
=> feat(plugin): add WasmEdgeIOstream API

plugins/wasi_nn/wasinn_ggml.cpp
- Add macro to parse metadata
- Refactor parsing code
=> refactor(WASI-NN/GGML): parse metadata
